// accent_data_1kyu.js
// 1級アクセント問題データ（コピペ用）
// - sylRaw は元データ（ˈ を含む）を保持
// - 出題表示で ˈ を消す／正解後に sylRaw を見せる…が可能

(function () {
  window.ACCENT_1KYU = [
    { blockId: 1, no: 1, en: "absence", ja: "欠席", sylRaw: "ˈab-sence", stress: 1, note: "" },
    { blockId: 1, no: 2, en: "absolute", ja: "絶対的な", sylRaw: "ˈab-so-lute", stress: 1, note: "" },
    { blockId: 1, no: 3, en: "account", ja: "勘定、説明", sylRaw: "ac-ˈcount", stress: 2, note: "" },
    { blockId: 1, no: 4, en: "acid", ja: "酸", sylRaw: "ˈac-id", stress: 1, note: "" },
    { blockId: 1, no: 5, en: "activity", ja: "活動", sylRaw: "ac-ˈtiv-i-ty", stress: 2, note: "-ic, -ics, -ical. -ityは直前母音" },
    { blockId: 1, no: 6, en: "advertisement", ja: "広告", sylRaw: "ad-ver-ˈtise-ment", stress: 3, note: "" },
    { blockId: 1, no: 7, en: "addition", ja: "追加", sylRaw: "ad-ˈdi-tion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 1, no: 8, en: "adopt", ja: "採用する、養子にする", sylRaw: "a-ˈdopt", stress: 2, note: "" },
    { blockId: 1, no: 9, en: "advance", ja: "前進する／前進", sylRaw: "ad-ˈvance", stress: 2, note: "" },
    { blockId: 1, no: 10, en: "advantage", ja: "利点", sylRaw: "ad-ˈvan-tage", stress: 2, note: "" },
    { blockId: 1, no: 11, en: "advertise", ja: "広告する", sylRaw: "ˈad-ver-tise", stress: 1, note: "" },
    { blockId: 1, no: 12, en: "affair", ja: "事柄、出来事", sylRaw: "af-ˈfair", stress: 2, note: "" },
    { blockId: 1, no: 13, en: "affect", ja: "影響を与える", sylRaw: "af-ˈfect", stress: 2, note: "" },
    { blockId: 1, no: 14, en: "afford", ja: "～する余裕がある", sylRaw: "af-ˈford", stress: 2, note: "" },
    { blockId: 1, no: 15, en: "agent", ja: "代理人", sylRaw: "ˈa-gent", stress: 1, note: "" },
    { blockId: 1, no: 16, en: "agreement", ja: "合意", sylRaw: "a-gree-ˈment", stress: 2, note: "" },
    { blockId: 1, no: 17, en: "agriculture", ja: "農業", sylRaw: "ˈag-ri-cul-ture", stress: 1, note: "" },
    { blockId: 1, no: 18, en: "aid", ja: "援助", sylRaw: "ˈaid", stress: 1, note: "" },
    { blockId: 1, no: 19, en: "alarm", ja: "警報、驚かせる", sylRaw: "a-ˈlarm", stress: 2, note: "" },
    { blockId: 1, no: 20, en: "ambitious", ja: "野心的な", sylRaw: "am-ˈbi-tious", stress: 2, note: "-ate, -ousは二つ前母音" },
    { blockId: 1, no: 21, en: "amusement", ja: "娯楽", sylRaw: "a-ˈmuse-ment", stress: 2, note: "" },
    { blockId: 1, no: 22, en: "angle", ja: "角度", sylRaw: "ˈan-gle", stress: 1, note: "" },
    { blockId: 1, no: 23, en: "anyhow", ja: "とにかく", sylRaw: "ˈany-how", stress: 1, note: "" },
    { blockId: 1, no: 24, en: "apologize", ja: "謝る", sylRaw: "a-ˈpol-o-gize", stress: 2, note: "" },
    { blockId: 1, no: 25, en: "apparent", ja: "明らかな", sylRaw: "ap-ˈpar-ent", stress: 2, note: "" },
    { blockId: 1, no: 26, en: "applicant", ja: "応募者", sylRaw: "ˈap-pli-cant", stress: 1, note: "" },
    { blockId: 1, no: 27, en: "application", ja: "応募、申請", sylRaw: "ap-pli-ˈca-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 1, no: 28, en: "appoint", ja: "任命する", sylRaw: "ap-ˈpoint", stress: 2, note: "" },
    { blockId: 1, no: 29, en: "appointment", ja: "予約、任命", sylRaw: "ap-ˈpoint-ment", stress: 2, note: "" },
    { blockId: 1, no: 30, en: "appreciate", ja: "感謝する、理解する", sylRaw: "ap-ˈpre-ci-ate", stress: 2, note: "-ate, -ousは二つ前母音" },
    { blockId: 1, no: 31, en: "approve", ja: "承認する", sylRaw: "ap-ˈprove", stress: 2, note: "" },
    { blockId: 1, no: 32, en: "argue", ja: "議論する", sylRaw: "ˈar-gue", stress: 1, note: "" },
    { blockId: 1, no: 33, en: "argument", ja: "議論", sylRaw: "ˈar-gu-ment", stress: 1, note: "" },
    { blockId: 1, no: 34, en: "arise", ja: "生じる", sylRaw: "a-ˈrise", stress: 2, note: "" },
    { blockId: 1, no: 35, en: "arrest", ja: "逮捕する", sylRaw: "ar-ˈrest", stress: 2, note: "" },
    { blockId: 1, no: 36, en: "article", ja: "記事", sylRaw: "ˈar-ti-cle", stress: 1, note: "" },
    { blockId: 1, no: 37, en: "artificial", ja: "人工の", sylRaw: "ar-ti-ˈfi-cial", stress: 3, note: "-ial, -ualは直前母音" },
    { blockId: 1, no: 38, en: "ash", ja: "灰", sylRaw: "ˈash", stress: 1, note: "" },
    { blockId: 1, no: 39, en: "association", ja: "協会、関連", sylRaw: "as-so-ci-ˈa-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 1, no: 40, en: "astronaut", ja: "宇宙飛行士", sylRaw: "ˈas-tro-naut", stress: 1, note: "" },
    { blockId: 1, no: 41, en: "attach", ja: "取り付ける", sylRaw: "at-ˈtach", stress: 2, note: "" },
    { blockId: 1, no: 42, en: "attract", ja: "引きつける", sylRaw: "at-ˈtract", stress: 2, note: "" },
    { blockId: 1, no: 43, en: "attractive", ja: "魅力的な", sylRaw: "at-ˈtrac-tive", stress: 2, note: "" },
    { blockId: 1, no: 44, en: "audience", ja: "聴衆", sylRaw: "ˈau-di-ence", stress: 1, note: "" },
    { blockId: 1, no: 45, en: "author", ja: "著者", sylRaw: "ˈau-thor", stress: 1, note: "" },
    { blockId: 1, no: 46, en: "available", ja: "利用できる", sylRaw: "a-ˈvail-a-ble", stress: 2, note: "" },
    { blockId: 1, no: 47, en: "background", ja: "背景", sylRaw: "ˈback-ground", stress: 1, note: "" },
    { blockId: 1, no: 48, en: "bar", ja: "棒、酒場", sylRaw: "ˈbar", stress: 1, note: "" },
    { blockId: 1, no: 49, en: "bare", ja: "裸の", sylRaw: "ˈbare", stress: 1, note: "" },
    { blockId: 1, no: 50, en: "behave", ja: "振る舞う", sylRaw: "be-ˈhave", stress: 2, note: "" },

    { blockId: 2, no: 51, en: "belief", ja: "信念", sylRaw: "be-ˈlief", stress: 2, note: "" },
    { blockId: 2, no: 52, en: "benefit", ja: "利益", sylRaw: "ˈben-e-fit", stress: 1, note: "" },
    { blockId: 2, no: 53, en: "bind", ja: "縛る", sylRaw: "ˈbind", stress: 1, note: "" },
    { blockId: 2, no: 54, en: "bitter", ja: "苦い", sylRaw: "ˈbit-ter", stress: 1, note: "" },
    { blockId: 2, no: 55, en: "blank", ja: "空白", sylRaw: "ˈblank", stress: 1, note: "" },
    { blockId: 2, no: 56, en: "bless", ja: "祝福する", sylRaw: "ˈbless", stress: 1, note: "" },
    { blockId: 2, no: 57, en: "boast", ja: "自慢する", sylRaw: "ˈboast", stress: 1, note: "" },
    { blockId: 2, no: 58, en: "bold", ja: "大胆な", sylRaw: "ˈbold", stress: 1, note: "" },
    { blockId: 2, no: 59, en: "border", ja: "国境", sylRaw: "ˈbor-der", stress: 1, note: "" },
    { blockId: 2, no: 60, en: "bore", ja: "退屈させる", sylRaw: "ˈbore", stress: 1, note: "" },
    { blockId: 2, no: 61, en: "bother", ja: "悩ませる", sylRaw: "ˈboth-er", stress: 1, note: "" },
    { blockId: 2, no: 62, en: "brain", ja: "脳", sylRaw: "ˈbrain", stress: 1, note: "" },
    { blockId: 2, no: 63, en: "brake", ja: "ブレーキ", sylRaw: "ˈbrake", stress: 1, note: "" },
    { blockId: 2, no: 64, en: "bride", ja: "花嫁", sylRaw: "ˈbride", stress: 1, note: "" },
    { blockId: 2, no: 65, en: "brief", ja: "簡潔な", sylRaw: "ˈbrief", stress: 1, note: "" },
    { blockId: 2, no: 66, en: "broadcast", ja: "放送する", sylRaw: "ˈbroad-cast", stress: 1, note: "" },
    { blockId: 2, no: 67, en: "bud", ja: "つぼみ", sylRaw: "ˈbud", stress: 1, note: "" },
    { blockId: 2, no: 68, en: "burst", ja: "破裂する", sylRaw: "ˈburst", stress: 1, note: "" },
    { blockId: 2, no: 69, en: "calculator", ja: "計算機", sylRaw: "ˈcal-cu-la-tor", stress: 1, note: "" },
    { blockId: 2, no: 70, en: "capacity", ja: "能力、容量", sylRaw: "ca-ˈpac-i-ty", stress: 2, note: "-ic, -ics, -ical. -ityは直前母音" },
    { blockId: 2, no: 71, en: "career", ja: "職業", sylRaw: "ca-ˈreer", stress: 2, note: "" },
    { blockId: 2, no: 72, en: "carriage", ja: "馬車", sylRaw: "ˈcar-riage", stress: 1, note: "" },
    { blockId: 2, no: 73, en: "cast", ja: "投げる", sylRaw: "ˈcast", stress: 1, note: "" },
    { blockId: 2, no: 74, en: "catalog", ja: "目録", sylRaw: "ˈcat-a-log", stress: 1, note: "" },
    { blockId: 2, no: 75, en: "celebrate", ja: "祝う", sylRaw: "ˈcel-e-brate", stress: 1, note: "-ate, -ousは二つ前母音にアクセント" },
    { blockId: 2, no: 76, en: "ceremony", ja: "式典", sylRaw: "ˈcer-e-mo-ny", stress: 1, note: "" },
    { blockId: 2, no: 77, en: "channel", ja: "水路、チャンネル", sylRaw: "ˈchan-nel", stress: 1, note: "" },
    { blockId: 2, no: 78, en: "chapter", ja: "章", sylRaw: "ˈchap-ter", stress: 1, note: "" },
    { blockId: 2, no: 79, en: "charge", ja: "料金、責任", sylRaw: "ˈcharge", stress: 1, note: "" },
    { blockId: 2, no: 80, en: "charm", ja: "魅力", sylRaw: "ˈcharm", stress: 1, note: "" },
    { blockId: 2, no: 81, en: "chase", ja: "追いかける", sylRaw: "ˈchase", stress: 1, note: "" },
    { blockId: 2, no: 82, en: "childhood", ja: "子ども時代", sylRaw: "ˈchild-hood", stress: 1, note: "" },
    { blockId: 2, no: 83, en: "circumstance", ja: "状況", sylRaw: "ˈcir-cum-stance", stress: 1, note: "" },
    { blockId: 2, no: 84, en: "civilization", ja: "文明", sylRaw: "civ-i-li-zaˈ-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 2, no: 85, en: "claim", ja: "主張する", sylRaw: "ˈclaim", stress: 1, note: "" },
    { blockId: 2, no: 86, en: "clothe", ja: "服を着せる", sylRaw: "ˈclothe", stress: 1, note: "" },
    { blockId: 2, no: 87, en: "collar", ja: "えり", sylRaw: "ˈcol-lar", stress: 1, note: "" },
    { blockId: 2, no: 88, en: "combination", ja: "組み合わせ", sylRaw: "com-bi-ˈna-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 2, no: 89, en: "combine", ja: "結合する", sylRaw: "ˈcom-bine", stress: 2, note: "" },
    { blockId: 2, no: 90, en: "command", ja: "命令する", sylRaw: "com-ˈmand", stress: 2, note: "" },
    { blockId: 2, no: 91, en: "committee", ja: "委員会", sylRaw: "com-ˈmit-tee", stress: 2, note: "通常eeのような母音の連続しているところにアクセントがくるが、committeeは例外でiにアクセントがくる。" },
    { blockId: 2, no: 92, en: "commodity", ja: "商品", sylRaw: "com-ˈmod-i-ty", stress: 2, note: "-ic, -ics, -ical. -ityは直前母音" },
    { blockId: 2, no: 93, en: "competition", ja: "競争", sylRaw: "com-pe-ˈti-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 2, no: 94, en: "compose", ja: "構成する", sylRaw: "com-ˈpose", stress: 2, note: "" },
    { blockId: 2, no: 95, en: "concentrate", ja: "集中する", sylRaw: "ˈcon-cen-trate", stress: 1, note: "-ate, -ous は二つ前母音にアクセント" },
    { blockId: 2, no: 96, en: "concern", ja: "関心", sylRaw: "con-ˈcern", stress: 2, note: "" },
    { blockId: 2, no: 97, en: "conclude", ja: "結論づける", sylRaw: "con-ˈclude", stress: 2, note: "" },
    { blockId: 2, no: 98, en: "conclusion", ja: "結論", sylRaw: "con-ˈclu-sion", stress: 2, note: "-cian, -tion, -sionは直前母音にアクセント" },
    { blockId: 2, no: 99, en: "confidence", ja: "自信", sylRaw: "ˈcon-fi-dence", stress: 1, note: "" },
    { blockId: 2, no: 100, en: "confuse", ja: "混乱させる", sylRaw: "con-ˈfuse", stress: 2, note: "" },
    { blockId: 3, no: 101, en: "confusion", ja: "混乱", sylRaw: "con-ˈfu-sion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 3, no: 102, en: "congratulate", ja: "祝う", sylRaw: "con-ˈgrat-u-late", stress: 2, note: "" },
    { blockId: 3, no: 103, en: "congratulation", ja: "祝賀", sylRaw: "con-grat-u-ˈla-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 3, no: 104, en: "connect", ja: "接続する", sylRaw: "con-ˈnect", stress: 2, note: "" },
    { blockId: 3, no: 105, en: "connection", ja: "接続、関係", sylRaw: "con-ˈnec-tion", stress: 2, note: "-cian, -tion, -sionは直前母音にアクセント" },
    { blockId: 3, no: 106, en: "consist", ja: "成り立つ", sylRaw: "con-ˈsist", stress: 2, note: "" },
    { blockId: 3, no: 107, en: "constant", ja: "一定の", sylRaw: "ˈcon-stant", stress: 1, note: "" },
    { blockId: 3, no: 108, en: "consult", ja: "相談する", sylRaw: "con-ˈsult", stress: 2, note: "" },
    { blockId: 3, no: 109, en: "consumer", ja: "消費者", sylRaw: "con-ˈsumer", stress: 2, note: "" },
    { blockId: 3, no: 110, en: "contact", ja: "接触、連絡", sylRaw: "ˈcon-tact", stress: 1, note: "" },
    { blockId: 3, no: 111, en: "content", ja: "内容", sylRaw: "ˈcon-tent", stress: 1, note: "" },
    { blockId: 3, no: 112, en: "continent", ja: "大陸", sylRaw: "ˈcon-ti-nent", stress: 1, note: "" },
    { blockId: 3, no: 113, en: "contrast", ja: "対照", sylRaw: "ˈcon-trast", stress: 1, note: "対比するという動詞で使う場合はtrastにアクセントをおく（名前動後)" },
    { blockId: 3, no: 114, en: "copper", ja: "銅", sylRaw: "ˈcop-per", stress: 1, note: "" },
    { blockId: 3, no: 115, en: "cord", ja: "ひも", sylRaw: "ˈcord", stress: 1, note: "" },
    { blockId: 3, no: 116, en: "cough", ja: "咳", sylRaw: "ˈcough", stress: 1, note: "" },
    { blockId: 3, no: 117, en: "crash", ja: "衝突する", sylRaw: "ˈcrash", stress: 1, note: "" },
    { blockId: 3, no: 118, en: "crawl", ja: "はう", sylRaw: "ˈcrawl", stress: 1, note: "" },
    { blockId: 3, no: 119, en: "crime", ja: "犯罪", sylRaw: "ˈcrime", stress: 1, note: "" },
    { blockId: 3, no: 120, en: "cruel", ja: "残酷な", sylRaw: "ˈcru-el", stress: 1, note: "" },
    { blockId: 3, no: 121, en: "cultivate", ja: "耕す", sylRaw: "ˈcul-ti-vate", stress: 1, note: "" },
    { blockId: 3, no: 122, en: "cultural", ja: "文化の", sylRaw: "ˈcul-tur-al", stress: 1, note: "" },
    { blockId: 3, no: 123, en: "cure", ja: "治す", sylRaw: "ˈcure", stress: 1, note: "" },
    { blockId: 3, no: 124, en: "current", ja: "現在の", sylRaw: "ˈcur-rent", stress: 1, note: "" },
    { blockId: 3, no: 125, en: "curve", ja: "曲線", sylRaw: "ˈcurve", stress: 1, note: "" },
    { blockId: 3, no: 126, en: "dare", ja: "あえて～する", sylRaw: "ˈdare", stress: 1, note: "" },
    { blockId: 3, no: 127, en: "debt", ja: "借金", sylRaw: "ˈdebt", stress: 1, note: "" },
    { blockId: 3, no: 128, en: "decision", ja: "決定", sylRaw: "de-ˈci-sion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 3, no: 129, en: "decorate", ja: "飾る", sylRaw: "ˈdec-o-rate", stress: 1, note: "-ate,-ousは2つ前母音" },
    { blockId: 3, no: 130, en: "decrease", ja: "減少する", sylRaw: "de-ˈcrease", stress: 2, note: "" },
    { blockId: 3, no: 131, en: "defeat", ja: "打ち負かす", sylRaw: "de-ˈfeat", stress: 2, note: "" },
    { blockId: 3, no: 132, en: "defend", ja: "守る", sylRaw: "de-ˈfend", stress: 2, note: "" },
    { blockId: 3, no: 133, en: "delay", ja: "遅らせる", sylRaw: "de-ˈlay", stress: 2, note: "" },
    { blockId: 3, no: 134, en: "delicate", ja: "繊細な", sylRaw: "ˈdel-i-cate", stress: 1, note: "-ate,-ousは２つ前母音" },
    { blockId: 3, no: 135, en: "deny", ja: "否定する", sylRaw: "de-ˈny", stress: 2, note: "" },
    { blockId: 3, no: 136, en: "describe", ja: "描写する", sylRaw: "de-ˈscribe", stress: 2, note: "" },
    { blockId: 3, no: 137, en: "description", ja: "描写", sylRaw: "de-ˈscrip-tion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 3, no: 138, en: "detail", ja: "詳細", sylRaw: "ˈde-tail", stress: 1, note: "deTAILと第２音節に置く場合もあるが基本は第一音節でOK" },
    { blockId: 3, no: 139, en: "determine", ja: "決定する", sylRaw: "de-ˈter-mine", stress: 2, note: "" },
    { blockId: 3, no: 140, en: "development", ja: "発展", sylRaw: "de-ˈvel-op-ment", stress: 2, note: "" },
    { blockId: 3, no: 141, en: "devil", ja: "悪魔", sylRaw: "ˈdev-il", stress: 1, note: "" },
    { blockId: 3, no: 142, en: "digest", ja: "消化する", sylRaw: "di-ˈgest", stress: 2, note: "" },
    { blockId: 3, no: 143, en: "dine", ja: "食事をする", sylRaw: "ˈdine", stress: 1, note: "" },
    { blockId: 3, no: 144, en: "director", ja: "監督、責任者", sylRaw: "di-ˈrec-tor", stress: 2, note: "" },
    { blockId: 3, no: 145, en: "discount", ja: "割引", sylRaw: "ˈdis-count", stress: 1, note: "" },
    { blockId: 3, no: 146, en: "display", ja: "展示する", sylRaw: "dis-ˈplay", stress: 2, note: "" },
    { blockId: 3, no: 147, en: "distinct", ja: "明確な", sylRaw: "dis-ˈtinct", stress: 2, note: "" },
    { blockId: 3, no: 148, en: "disturb", ja: "妨げる", sylRaw: "dis-ˈturb", stress: 2, note: "" },
    { blockId: 3, no: 149, en: "dive", ja: "飛び込む", sylRaw: "ˈdive", stress: 1, note: "" },
    { blockId: 3, no: 150, en: "domestic", ja: "国内の", sylRaw: "do-ˈmes-tic", stress: 2, note: "-ic,-ics,-ical,-ityは直前母音" },

    { blockId: 4, no: 151, en: "drawer", ja: "引き出し", sylRaw: "ˈdraw-er", stress: 1, note: "" },
    { blockId: 4, no: 152, en: "due", ja: "期限の", sylRaw: "ˈdue", stress: 1, note: "" },
    { blockId: 4, no: 153, en: "dumb", ja: "ばかな", sylRaw: "ˈdumb", stress: 1, note: "" },
    { blockId: 4, no: 154, en: "economic", ja: "経済の", sylRaw: "e-co-ˈno-mic", stress: 3, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 4, no: 155, en: "economical", ja: "経済的な", sylRaw: "e-co-ˈno-mi-cal", stress: 3, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 4, no: 156, en: "editor", ja: "編集者", sylRaw: "ˈed-i-tor", stress: 1, note: "" },
    { blockId: 4, no: 157, en: "effective", ja: "効果的な", sylRaw: "ef-ˈfec-tive", stress: 2, note: "" },
    { blockId: 4, no: 158, en: "embarrass", ja: "当惑させる", sylRaw: "em-ˈbar-rass", stress: 2, note: "" },
    { blockId: 4, no: 159, en: "emergency", ja: "緊急事態", sylRaw: "e-ˈmer-gen-cy", stress: 2, note: "" },
    { blockId: 4, no: 160, en: "employee", ja: "従業員", sylRaw: "em-ploy-ˈee", stress: 3, note: "同じ母音の連続にアクセント、enPLOYeeと第２音節にアクセントを置く場合もあるが、基本第３音節でＯＫ" },
    { blockId: 4, no: 161, en: "employer", ja: "雇用主", sylRaw: "em-ˈploy-er", stress: 2, note: "" },
    { blockId: 4, no: 162, en: "employment", ja: "雇用", sylRaw: "em-ˈploy-ment", stress: 2, note: "" },
    { blockId: 4, no: 163, en: "encourage", ja: "励ます", sylRaw: "en-ˈcour-age", stress: 2, note: "" },
    { blockId: 4, no: 164, en: "engage", ja: "従事する", sylRaw: "en-ˈgage", stress: 2, note: "" },
    { blockId: 4, no: 165, en: "environment", ja: "環境", sylRaw: "en-ˈvi-ron-ment", stress: 2, note: "" },
    { blockId: 4, no: 166, en: "envy", ja: "ねたみ", sylRaw: "ˈen-vy", stress: 1, note: "" },
    { blockId: 4, no: 167, en: "essential", ja: "必不可欠な", sylRaw: "es-ˈsen-tial", stress: 2, note: "-ial,-ualは直前母音" },
    { blockId: 4, no: 168, en: "estimate", ja: "見積もる", sylRaw: "ˈes-ti-mate", stress: 1, note: "-ate,-ousは二つ前母音" },
    { blockId: 4, no: 169, en: "evidence", ja: "証拠", sylRaw: "ˈev-i-dence", stress: 1, note: "" },
    { blockId: 4, no: 170, en: "evil", ja: "悪", sylRaw: "ˈe-vil", stress: 1, note: "" },
    { blockId: 4, no: 171, en: "exhibition", ja: "展覧会", sylRaw: "ex-hi-ˈbi-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 4, no: 172, en: "existence", ja: "存在", sylRaw: "ex-ˈis-tence", stress: 2, note: "" },
    { blockId: 4, no: 173, en: "expand", ja: "拡大する", sylRaw: "ex-ˈpand", stress: 2, note: "" },
    { blockId: 4, no: 174, en: "expense", ja: "費用", sylRaw: "ex-ˈpense", stress: 2, note: "" },
    { blockId: 4, no: 175, en: "expert", ja: "専門家", sylRaw: "ˈex-pert", stress: 1, note: "" },
    { blockId: 4, no: 176, en: "explore", ja: "探検する", sylRaw: "ex-ˈplore", stress: 2, note: "" },
    { blockId: 4, no: 177, en: "extend", ja: "延ばす", sylRaw: "ex-ˈtend", stress: 2, note: "" },
    { blockId: 4, no: 178, en: "extension", ja: "延長", sylRaw: "ex-ˈten-sion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 4, no: 179, en: "extent", ja: "程度", sylRaw: "ex-ˈtent", stress: 2, note: "" },
    { blockId: 4, no: 180, en: "extra", ja: "余分な", sylRaw: "ˈex-tra", stress: 1, note: "" },
    { blockId: 4, no: 181, en: "extreme", ja: "極端な", sylRaw: "ex-ˈtreme", stress: 2, note: "" },
    { blockId: 4, no: 182, en: "eyesight", ja: "視力", sylRaw: "ˈeye-sight", stress: 1, note: "" },
    { blockId: 4, no: 183, en: "failure", ja: "失敗", sylRaw: "ˈfail-ure", stress: 1, note: "" },
    { blockId: 4, no: 184, en: "faith", ja: "信仰", sylRaw: "ˈfaith", stress: 1, note: "" },
    { blockId: 4, no: 185, en: "fancy", ja: "空想", sylRaw: "ˈfan-cy", stress: 1, note: "" },
    { blockId: 4, no: 186, en: "fare", ja: "運賃", sylRaw: "ˈfare", stress: 1, note: "" },
    { blockId: 4, no: 187, en: "fashionable", ja: "流行の", sylRaw: "ˈfash-ion-able", stress: 1, note: "" },
    { blockId: 4, no: 188, en: "fate", ja: "運命", sylRaw: "ˈfate", stress: 1, note: "" },
    { blockId: 4, no: 189, en: "fearful", ja: "恐れている", sylRaw: "ˈfear-ful", stress: 1, note: "" },
    { blockId: 4, no: 190, en: "fierce", ja: "激しい", sylRaw: "ˈfierce", stress: 1, note: "" },
    { blockId: 4, no: 191, en: "figure", ja: "数字、人物", sylRaw: "ˈfig-ure", stress: 1, note: "" },
    { blockId: 4, no: 192, en: "flame", ja: "炎", sylRaw: "ˈflame", stress: 1, note: "" },
    { blockId: 4, no: 193, en: "flash", ja: "閃光", sylRaw: "ˈflash", stress: 1, note: "" },
    { blockId: 4, no: 194, en: "flour", ja: "小麦粉", sylRaw: "ˈflour", stress: 1, note: "" },
    { blockId: 4, no: 195, en: "fluent", ja: "流暢な", sylRaw: "ˈflu-ent", stress: 1, note: "" },
    { blockId: 4, no: 196, en: "fold", ja: "折る", sylRaw: "ˈfold", stress: 1, note: "" },
    { blockId: 4, no: 197, en: "forehead", ja: "額", sylRaw: "ˈfore-head", stress: 1, note: "" },
    { blockId: 4, no: 198, en: "frank", ja: "率直な", sylRaw: "ˈfrank", stress: 1, note: "" },
    { blockId: 4, no: 199, en: "freezer", ja: "冷凍庫", sylRaw: "ˈfreez-er", stress: 1, note: "" },
    { blockId: 4, no: 200, en: "frequent", ja: "頻繁な", sylRaw: "ˈfre-quent", stress: 1, note: "" },  
    { blockId: 5, no: 201, en: "frost", ja: "霜", sylRaw: "ˈfrost", stress: 1, note: "" },
    { blockId: 5, no: 202, en: "fuel", ja: "燃料", sylRaw: "ˈfu-el", stress: 1, note: "" },
    { blockId: 5, no: 203, en: "funeral", ja: "葬式", sylRaw: "ˈfu-ner-al", stress: 1, note: "" },
    { blockId: 5, no: 204, en: "garbage", ja: "ごみ", sylRaw: "ˈgar-bage", stress: 1, note: "" },
    { blockId: 5, no: 205, en: "generation", ja: "世代", sylRaw: "gen-er-ˈa-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 5, no: 206, en: "generous", ja: "寛大な", sylRaw: "ˈgen-er-ous", stress: 1, note: "-ate,-ousは二つ前母音" },
    { blockId: 5, no: 207, en: "ghost", ja: "幽霊", sylRaw: "ˈghost", stress: 1, note: "" },
    { blockId: 5, no: 208, en: "glance", ja: "ちらりと見る", sylRaw: "ˈglance", stress: 1, note: "" },
    { blockId: 5, no: 209, en: "globe", ja: "地球", sylRaw: "ˈglobe", stress: 1, note: "" },
    { blockId: 5, no: 210, en: "goods", ja: "商品", sylRaw: "ˈgoods", stress: 1, note: "" },
    { blockId: 5, no: 211, en: "grammar", ja: "文法", sylRaw: "ˈgram-mar", stress: 1, note: "" },
    { blockId: 5, no: 212, en: "grave", ja: "墓", sylRaw: "ˈgrave", stress: 1, note: "" },
    { blockId: 5, no: 213, en: "grief", ja: "悲しみ", sylRaw: "ˈgrief", stress: 1, note: "" },
    { blockId: 5, no: 214, en: "guarantee", ja: "保証する", sylRaw: "guar-an-ˈtee", stress: 3, note: "同じ母音の連続にアクセント" },
    { blockId: 5, no: 215, en: "guilty", ja: "有罪の", sylRaw: "ˈguilt-y", stress: 1, note: "" },
    { blockId: 5, no: 216, en: "halfway", ja: "途中で", sylRaw: "ˈhalf-way", stress: 1, note: "" },
    { blockId: 5, no: 217, en: "handicap", ja: "障害", sylRaw: "ˈhand-i-cap", stress: 1, note: "" },
    { blockId: 5, no: 218, en: "harmful", ja: "有害な", sylRaw: "ˈharm-ful", stress: 1, note: "" },
    { blockId: 5, no: 219, en: "harmony", ja: "調和", sylRaw: "ˈhar-mo-ny", stress: 1, note: "" },
    { blockId: 5, no: 220, en: "hesitate", ja: "ためらう", sylRaw: "ˈhes-i-tate", stress: 1, note: "-ate,-ousは二つ前母音" },
    { blockId: 5, no: 221, en: "hire", ja: "雇う", sylRaw: "ˈhire", stress: 1, note: "" },
    { blockId: 5, no: 222, en: "holy", ja: "神聖な", sylRaw: "ˈho-ly", stress: 1, note: "" },
    { blockId: 5, no: 223, en: "honesty", ja: "正直", sylRaw: "ˈhon-esty", stress: 1, note: "" },
    { blockId: 5, no: 224, en: "hook", ja: "かぎ", sylRaw: "ˈhook", stress: 1, note: "" },
    { blockId: 5, no: 225, en: "horizon", ja: "地平線", sylRaw: "ho-ˈri-zon", stress: 2, note: "" },
    { blockId: 5, no: 226, en: "horn", ja: "角", sylRaw: "ˈhorn", stress: 1, note: "" },
    { blockId: 5, no: 227, en: "human", ja: "人間の", sylRaw: "ˈhu-man", stress: 1, note: "" },
    { blockId: 5, no: 228, en: "humid", ja: "蒸し暑い", sylRaw: "ˈhu-mid", stress: 1, note: "" },
    { blockId: 5, no: 229, en: "humorous", ja: "ユーモアのある", sylRaw: "ˈhu-mor-ous", stress: 1, note: "-ate, -ousは二つ前母音" },
    { blockId: 5, no: 230, en: "ideal", ja: "理想", sylRaw: "i-ˈdeal", stress: 2, note: "" },
    { blockId: 5, no: 231, en: "identify", ja: "特定する", sylRaw: "i-ˈden-ti-fy", stress: 2, note: "" },
    { blockId: 5, no: 232, en: "imitate", ja: "まねる", sylRaw: "ˈim-i-tate", stress: 1, note: "-ate,-ousは二つ前母音" },
    { blockId: 5, no: 233, en: "imitation", ja: "模倣", sylRaw: "im-i-ˈta-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 5, no: 234, en: "impress", ja: "感銘を与える", sylRaw: "im-ˈpress", stress: 2, note: "" },
    { blockId: 5, no: 235, en: "impression", ja: "印象", sylRaw: "im-ˈpres-sion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 5, no: 236, en: "improve", ja: "改善する", sylRaw: "im-ˈprove", stress: 2, note: "" },
    { blockId: 5, no: 237, en: "improvement", ja: "改善", sylRaw: "im-ˈprove-ment", stress: 2, note: "" },
    { blockId: 5, no: 238, en: "include", ja: "含む", sylRaw: "in-ˈclude", stress: 2, note: "" },
    { blockId: 5, no: 239, en: "income", ja: "収入", sylRaw: "ˈin-come", stress: 1, note: "" },
    { blockId: 5, no: 240, en: "incredible", ja: "信じられない", sylRaw: "in-ˈcred-i-ble", stress: 2, note: "" },
    { blockId: 5, no: 241, en: "independence", ja: "独立", sylRaw: "in-de-ˈpen-dence", stress: 3, note: "" },
    { blockId: 5, no: 242, en: "indicate", ja: "示す", sylRaw: "ˈin-di-cate", stress: 1, note: "-ate,-ousは二つ前母音" },
    { blockId: 5, no: 243, en: "individual", ja: "個人", sylRaw: "in-di-ˈvid-u-al", stress: 3, note: "-ial,-ualは直前母音" },
    { blockId: 5, no: 244, en: "inferior", ja: "劣った", sylRaw: "in-ˈfe-ri-or", stress: 2, note: "" },
    { blockId: 5, no: 245, en: "inform", ja: "知らせる", sylRaw: "in-ˈform", stress: 2, note: "" },
    { blockId: 5, no: 246, en: "initial", ja: "初期の", sylRaw: "i-ˈni-tial", stress: 2, note: "-ial,-ualは直前母音" },
    { blockId: 5, no: 247, en: "injure", ja: "傷つける", sylRaw: "ˈin-jure", stress: 1, note: "" },
    { blockId: 5, no: 248, en: "injury", ja: "けが", sylRaw: "ˈin-jury", stress: 1, note: "" },
    { blockId: 5, no: 249, en: "innocence", ja: "無罪", sylRaw: "ˈin-no-cence", stress: 1, note: "" },
    { blockId: 5, no: 250, en: "innocent", ja: "無実の", sylRaw: "ˈin-no-cent", stress: 1, note: "" },

    { blockId: 6, no: 251, en: "inquire", ja: "尋ねる", sylRaw: "in-ˈquire", stress: 2, note: "" },
    { blockId: 6, no: 252, en: "inquiry", ja: "問い合わせ", sylRaw: "ˈin-quir-y", stress: 1, note: "inにアクセントを置くことがほとんどだが、quirの部分にアクセントを置く人もおり、どちらも辞書に載っているので、テストには出ない(はず）。" },
    { blockId: 6, no: 253, en: "insist", ja: "主張する", sylRaw: "in-ˈsist", stress: 2, note: "" },
    { blockId: 6, no: 254, en: "inspect", ja: "検査する", sylRaw: "in-ˈspect", stress: 2, note: "" },
    { blockId: 6, no: 255, en: "instrument", ja: "器具", sylRaw: "ˈin-stru-ment", stress: 1, note: "" },
    { blockId: 6, no: 256, en: "insurance", ja: "保険", sylRaw: "in-ˈsur-ance", stress: 2, note: "" },
    { blockId: 6, no: 257, en: "intention", ja: "意図", sylRaw: "in-ˈten-tion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 6, no: 258, en: "investigate", ja: "調査する", sylRaw: "in-ˈves-ti-gate", stress: 2, note: "-ate,-ousは二つ前母音" },
    { blockId: 6, no: 259, en: "investigation", ja: "調査", sylRaw: "in-ves-ti-ˈga-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 6, no: 260, en: "investment", ja: "投資", sylRaw: "in-ˈvest-ment", stress: 2, note: "" },
    { blockId: 6, no: 261, en: "invoice", ja: "請求書", sylRaw: "ˈin-voice", stress: 1, note: "" },
    { blockId: 6, no: 262, en: "involve", ja: "関係させる", sylRaw: "in-ˈvolve", stress: 2, note: "" },
    { blockId: 6, no: 263, en: "issue", ja: "問題", sylRaw: "ˈis-sue", stress: 1, note: "" },
    { blockId: 6, no: 264, en: "item", ja: "品目", sylRaw: "ˈi-tem", stress: 1, note: "" },
    { blockId: 6, no: 265, en: "jail", ja: "刑務所", sylRaw: "ˈjail", stress: 1, note: "" },
    { blockId: 6, no: 266, en: "journal", ja: "日記、雑誌", sylRaw: "ˈjour-nal", stress: 1, note: "" },
    { blockId: 6, no: 267, en: "judgment", ja: "判断", sylRaw: "ˈjudg-ment", stress: 1, note: "" },
    { blockId: 6, no: 268, en: "justice", ja: "正義", sylRaw: "ˈjus-tice", stress: 1, note: "" },
    { blockId: 6, no: 269, en: "keen", ja: "鋭い", sylRaw: "ˈkeen", stress: 1, note: "" },
    { blockId: 6, no: 270, en: "labor", ja: "労働", sylRaw: "ˈla-bor", stress: 1, note: "" },
    { blockId: 6, no: 271, en: "lawyer", ja: "弁護士", sylRaw: "ˈlaw-yer", stress: 1, note: "" },
    { blockId: 6, no: 272, en: "leak", ja: "漏れる", sylRaw: "ˈleak", stress: 1, note: "" },
    { blockId: 6, no: 273, en: "lean", ja: "傾く", sylRaw: "ˈlean", stress: 1, note: "" },
    { blockId: 6, no: 274, en: "leather", ja: "革", sylRaw: "ˈleath-er", stress: 1, note: "" },
    { blockId: 6, no: 275, en: "lecture", ja: "講義", sylRaw: "ˈlec-ture", stress: 1, note: "" },
    { blockId: 6, no: 276, en: "librarian", ja: "図書館員", sylRaw: "li-ˈbrar-i-an", stress: 2, note: "" },
    { blockId: 6, no: 277, en: "license", ja: "免許", sylRaw: "ˈli-cense", stress: 1, note: "" },
    { blockId: 6, no: 278, en: "liquid", ja: "液体", sylRaw: "ˈliq-uid", stress: 1, note: "" },
    { blockId: 6, no: 279, en: "literature", ja: "文学", sylRaw: "ˈlit-er-a-ture", stress: 1, note: "" },
    { blockId: 6, no: 280, en: "local", ja: "地元の", sylRaw: "ˈlo-cal", stress: 1, note: "" },
    { blockId: 6, no: 281, en: "locate", ja: "位置する", sylRaw: "ˈlo-cate", stress: 1, note: "" },
    { blockId: 6, no: 282, en: "luxurious", ja: "豪華な", sylRaw: "lux-ˈu-ri-ous", stress: 2, note: "-ate,-ousは二つ前母音" },
    { blockId: 6, no: 283, en: "luxury", ja: "贅沢", sylRaw: "ˈlux-u-ry", stress: 1, note: "" },
    { blockId: 6, no: 284, en: "majority", ja: "大多数", sylRaw: "ma-ˈjor-i-ty", stress: 2, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 6, no: 285, en: "manufacture", ja: "製造する", sylRaw: "man-u-ˈfac-ture", stress: 3, note: "" },
    { blockId: 6, no: 286, en: "mass", ja: "大量", sylRaw: "ˈmass", stress: 1, note: "" },
    { blockId: 6, no: 287, en: "maximum", ja: "最大", sylRaw: "ˈmax-i-mum", stress: 1, note: "" },
    { blockId: 6, no: 288, en: "mayor", ja: "市長", sylRaw: "ˈmay-or", stress: 1, note: "" },
    { blockId: 6, no: 289, en: "means", ja: "手段", sylRaw: "ˈmeans", stress: 1, note: "" },
    { blockId: 6, no: 290, en: "medical", ja: "医学の", sylRaw: "ˈmed-i-cal", stress: 1, note: "" },
    { blockId: 6, no: 291, en: "memorize", ja: "暗記する", sylRaw: "ˈmem-o-rize", stress: 1, note: "" },
    { blockId: 6, no: 292, en: "mention", ja: "言及する", sylRaw: "ˈmen-tion", stress: 1, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 6, no: 293, en: "merit", ja: "長所", sylRaw: "ˈmer-it", stress: 1, note: "" },
    { blockId: 6, no: 294, en: "method", ja: "方法", sylRaw: "ˈmeth-od", stress: 1, note: "" },
    { blockId: 6, no: 295, en: "minimum", ja: "最小", sylRaw: "ˈmin-i-mum", stress: 1, note: "" },
    { blockId: 6, no: 296, en: "minority", ja: "少数", sylRaw: "mi-ˈnor-i-ty", stress: 2, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 6, no: 297, en: "miracle", ja: "奇跡", sylRaw: "ˈmir-a-cle", stress: 1, note: "" },
    { blockId: 6, no: 298, en: "miserable", ja: "みじめな", sylRaw: "ˈmis-er-able", stress: 1, note: "" },
    { blockId: 6, no: 299, en: "modest", ja: "控えめな", sylRaw: "ˈmod-est", stress: 1, note: "" },
    { blockId: 6, no: 300, en: "monthly", ja: "毎月の", sylRaw: "ˈmonth-ly", stress: 1, note: "" },

    { blockId: 7, no: 301, en: "moral", ja: "道徳", sylRaw: "ˈmo-ral", stress: 1, note: "" },
    { blockId: 7, no: 302, en: "moreover", ja: "さらに", sylRaw: "more-ˈo-ver", stress: 2, note: "" },
    { blockId: 7, no: 303, en: "motion", ja: "動き", sylRaw: "ˈmo-tion", stress: 1, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 304, en: "mutual", ja: "相互の", sylRaw: "ˈmu-tu-al", stress: 1, note: "-ial,-ualは直前母音" },
    { blockId: 7, no: 305, en: "mysterious", ja: "不思議な", sylRaw: "mys-ˈte-ri-ous", stress: 2, note: "-ate,-ousは二つ前母音" },
    { blockId: 7, no: 306, en: "mystery", ja: "謎", sylRaw: "ˈmys-tery", stress: 1, note: "" },
    { blockId: 7, no: 307, en: "neat", ja: "きちんとした", sylRaw: "ˈneat", stress: 1, note: "" },
    { blockId: 7, no: 308, en: "negative", ja: "否定的な", sylRaw: "ˈneg-a-tive", stress: 1, note: "" },
    { blockId: 7, no: 309, en: "neglect", ja: "無視する", sylRaw: "ne-ˈglect", stress: 2, note: "" },
    { blockId: 7, no: 310, en: "neighborhood", ja: "近所", sylRaw: "ˈneigh-bor-hood", stress: 1, note: "" },
    { blockId: 7, no: 311, en: "nephew", ja: "甥", sylRaw: "ˈneph-ew", stress: 1, note: "" },
    { blockId: 7, no: 312, en: "niece", ja: "姪", sylRaw: "ˈniece", stress: 1, note: "" },
    { blockId: 7, no: 313, en: "normal", ja: "普通の", sylRaw: "ˈnor-mal", stress: 1, note: "" },
    { blockId: 7, no: 314, en: "nuclear", ja: "核の", sylRaw: "ˈnu-cle-ar", stress: 1, note: "" },
    { blockId: 7, no: 315, en: "obedient", ja: "従順な", sylRaw: "o-ˈbe-di-ent", stress: 2, note: "" },
    { blockId: 7, no: 316, en: "observation", ja: "観察", sylRaw: "ob-ser-ˈva-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 317, en: "observe", ja: "観察する", sylRaw: "ob-ˈserve", stress: 2, note: "" },
    { blockId: 7, no: 318, en: "occasional", ja: "時々の", sylRaw: "oc-ˈca-sion-al", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 319, en: "occupation", ja: "職業", sylRaw: "oc-cu-ˈpa-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 320, en: "occupy", ja: "占める", sylRaw: "ˈoc-cu-py", stress: 1, note: "" },
    { blockId: 7, no: 321, en: "occur", ja: "起こる", sylRaw: "oc-ˈcur", stress: 2, note: "" },
    { blockId: 7, no: 322, en: "omit", ja: "省く", sylRaw: "ˈo-mit", stress: 2, note: "" },
    { blockId: 7, no: 323, en: "opportunity", ja: "機会", sylRaw: "op-por-ˈtu-ni-ty", stress: 3, note: "" },
    { blockId: 7, no: 324, en: "oppose", ja: "反対する", sylRaw: "op-ˈpose", stress: 2, note: "" },
    { blockId: 7, no: 325, en: "oral", ja: "口頭の", sylRaw: "ˈo-ral", stress: 1, note: "" },
    { blockId: 7, no: 326, en: "organization", ja: "組織", sylRaw: "or-ga-ni-ˈza-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 327, en: "organize", ja: "組織する", sylRaw: "ˈor-ga-nize", stress: 1, note: "" },
    { blockId: 7, no: 328, en: "otherwise", ja: "そうでなければ", sylRaw: "ˈoth-er-wise", stress: 1, note: "" },
    { blockId: 7, no: 329, en: "oxygen", ja: "酸素", sylRaw: "ˈox-y-gen", stress: 1, note: "" },
    { blockId: 7, no: 330, en: "parcel", ja: "小包", sylRaw: "ˈpar-cel", stress: 1, note: "" },
    { blockId: 7, no: 331, en: "passage", ja: "通路", sylRaw: "ˈpas-sage", stress: 1, note: "" },
    { blockId: 7, no: 332, en: "paste", ja: "のり", sylRaw: "ˈpaste", stress: 1, note: "" },
    { blockId: 7, no: 333, en: "pause", ja: "休止", sylRaw: "ˈpause", stress: 1, note: "" },
    { blockId: 7, no: 334, en: "pavement", ja: "歩道", sylRaw: "ˈpave-ment", stress: 1, note: "" },
    { blockId: 7, no: 335, en: "payment", ja: "支払い", sylRaw: "ˈpay-ment", stress: 1, note: "" },
    { blockId: 7, no: 336, en: "performance", ja: "公演、成績", sylRaw: "per-ˈfor-mance", stress: 2, note: "" },
    { blockId: 7, no: 337, en: "permanent", ja: "永久の", sylRaw: "ˈper-ma-nent", stress: 1, note: "" },
    { blockId: 7, no: 338, en: "permission", ja: "許可", sylRaw: "per-ˈmis-sion", stress: 2, note: "" },
    { blockId: 7, no: 339, en: "persuade", ja: "説得する", sylRaw: "per-ˈsuade", stress: 2, note: "" },
    { blockId: 7, no: 340, en: "philosophy", ja: "哲学", sylRaw: "phi-ˈlos-o-phy", stress: 2, note: "" },
    { blockId: 7, no: 341, en: "pigeon", ja: "ハト", sylRaw: "ˈpi-geon", stress: 1, note: "" },
    { blockId: 7, no: 342, en: "pile", ja: "積み重ね", sylRaw: "ˈpile", stress: 1, note: "" },
    { blockId: 7, no: 343, en: "planet", ja: "惑星", sylRaw: "ˈplan-et", stress: 1, note: "" },
    { blockId: 7, no: 344, en: "poison", ja: "毒", sylRaw: "ˈpoi-son", stress: 1, note: "" },
    { blockId: 7, no: 345, en: "policy", ja: "政策", sylRaw: "ˈpol-i-cy", stress: 1, note: "" },
    { blockId: 7, no: 346, en: "political", ja: "政治の", sylRaw: "po-ˈlit-i-cal", stress: 2, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 7, no: 347, en: "politician", ja: "政治家", sylRaw: "pol-i-ˈti-cian", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 7, no: 348, en: "politics", ja: "政治", sylRaw: "ˈpol-i-tics", stress: 1, note: "-icsだがこれは例外的に第一音節にアクセント" },
    { blockId: 7, no: 349, en: "positive", ja: "肯定的な", sylRaw: "ˈpos-i-tive", stress: 1, note: "" },
    { blockId: 7, no: 350, en: "possibility", ja: "可能性", sylRaw: "pos-si-ˈbil-i-ty", stress: 3, note: "-ic,-ics,-ical,-ityは直前母音" },
    { blockId: 8, no: 351, en: "poverty", ja: "貧困", sylRaw: "ˈpo-ver-ty", stress: 1, note: "" },
    { blockId: 8, no: 352, en: "praise", ja: "ほめる", sylRaw: "ˈpraise", stress: 1, note: "" },
    { blockId: 8, no: 353, en: "pray", ja: "祈る", sylRaw: "ˈpray", stress: 1, note: "" },
    { blockId: 8, no: 354, en: "preparation", ja: "準備", sylRaw: "prep-a-ra-ˈtion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 355, en: "pretend", ja: "ふりをする", sylRaw: "pre-ˈtend", stress: 2, note: "" },
    { blockId: 8, no: 356, en: "principle", ja: "原理、主義", sylRaw: "ˈprin-ci-ple", stress: 1, note: "" },
    { blockId: 8, no: 357, en: "process", ja: "過程", sylRaw: "ˈpro-cess", stress: 1, note: "" },
    { blockId: 8, no: 358, en: "profession", ja: "職業", sylRaw: "pro-ˈfes-sion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 359, en: "professor", ja: "教授", sylRaw: "pro-ˈfes-sor", stress: 2, note: "" },
    { blockId: 8, no: 360, en: "profit", ja: "利益", sylRaw: "ˈprof-it", stress: 1, note: "" },
    { blockId: 8, no: 361, en: "project", ja: "計画", sylRaw: "ˈproj-ect", stress: 1, note: "" },
    { blockId: 8, no: 362, en: "pronounce", ja: "発音する", sylRaw: "pro-ˈnounce", stress: 2, note: "" },
    { blockId: 8, no: 363, en: "pronunciation", ja: "発音", sylRaw: "pro-nun-ci-ˈa-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 364, en: "proposal", ja: "提案", sylRaw: "pro-ˈpos-al", stress: 2, note: "" },
    { blockId: 8, no: 365, en: "provide", ja: "提供する", sylRaw: "pro-ˈvide", stress: 2, note: "" },
    { blockId: 8, no: 366, en: "purchase", ja: "購入する", sylRaw: "ˈpur-chase", stress: 1, note: "動詞だが第一音節にアクセントがくる" },
    { blockId: 8, no: 367, en: "qualification", ja: "資格", sylRaw: "qual-i-fi-ˈca-tion", stress: 4, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 368, en: "radar", ja: "レーダー", sylRaw: "ˈra-dar", stress: 1, note: "" },
    { blockId: 8, no: 369, en: "rapid", ja: "急速な", sylRaw: "ˈrap-id", stress: 1, note: "" },
    { blockId: 8, no: 370, en: "rate", ja: "率", sylRaw: "ˈrate", stress: 1, note: "" },
    { blockId: 8, no: 371, en: "ray", ja: "光線", sylRaw: "ˈray", stress: 1, note: "" },
    { blockId: 8, no: 372, en: "reasonable", ja: "合理的な", sylRaw: "ˈrea-son-a-ble", stress: 1, note: "" },
    { blockId: 8, no: 373, en: "receiver", ja: "受信機", sylRaw: "re-ˈceiv-er", stress: 2, note: "" },
    { blockId: 8, no: 374, en: "recipe", ja: "料理法", sylRaw: "ˈre-ci-pe", stress: 1, note: "" },
    { blockId: 8, no: 375, en: "recognition", ja: "認識", sylRaw: "rec-og-ˈni-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 376, en: "recommend", ja: "勧める", sylRaw: "rec-om-ˈmend", stress: 3, note: "" },
    { blockId: 8, no: 377, en: "recreation", ja: "娯楽", sylRaw: "rec-re-ˈa-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 378, en: "reduce", ja: "減らす", sylRaw: "re-ˈduce", stress: 2, note: "" },
    { blockId: 8, no: 379, en: "refer", ja: "言及する", sylRaw: "re-ˈfer", stress: 2, note: "" },
    { blockId: 8, no: 380, en: "reflect", ja: "反映する", sylRaw: "re-ˈflect", stress: 2, note: "" },
    { blockId: 8, no: 381, en: "regret", ja: "後悔する", sylRaw: "re-ˈgret", stress: 2, note: "" },
    { blockId: 8, no: 382, en: "relationship", ja: "関係", sylRaw: "re-ˈla-tion-ship", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 383, en: "reliable", ja: "信頼できる", sylRaw: "re-ˈli-a-ble", stress: 2, note: "" },
    { blockId: 8, no: 384, en: "relieve", ja: "和らげる", sylRaw: "re-ˈlieve", stress: 2, note: "" },
    { blockId: 8, no: 385, en: "religion", ja: "宗教", sylRaw: "re-ˈli-gion", stress: 2, note: "" },
    { blockId: 8, no: 386, en: "religious", ja: "宗教の", sylRaw: "re-ˈli-gious", stress: 2, note: "-ate,-ousは二つ前母音" },
    { blockId: 8, no: 387, en: "rely", ja: "頼る", sylRaw: "re-ˈly", stress: 2, note: "" },
    { blockId: 8, no: 388, en: "replace", ja: "取り替える", sylRaw: "re-ˈplace", stress: 2, note: "" },
    { blockId: 8, no: 389, en: "represent", ja: "代表する", sylRaw: "rep-re-ˈsent", stress: 3, note: "" },
    { blockId: 8, no: 390, en: "representative", ja: "代表者", sylRaw: "rep-re-ˈsen-ta-tive", stress: 3, note: "" },
    { blockId: 8, no: 391, en: "research", ja: "研究", sylRaw: "re-ˈsearch", stress: 2, note: "" },
    { blockId: 8, no: 392, en: "resemble", ja: "似ている", sylRaw: "re-ˈsem-ble", stress: 2, note: "" },
    { blockId: 8, no: 393, en: "reservation", ja: "予約", sylRaw: "res-er-ˈva-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 8, no: 394, en: "responsibility", ja: "責任", sylRaw: "re-spon-si-ˈbil-i-ty", stress: 4, note: "-ityは直前母音" },
    { blockId: 8, no: 395, en: "responsible", ja: "責任がある", sylRaw: "re-ˈspon-si-ble", stress: 2, note: "" },
    { blockId: 8, no: 396, en: "retire", ja: "引退する", sylRaw: "re-ˈtire", stress: 2, note: "" },
    { blockId: 8, no: 397, en: "reward", ja: "報酬", sylRaw: "re-ˈward", stress: 2, note: "" },
    { blockId: 8, no: 398, en: "rid", ja: "取り除く", sylRaw: "ˈrid", stress: 1, note: "" },
    { blockId: 8, no: 399, en: "ripe", ja: "熟した", sylRaw: "ˈripe", stress: 1, note: "" },
    { blockId: 8, no: 400, en: "risk", ja: "危険", sylRaw: "ˈrisk", stress: 1, note: "" },

    { blockId: 9, no: 401, en: "rob", ja: "奪う", sylRaw: "ˈrob", stress: 1, note: "" },
    { blockId: 9, no: 402, en: "robber", ja: "強盗", sylRaw: "ˈrob-ber", stress: 1, note: "" },
    { blockId: 9, no: 403, en: "role", ja: "役割", sylRaw: "ˈrole", stress: 1, note: "" },
    { blockId: 9, no: 404, en: "route", ja: "道筋", sylRaw: "ˈroute", stress: 1, note: "" },
    { blockId: 9, no: 405, en: "rubber", ja: "ゴム", sylRaw: "ˈrub-ber", stress: 1, note: "" },
    { blockId: 9, no: 406, en: "ruin", ja: "台無しにする", sylRaw: "ˈru-in", stress: 1, note: "" },
    { blockId: 9, no: 407, en: "sacrifice", ja: "犠牲", sylRaw: "ˈsac-ri-fice", stress: 1, note: "" },
    { blockId: 9, no: 408, en: "sake", ja: "理由", sylRaw: "ˈsake", stress: 1, note: "" },
    { blockId: 9, no: 409, en: "satisfaction", ja: "満足", sylRaw: "sat-is-ˈfac-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 9, no: 410, en: "satisfactory", ja: "満足な", sylRaw: "sat-is-ˈfac-to-ry", stress: 3, note: "" },
    { blockId: 9, no: 411, en: "scale", ja: "規模", sylRaw: "ˈscale", stress: 1, note: "" },
    { blockId: 9, no: 412, en: "scholar", ja: "学者", sylRaw: "ˈschol-ar", stress: 1, note: "" },
    { blockId: 9, no: 413, en: "scholarship", ja: "奨学金", sylRaw: "ˈschol-ar-ship", stress: 1, note: "" },
    { blockId: 9, no: 414, en: "score", ja: "得点", sylRaw: "ˈscore", stress: 1, note: "" },
    { blockId: 9, no: 415, en: "scream", ja: "叫ぶ", sylRaw: "ˈscream", stress: 1, note: "" },
    { blockId: 9, no: 416, en: "seize", ja: "つかむ", sylRaw: "ˈseize", stress: 1, note: "" },
    { blockId: 9, no: 417, en: "seldom", ja: "めったに～ない", sylRaw: "ˈsel-dom", stress: 1, note: "" },
    { blockId: 9, no: 418, en: "select", ja: "選ぶ", sylRaw: "se-ˈlect", stress: 2, note: "" },
    { blockId: 9, no: 419, en: "sensible", ja: "分別のある", sylRaw: "ˈsen-si-ble", stress: 1, note: "" },
    { blockId: 9, no: 420, en: "sensitive", ja: "敏感な", sylRaw: "ˈsen-si-tive", stress: 1, note: "" },
    { blockId: 9, no: 421, en: "series", ja: "連続", sylRaw: "ˈse-ries", stress: 1, note: "日本語の発音との混同注意" },
    { blockId: 9, no: 422, en: "severe", ja: "厳しい", sylRaw: "se-ˈvere", stress: 2, note: "" },
    { blockId: 9, no: 423, en: "shade", ja: "日陰", sylRaw: "ˈshade", stress: 1, note: "" },
    { blockId: 9, no: 424, en: "shallow", ja: "浅い", sylRaw: "ˈshal-low", stress: 1, note: "" },
    { blockId: 9, no: 425, en: "shame", ja: "恥", sylRaw: "ˈshame", stress: 1, note: "" },
    { blockId: 9, no: 426, en: "shortage", ja: "不足", sylRaw: "ˈshort-age", stress: 1, note: "" },
    { blockId: 9, no: 427, en: "sightseeing", ja: "観光", sylRaw: "ˈsight-see-ing", stress: 1, note: "" },
    { blockId: 9, no: 428, en: "signature", ja: "署名", sylRaw: "ˈsig-na-ture", stress: 1, note: "" },
    { blockId: 9, no: 429, en: "silly", ja: "ばかな", sylRaw: "ˈsil-ly", stress: 1, note: "" },
    { blockId: 9, no: 430, en: "similar", ja: "類似した", sylRaw: "ˈsim-i-lar", stress: 1, note: "" },
    { blockId: 9, no: 431, en: "sincere", ja: "誠実な", sylRaw: "sin-ˈcere", stress: 2, note: "" },
    { blockId: 9, no: 432, en: "situation", ja: "状況", sylRaw: "sit-u-ˈa-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 9, no: 433, en: "skill", ja: "技能", sylRaw: "ˈskill", stress: 1, note: "" },
    { blockId: 9, no: 434, en: "skillful", ja: "熟練した", sylRaw: "ˈskill-ful", stress: 1, note: "" },
    { blockId: 9, no: 435, en: "soil", ja: "土", sylRaw: "ˈsoil", stress: 1, note: "" },
    { blockId: 9, no: 436, en: "solution", ja: "解決策", sylRaw: "so-ˈlu-tion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 9, no: 437, en: "sorrow", ja: "悲しみ", sylRaw: "ˈsor-row", stress: 1, note: "" },
    { blockId: 9, no: 438, en: "source", ja: "源", sylRaw: "ˈsource", stress: 1, note: "" },
    { blockId: 9, no: 439, en: "spite", ja: "悪意", sylRaw: "ˈspite", stress: 1, note: "" },
    { blockId: 9, no: 440, en: "spoil", ja: "台無しにする", sylRaw: "ˈspoil", stress: 1, note: "" },
    { blockId: 9, no: 441, en: "staff", ja: "職員", sylRaw: "ˈstaff", stress: 1, note: "" },
    { blockId: 9, no: 442, en: "stare", ja: "じっと見る", sylRaw: "ˈstare", stress: 1, note: "" },
    { blockId: 9, no: 443, en: "starve", ja: "飢える", sylRaw: "ˈstarve", stress: 1, note: "" },
    { blockId: 9, no: 444, en: "steady", ja: "安定した", sylRaw: "ˈstead-y", stress: 1, note: "" },
    { blockId: 9, no: 445, en: "steep", ja: "急な", sylRaw: "ˈsteep", stress: 1, note: "" },
    { blockId: 9, no: 446, en: "stock", ja: "在庫", sylRaw: "ˈstock", stress: 1, note: "" },
    { blockId: 9, no: 447, en: "stormy", ja: "嵐の", sylRaw: "ˈstorm-y", stress: 1, note: "" },
    { blockId: 9, no: 448, en: "strain", ja: "緊張", sylRaw: "ˈstrain", stress: 1, note: "" },
    { blockId: 9, no: 449, en: "stretch", ja: "伸ばす", sylRaw: "ˈstretch", stress: 1, note: "" },
    { blockId: 9, no: 450, en: "struggle", ja: "奮闘する", sylRaw: "ˈstrug-gle", stress: 1, note: "" },

    { blockId: 10, no: 451, en: "stupid", ja: "愚かな", sylRaw: "ˈstu-pid", stress: 1, note: "" },
    { blockId: 10, no: 452, en: "substitute", ja: "代わり", sylRaw: "ˈsub-sti-tute", stress: 1, note: "" },
    { blockId: 10, no: 453, en: "suggestion", ja: "提案", sylRaw: "sug-ˈges-tion", stress: 2, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 10, no: 454, en: "suitable", ja: "適した", sylRaw: "ˈsuit-a-ble", stress: 1, note: "" },
    { blockId: 10, no: 455, en: "sum", ja: "合計", sylRaw: "ˈsum", stress: 1, note: "" },
    { blockId: 10, no: 456, en: "superior", ja: "優れた", sylRaw: "su-ˈpe-ri-or", stress: 2, note: "" },
    { blockId: 10, no: 457, en: "surround", ja: "囲む", sylRaw: "sur-ˈround", stress: 2, note: "" },
    { blockId: 10, no: 458, en: "survive", ja: "生き残る", sylRaw: "sur-ˈvive", stress: 2, note: "" },
    { blockId: 10, no: 459, en: "suspect", ja: "疑う", sylRaw: "sus-ˈpect", stress: 2, note: "" },
    { blockId: 10, no: 460, en: "swallow", ja: "飲み込む", sylRaw: "ˈswal-low", stress: 1, note: "" },
    { blockId: 10, no: 461, en: "symbol", ja: "象徴", sylRaw: "ˈsym-bol", stress: 1, note: "" },
    { blockId: 10, no: 462, en: "sympathy", ja: "同情", sylRaw: "ˈsym-pa-thy", stress: 1, note: "" },
    { blockId: 10, no: 463, en: "tank", ja: "戦車", sylRaw: "ˈtank", stress: 1, note: "" },
    { blockId: 10, no: 464, en: "task", ja: "任務", sylRaw: "ˈtask", stress: 1, note: "" },
    { blockId: 10, no: 465, en: "technical", ja: "技術的な", sylRaw: "ˈtech-ni-cal", stress: 1, note: "" },
    { blockId: 10, no: 466, en: "technique", ja: "技術", sylRaw: "tech-ˈnique", stress: 2, note: "日本語の発音との混同注意" },
    { blockId: 10, no: 467, en: "technology", ja: "技術", sylRaw: "tech-ˈnol-o-gy", stress: 2, note: "" },
    { blockId: 10, no: 468, en: "telescope", ja: "望遠鏡", sylRaw: "ˈtel-e-scope", stress: 1, note: "" },
    { blockId: 10, no: 469, en: "temple", ja: "寺", sylRaw: "ˈtem-ple", stress: 1, note: "" },
    { blockId: 10, no: 470, en: "tend", ja: "～する傾向がある", sylRaw: "ˈtend", stress: 1, note: "" },
    { blockId: 10, no: 471, en: "theory", ja: "理論", sylRaw: "ˈthe-o-ry", stress: 1, note: "" },
    { blockId: 10, no: 472, en: "thermometer", ja: "温度計", sylRaw: "ther-ˈmom-e-ter", stress: 2, note: "" },
    { blockId: 10, no: 473, en: "throughout", ja: "～の間ずっと", sylRaw: "through-ˈout", stress: 2, note: "" },
    { blockId: 10, no: 474, en: "thus", ja: "それゆえ", sylRaw: "ˈthus", stress: 1, note: "" },
    { blockId: 10, no: 475, en: "tidy", ja: "きちんとした", sylRaw: "ˈtidy", stress: 1, note: "" },
    { blockId: 10, no: 476, en: "transfer", ja: "移す", sylRaw: "trans-ˈfer", stress: 2, note: "" },
    { blockId: 10, no: 477, en: "transportation", ja: "交通", sylRaw: "trans-por-ˈta-tion", stress: 3, note: "-cian, -tion, -sionは直前母音" },
    { blockId: 10, no: 478, en: "treasure", ja: "宝", sylRaw: "ˈtrea-sure", stress: 1, note: "" },
    { blockId: 10, no: 479, en: "tube", ja: "管", sylRaw: "ˈtube", stress: 1, note: "" },
    { blockId: 10, no: 480, en: "typical", ja: "典型的な", sylRaw: "ˈtyp-i-cal", stress: 1, note: "-icalは直前母音" },
    { blockId: 10, no: 481, en: "ugly", ja: "醜い", sylRaw: "ˈug-ly", stress: 1, note: "" },
    { blockId: 10, no: 482, en: "uneasy", ja: "不安な", sylRaw: "un-ˈeasy", stress: 2, note: "" },
    { blockId: 10, no: 483, en: "unfortunate", ja: "不運な", sylRaw: "un-ˈfor-tu-nate", stress: 2, note: "-ate,-ousは二つ前母音" },
    { blockId: 10, no: 484, en: "universal", ja: "普遍的な", sylRaw: "u-ni-ˈver-sal", stress: 3, note: "" },
    { blockId: 10, no: 485, en: "universe", ja: "宇宙", sylRaw: "ˈu-ni-verse", stress: 1, note: "" },
    { blockId: 10, no: 486, en: "urge", ja: "強く促す", sylRaw: "ˈurge", stress: 1, note: "" },
    { blockId: 10, no: 487, en: "urgent", ja: "緊急の", sylRaw: "ˈur-gent", stress: 1, note: "" },
    { blockId: 10, no: 488, en: "variety", ja: "多様性", sylRaw: "va-ˈri-ety", stress: 2, note: "" },
    { blockId: 10, no: 489, en: "victory", ja: "勝利", sylRaw: "ˈvic-to-ry", stress: 1, note: "" },
    { blockId: 10, no: 490, en: "virus", ja: "ウイルス", sylRaw: "ˈvi-rus", stress: 1, note: "" },
    { blockId: 10, no: 491, en: "vote", ja: "投票", sylRaw: "ˈvote", stress: 1, note: "" },
    { blockId: 10, no: 492, en: "voyage", ja: "航海", sylRaw: "ˈvoy-age", stress: 1, note: "" },
    { blockId: 10, no: 493, en: "wage", ja: "賃金", sylRaw: "ˈwage", stress: 1, note: "" },
    { blockId: 10, no: 494, en: "wander", ja: "さまよう", sylRaw: "ˈwan-der", stress: 1, note: "" },
    { blockId: 10, no: 495, en: "weave", ja: "織る", sylRaw: "ˈweave", stress: 1, note: "" },
    { blockId: 10, no: 496, en: "welfare", ja: "福祉", sylRaw: "ˈwel-fare", stress: 1, note: "" },
    { blockId: 10, no: 497, en: "wheel", ja: "車輪", sylRaw: "ˈwheel", stress: 1, note: "" },
    { blockId: 10, no: 498, en: "wisdom", ja: "知恵", sylRaw: "ˈwis-dom", stress: 1, note: "" },
    { blockId: 10, no: 499, en: "worm", ja: "虫", sylRaw: "ˈworm", stress: 1, note: "" },
    { blockId: 10, no: 500, en: "worthy", ja: "値する", sylRaw: "ˈwor-thy", stress: 1, note: "" },

  ];
})();
