// idiom_master_1kyu.js
// 全商英検1級 イディオム・定型表現マスターデータ
// 100本の paraphrase note をもとに、まずはイディオム問題用の辞書データとして整えた版
// まだ現在の idiom_quiz.html / idiom_quiz.js には直結しなくてOK
// 今後、このファイルをもとに
// - idiom_data_1kyu.js
// - paraphrase_data_1kyu.js
// を作る土台にする

window.IDIOM_MASTER_1KYU = [
  { id: "IM001", expression: "take part in", ja: "～に参加する", noteId: "N001", paraphraseTo: ["participate in"], rank: "A", type: "熟語→1語" },
  { id: "IM002", expression: "put off", ja: "～を延期する", noteId: "N002", paraphraseTo: ["postpone"], rank: "A", type: "熟語→1語" },
  { id: "IM003", expression: "be made up of", ja: "～から成り立っている", noteId: "N003", paraphraseTo: ["consist of"], rank: "A", type: "構成表現" },
  { id: "IM004", expression: "deal with", ja: "～に対処する", noteId: "N004", paraphraseTo: ["handle"], rank: "A", type: "熟語→1語" },
  { id: "IM005", expression: "be in charge of", ja: "～を担当している", noteId: "N005", paraphraseTo: ["be responsible for"], rank: "A", type: "句⇄形容詞句" },
  { id: "IM006", expression: "be absent from", ja: "～を欠席する", noteId: "N006", paraphraseTo: ["miss"], rank: "A", type: "句→1語" },
  { id: "IM007", expression: "come across", ja: "偶然出会う", noteId: "N007", paraphraseTo: ["happen to meet"], rank: "A", type: "句動詞→言い換え" },
  { id: "IM008", expression: "look into", ja: "～を調査する", noteId: "N008", paraphraseTo: ["investigate"], rank: "A", type: "熟語→1語" },
  { id: "IM009", expression: "get over", ja: "～を克服する", noteId: "N009", paraphraseTo: ["recover from"], rank: "A", type: "句動詞→言い換え" },
  { id: "IM010", expression: "be against", ja: "～に反対している", noteId: "N010", paraphraseTo: ["disagree with"], rank: "A", type: "句⇄動詞句" },

  { id: "IM011", expression: "rely on", ja: "～に頼る", noteId: "N011", paraphraseTo: ["depend on"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM012", expression: "be independent of", ja: "～に頼らない", noteId: "N012", paraphraseTo: ["not depend on"], rank: "A", type: "反対構文型言い換え" },
  { id: "IM013", expression: "lead to", ja: "～を引き起こす", noteId: "N013", paraphraseTo: ["cause"], rank: "A", type: "因果表現" },
  { id: "IM014", expression: "due to", ja: "～が原因で", noteId: "N014", paraphraseTo: ["because of"], rank: "A", type: "原因表現" },
  { id: "IM015", expression: "call off", ja: "～を中止する", noteId: "N015", paraphraseTo: ["cancel"], rank: "A", type: "句動詞→1語" },
  { id: "IM016", expression: "turn down", ja: "～を断る", noteId: "N016", paraphraseTo: ["reject"], rank: "A", type: "句動詞→1語" },
  { id: "IM017", expression: "cut down on", ja: "～を減らす", noteId: "N017", paraphraseTo: ["reduce"], rank: "A", type: "句動詞→1語" },
  { id: "IM018", expression: "carry out", ja: "～を実行する", noteId: "N018", paraphraseTo: ["implement"], rank: "A", type: "熟語→1語" },
  { id: "IM019", expression: "have an effect on", ja: "～に影響を与える", noteId: "N019", paraphraseTo: ["affect"], rank: "A-", type: "名詞化⇄動詞化" },
  { id: "IM020", expression: "pass away", ja: "亡くなる", noteId: "N020", paraphraseTo: ["die"], rank: "A", type: "婉曲表現→1語" },

  { id: "IM021", expression: "go through", ja: "～を経験する", noteId: "N021", paraphraseTo: ["experience"], rank: "A", type: "熟語→1語" },
  { id: "IM022", expression: "have confidence in", ja: "～を信頼している", noteId: "N022", paraphraseTo: ["trust"], rank: "A", type: "名詞句→1語" },
  { id: "IM023", expression: "be in favor of", ja: "～に賛成している", noteId: "N023", paraphraseTo: ["support","agree with"], rank: "A", type: "句→1語" },
  { id: "IM024", expression: "account for", ja: "～を説明する", noteId: "N024", paraphraseTo: ["explain"], rank: "A", type: "熟語→1語" },
  { id: "IM025", expression: "look up to", ja: "～を尊敬する", noteId: "N025", paraphraseTo: ["respect"], rank: "A", type: "句動詞→1語" },
  { id: "IM026", expression: "take care of", ja: "～の世話をする", noteId: "N026", paraphraseTo: ["look after"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM027", expression: "run out of", ja: "～を使い果たす", noteId: "N027", paraphraseTo: ["use up"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM028", expression: "be short of", ja: "～が不足している", noteId: "N028", paraphraseTo: ["lack"], rank: "A", type: "句→1語" },
  { id: "IM029", expression: "in spite of", ja: "～にもかかわらず", noteId: "N029", paraphraseTo: ["despite"], rank: "A", type: "接続・前置詞表現" },
  { id: "IM030", expression: "no longer", ja: "もはや～ない", noteId: "N030", paraphraseTo: ["not ... anymore"], rank: "A", type: "否定言い換え" },

  { id: "IM031", expression: "all of a sudden", ja: "突然", noteId: "N031", paraphraseTo: ["suddenly"], rank: "A", type: "副詞化" },
  { id: "IM032", expression: "from time to time", ja: "時々", noteId: "N032", paraphraseTo: ["occasionally"], rank: "A", type: "副詞化" },
  { id: "IM033", expression: "by accident", ja: "偶然に", noteId: "N033", paraphraseTo: ["accidentally"], rank: "A", type: "副詞化" },
  { id: "IM034", expression: "on purpose", ja: "わざと", noteId: "N034", paraphraseTo: ["intentionally"], rank: "A", type: "副詞化" },
  { id: "IM035", expression: "in the end", ja: "結局", noteId: "N035", paraphraseTo: ["finally"], rank: "A", type: "副詞化" },
  { id: "IM036", expression: "instead of", ja: "～の代わりに", noteId: "N036", paraphraseTo: ["rather than"], rank: "A", type: "接続表現" },
  { id: "IM037", expression: "in addition to", ja: "～に加えて", noteId: "N037", paraphraseTo: ["besides"], rank: "A-", type: "追加表現" },
  { id: "IM038", expression: "be likely to", ja: "～しそうだ", noteId: "N038", paraphraseTo: ["probably"], rank: "A-", type: "構文→副詞" },
  { id: "IM039", expression: "be supposed to", ja: "～することになっている", noteId: "N039", paraphraseTo: ["should"], rank: "A", type: "構文→助動詞" },
  { id: "IM040", expression: "cannot help Ving", ja: "～せずにはいられない", noteId: "N040", paraphraseTo: ["cannot avoid Ving"], rank: "A", type: "構文言い換え" },

  { id: "IM041", expression: "be eager to", ja: "～したがっている", noteId: "N041", paraphraseTo: ["be keen to"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM042", expression: "get along with", ja: "～とうまくやる", noteId: "N042", paraphraseTo: ["have a good relationship with"], rank: "A", type: "熟語→説明型" },
  { id: "IM043", expression: "keep in touch with", ja: "～と連絡を取り合う", noteId: "N043", paraphraseTo: ["stay in contact with"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM044", expression: "take over", ja: "引き継ぐ", noteId: "N044", paraphraseTo: ["assume control of"], rank: "A", type: "句動詞→説明型" },
  { id: "IM045", expression: "make sense", ja: "筋が通る", noteId: "N045", paraphraseTo: ["be understandable"], rank: "A", type: "熟語→形容詞化" },
  { id: "IM046", expression: "be different from", ja: "～と異なる", noteId: "N046", paraphraseTo: ["differ from"], rank: "A", type: "句⇄動詞" },
  { id: "IM047", expression: "there is no use Ving", ja: "～しても無駄だ", noteId: "N047", paraphraseTo: ["it is useless to do"], rank: "A", type: "構文言い換え" },
  { id: "IM048", expression: "there is no knowing", ja: "～はわからない", noteId: "N048", paraphraseTo: ["it is impossible to know"], rank: "A", type: "構文言い換え" },
  { id: "IM049", expression: "be worth Ving", ja: "～する価値がある", noteId: "N049", paraphraseTo: ["it is worthwhile to do"], rank: "A", type: "構文言い換え" },
  { id: "IM050", expression: "take A for granted", ja: "Aを当然のことと思う", noteId: "N050", paraphraseTo: ["fail to appreciate A"], rank: "A", type: "熟語→説明型" },

  { id: "IM051", expression: "put up with", ja: "～を我慢する", noteId: "N051", paraphraseTo: ["tolerate"], rank: "A", type: "句動詞→1語" },
  { id: "IM052", expression: "get rid of", ja: "～を取り除く", noteId: "N052", paraphraseTo: ["remove"], rank: "A", type: "熟語→1語" },
  { id: "IM053", expression: "get in touch with", ja: "～に連絡を取る", noteId: "N053", paraphraseTo: ["contact"], rank: "A", type: "熟語→1語" },
  { id: "IM054", expression: "make up one's mind", ja: "決心する", noteId: "N054", paraphraseTo: ["decide"], rank: "A", type: "熟語→1語" },
  { id: "IM055", expression: "break out", ja: "突然起こる", noteId: "N055", paraphraseTo: ["start suddenly"], rank: "A", type: "句動詞→説明型" },
  { id: "IM056", expression: "bring about", ja: "～を引き起こす", noteId: "N056", paraphraseTo: ["cause"], rank: "A", type: "熟語→1語" },
  { id: "IM057", expression: "result from", ja: "～から生じる", noteId: "N057", paraphraseTo: ["be caused by"], rank: "A", type: "因果表現" },
  { id: "IM058", expression: "be concerned about", ja: "～を心配している", noteId: "N058", paraphraseTo: ["worry about"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM059", expression: "be satisfied with", ja: "～に満足している", noteId: "N059", paraphraseTo: ["be content with"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM060", expression: "make fun of", ja: "～をからかう", noteId: "N060", paraphraseTo: ["laugh at"], rank: "A", type: "熟語⇄熟語" },

  { id: "IM061", expression: "keep A from Ving", ja: "Aが～するのを妨げる", noteId: "N061", paraphraseTo: ["prevent A from doing"], rank: "A", type: "構文言い換え" },
  { id: "IM062", expression: "be known for", ja: "～で知られている", noteId: "N062", paraphraseTo: ["be famous for"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM063", expression: "be familiar with", ja: "～をよく知っている", noteId: "N063", paraphraseTo: ["know well"], rank: "A", type: "形容詞句→説明型" },
  { id: "IM064", expression: "in search of", ja: "～を探して", noteId: "N064", paraphraseTo: ["looking for"], rank: "A", type: "前置詞句⇄熟語" },
  { id: "IM065", expression: "make progress in", ja: "～で進歩する", noteId: "N065", paraphraseTo: ["improve"], rank: "A-", type: "名詞化⇄動詞化" },
  { id: "IM066", expression: "stand for", ja: "～を表す", noteId: "N066", paraphraseTo: ["represent"], rank: "A", type: "熟語→1語" },
  { id: "IM067", expression: "take after", ja: "～に似ている", noteId: "N067", paraphraseTo: ["resemble"], rank: "A", type: "句動詞→1語" },
  { id: "IM068", expression: "be accustomed to", ja: "～に慣れている", noteId: "N068", paraphraseTo: ["be used to"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM069", expression: "have difficulty in doing", ja: "～するのが難しい", noteId: "N069", paraphraseTo: ["find it hard to do"], rank: "A", type: "構文言い換え" },
  { id: "IM070", expression: "make room for", ja: "～のための場所を空ける", noteId: "N070", paraphraseTo: ["allow space for"], rank: "A", type: "熟語→説明型" },

  { id: "IM071", expression: "contribute to", ja: "～の一因となる", noteId: "N071", paraphraseTo: ["help cause"], rank: "A", type: "熟語→説明型" },
  { id: "IM072", expression: "get in the way of", ja: "～の妨げになる", noteId: "N072", paraphraseTo: ["obstruct"], rank: "A", type: "熟語→1語" },
  { id: "IM073", expression: "in other words", ja: "言い換えれば", noteId: "N073", paraphraseTo: ["that is to say"], rank: "A", type: "定型表現" },
  { id: "IM074", expression: "for instance", ja: "例えば", noteId: "N074", paraphraseTo: ["for example"], rank: "A", type: "定型表現" },
  { id: "IM075", expression: "on behalf of", ja: "～に代わって", noteId: "N075", paraphraseTo: ["for"], rank: "A-", type: "前置詞表現" },
  { id: "IM076", expression: "in return for", ja: "～のお返しに", noteId: "N076", paraphraseTo: ["in exchange for"], rank: "A", type: "前置詞表現" },
  { id: "IM077", expression: "with regard to", ja: "～に関して", noteId: "N077", paraphraseTo: ["about"], rank: "A-", type: "前置詞表現" },
  { id: "IM078", expression: "be related to", ja: "～に関連している", noteId: "N078", paraphraseTo: ["be connected with"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM079", expression: "in terms of", ja: "～の観点で", noteId: "N079", paraphraseTo: ["with respect to"], rank: "A", type: "前置詞表現" },
  { id: "IM080", expression: "have a tendency to", ja: "～する傾向がある", noteId: "N080", paraphraseTo: ["tend to"], rank: "A", type: "構文言い換え" },

  { id: "IM081", expression: "do away with", ja: "～を廃止する", noteId: "N081", paraphraseTo: ["abolish"], rank: "A", type: "熟語→1語" },
  { id: "IM082", expression: "make up for", ja: "～を埋め合わせる", noteId: "N082", paraphraseTo: ["compensate for"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM083", expression: "have no choice but to", ja: "～するしかない", noteId: "N083", paraphraseTo: ["be forced to"], rank: "A", type: "構文言い換え" },
  { id: "IM084", expression: "be superior to", ja: "～より優れている", noteId: "N084", paraphraseTo: ["be better than"], rank: "A", type: "比較表現" },
  { id: "IM085", expression: "be inferior to", ja: "～より劣っている", noteId: "N085", paraphraseTo: ["be worse than"], rank: "A", type: "比較表現" },
  { id: "IM086", expression: "take place", ja: "起こる", noteId: "N086", paraphraseTo: ["happen"], rank: "A", type: "熟語→1語" },
  { id: "IM087", expression: "set up", ja: "～を設立する", noteId: "N087", paraphraseTo: ["establish"], rank: "A", type: "句動詞→1語" },
  { id: "IM088", expression: "look down on", ja: "～を見下す", noteId: "N088", paraphraseTo: ["despise"], rank: "A", type: "句動詞→1語" },
  { id: "IM089", expression: "consent to", ja: "～に同意する", noteId: "N089", paraphraseTo: ["agree to"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM090", expression: "turn to A for help", ja: "Aに助けを求める", noteId: "N090", paraphraseTo: ["ask A for help"], rank: "A", type: "熟語→説明型" },

  { id: "IM091", expression: "be on the point of Ving", ja: "まさに～しようとしている", noteId: "N091", paraphraseTo: ["be about to do"], rank: "A", type: "構文言い換え" },
  { id: "IM092", expression: "in advance", ja: "前もって", noteId: "N092", paraphraseTo: ["beforehand"], rank: "A", type: "副詞化" },
  { id: "IM093", expression: "for the time being", ja: "当分の間", noteId: "N093", paraphraseTo: ["for now"], rank: "A", type: "定型表現" },
  { id: "IM094", expression: "at present", ja: "現在は", noteId: "N094", paraphraseTo: ["currently"], rank: "A", type: "副詞化" },
  { id: "IM095", expression: "with ease", ja: "容易に", noteId: "N095", paraphraseTo: ["easily"], rank: "A", type: "副詞化" },
  { id: "IM096", expression: "in vain", ja: "むだに", noteId: "N096", paraphraseTo: ["without success"], rank: "A", type: "定型表現" },
  { id: "IM097", expression: "regardless of", ja: "～に関係なく", noteId: "N097", paraphraseTo: ["despite"], rank: "A", type: "前置詞表現" },
  { id: "IM098", expression: "far from", ja: "決して～ない", noteId: "N098", paraphraseTo: ["not at all"], rank: "A-", type: "否定強調表現" },
  { id: "IM099", expression: "out of order", ja: "故障している", noteId: "N099", paraphraseTo: ["not working"], rank: "A", type: "状態表現" },
  { id: "IM100", expression: "keep up with", ja: "～に遅れずについていく", noteId: "N100", paraphraseTo: ["stay at the same level as"], rank: "A", type: "熟語→説明型" },
    { id: "IM101", expression: "come up with", ja: "～を思いつく", noteId: "N101", paraphraseTo: ["think of", "think up"], rank: "A", type: "句動詞→説明型" },
  { id: "IM102", expression: "leave out", ja: "～を省く", noteId: "N102", paraphraseTo: ["omit", "skip"], rank: "A", type: "句動詞→1語" },
  { id: "IM103", expression: "make sense of", ja: "～を理解する", noteId: "N103", paraphraseTo: ["understand", "figure out"], rank: "A", type: "熟語→1語" },
  { id: "IM104", expression: "refrain from", ja: "～を控える", noteId: "N104", paraphraseTo: ["avoid", "keep from"], rank: "A", type: "熟語→1語" },
  { id: "IM105", expression: "cope with", ja: "～に対処する", noteId: "N105", paraphraseTo: ["deal with", "handle"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM106", expression: "be bound to", ja: "きっと～する", noteId: "N106", paraphraseTo: ["be certain to", "be sure to"], rank: "A", type: "構文言い換え" },
  { id: "IM107", expression: "be entitled to", ja: "～する権利がある", noteId: "N107", paraphraseTo: ["have the right to"], rank: "A", type: "形容詞句→説明型" },
  { id: "IM108", expression: "on the verge of", ja: "まさに～しそうで", noteId: "N108", paraphraseTo: ["close to", "almost"], rank: "A", type: "前置詞句言い換え" },
  { id: "IM109", expression: "in the course of", ja: "～の間に", noteId: "N109", paraphraseTo: ["during"], rank: "A", type: "前置詞表現" },
  { id: "IM110", expression: "at the expense of", ja: "～を犠牲にして", noteId: "N110", paraphraseTo: ["by sacrificing", "while sacrificing"], rank: "A", type: "前置詞句→説明型" },

  { id: "IM111", expression: "make ends meet", ja: "どうにかやりくりする", noteId: "N111", paraphraseTo: ["earn just enough to live", "have enough money to live"], rank: "A", type: "熟語→説明型" },
  { id: "IM112", expression: "keep track of", ja: "～の動向を追う", noteId: "N112", paraphraseTo: ["follow", "stay informed about"], rank: "A-", type: "熟語→説明型" },
  { id: "IM113", expression: "speak ill of", ja: "～の悪口を言う", noteId: "N113", paraphraseTo: ["criticize", "say bad things about"], rank: "A", type: "熟語→1語" },
  { id: "IM114", expression: "take A into consideration", ja: "Aを考慮に入れる", noteId: "N114", paraphraseTo: ["consider A", "take A into account"], rank: "A", type: "熟語→1語" },
  { id: "IM115", expression: "put pressure on", ja: "～に圧力をかける", noteId: "N115", paraphraseTo: ["urge", "force"], rank: "A", type: "熟語→1語" },
  { id: "IM116", expression: "be obliged to", ja: "～せざるを得ない", noteId: "N116", paraphraseTo: ["be forced to", "have to"], rank: "A", type: "構文言い換え" },
  { id: "IM117", expression: "turn out to be", ja: "～であることがわかる", noteId: "N117", paraphraseTo: ["prove to be", "be found to be"], rank: "A", type: "構文言い換え" },
  { id: "IM118", expression: "provide A with B", ja: "AにBを供給する", noteId: "N118", paraphraseTo: ["supply A with B", "give A B"], rank: "A", type: "構文言い換え" },
  { id: "IM119", expression: "for lack of", ja: "～が不足しているために", noteId: "N119", paraphraseTo: ["because there is not enough of", "due to not having enough"], rank: "A", type: "原因表現" },
  { id: "IM120", expression: "sooner or later", ja: "遅かれ早かれ", noteId: "N120", paraphraseTo: ["eventually", "in time"], rank: "A", type: "副詞化" },

  { id: "IM121", expression: "look forward to", ja: "～を楽しみに待つ", noteId: "N121", paraphraseTo: ["await", "expect eagerly"], rank: "A", type: "熟語→1語" },
  { id: "IM122", expression: "show up", ja: "現れる", noteId: "N122", paraphraseTo: ["appear", "arrive"], rank: "A", type: "句動詞→1語" },
  { id: "IM123", expression: "carry on", ja: "続ける", noteId: "N123", paraphraseTo: ["continue", "go on"], rank: "A", type: "句動詞→1語" },
  { id: "IM124", expression: "drop in on", ja: "～をふらっと訪ねる", noteId: "N124", paraphraseTo: ["visit casually", "stop by"], rank: "A", type: "句動詞→説明型" },
  { id: "IM125", expression: "make believe", ja: "ふりをする", noteId: "N125", paraphraseTo: ["pretend", "act as if"], rank: "A", type: "熟語→1語" },
  { id: "IM126", expression: "bring up", ja: "～を育てる", noteId: "N126", paraphraseTo: ["raise"], rank: "A", type: "句動詞→1語" },
  { id: "IM127", expression: "put aside", ja: "～を取っておく", noteId: "N127", paraphraseTo: ["save", "keep for later"], rank: "A", type: "句動詞→1語" },
  { id: "IM128", expression: "take advantage of", ja: "～を利用する", noteId: "N128", paraphraseTo: ["make use of", "exploit"], rank: "A", type: "熟語→1語" },
  { id: "IM129", expression: "make a point of doing", ja: "必ず～するようにする", noteId: "N129", paraphraseTo: ["be sure to do", "always do intentionally"], rank: "A", type: "構文言い換え" },
  { id: "IM130", expression: "do one's best", ja: "最善を尽くす", noteId: "N130", paraphraseTo: ["try as hard as one can", "make every effort"], rank: "A", type: "熟語→説明型" },

  { id: "IM131", expression: "attach importance to", ja: "～を重視する", noteId: "N131", paraphraseTo: ["value", "think much of"], rank: "A", type: "熟語→1語" },
  { id: "IM132", expression: "put emphasis on", ja: "～を強調する", noteId: "N132", paraphraseTo: ["emphasize", "stress"], rank: "A", type: "熟語→1語" },
  { id: "IM133", expression: "be reluctant to", ja: "気が進まない", noteId: "N133", paraphraseTo: ["hesitate to", "be unwilling to"], rank: "A", type: "形容詞句言い換え" },
  { id: "IM134", expression: "have yet to do", ja: "まだ～していない", noteId: "N134", paraphraseTo: ["have not done ... yet", "still have to do"], rank: "A", type: "構文言い換え" },
  { id: "IM135", expression: "let alone", ja: "まして～ない", noteId: "N135", paraphraseTo: ["much less", "not to mention"], rank: "A", type: "定型表現" },
  { id: "IM136", expression: "in no time", ja: "すぐに", noteId: "N136", paraphraseTo: ["very soon", "soon"], rank: "A", type: "副詞化" },
  { id: "IM137", expression: "in the meantime", ja: "その間に", noteId: "N137", paraphraseTo: ["meanwhile", "during that time"], rank: "A", type: "副詞化" },
  { id: "IM138", expression: "owing to", ja: "～のために", noteId: "N138", paraphraseTo: ["because of", "due to"], rank: "A", type: "原因表現" },
  { id: "IM139", expression: "by means of", ja: "～によって", noteId: "N139", paraphraseTo: ["by using", "through"], rank: "A", type: "前置詞句→説明型" },
  { id: "IM140", expression: "under no circumstances", ja: "決して～ない", noteId: "N140", paraphraseTo: ["never", "not in any case"], rank: "A", type: "否定強調表現" },

  { id: "IM141", expression: "comply with", ja: "～に従う", noteId: "N141", paraphraseTo: ["obey", "follow"], rank: "A", type: "熟語→1語" },
  { id: "IM142", expression: "be under the impression that", ja: "～だと思っている", noteId: "N142", paraphraseTo: ["believe that", "think that"], rank: "A", type: "構文言い換え" },
  { id: "IM143", expression: "make a living", ja: "生計を立てる", noteId: "N143", paraphraseTo: ["earn money to live", "support oneself"], rank: "A", type: "熟語→説明型" },
  { id: "IM144", expression: "be on duty", ja: "勤務中である", noteId: "N144", paraphraseTo: ["be working", "be at work"], rank: "A", type: "状態表現" },
  { id: "IM145", expression: "in case of", ja: "～の場合に", noteId: "N145", paraphraseTo: ["if there is", "when there is"], rank: "A-", type: "前置詞句→説明型" },
  { id: "IM146", expression: "in honor of", ja: "～に敬意を表して", noteId: "N146", paraphraseTo: ["to show respect for", "to celebrate"], rank: "A", type: "前置詞句→説明型" },
  { id: "IM147", expression: "have a good reputation", ja: "評判がよい", noteId: "N147", paraphraseTo: ["be well thought of", "be respected"], rank: "A", type: "名詞句→説明型" },
  { id: "IM148", expression: "aside from", ja: "～は別として", noteId: "N148", paraphraseTo: ["except for", "apart from"], rank: "A", type: "前置詞表現" },
  { id: "IM149", expression: "consist in", ja: "～にある", noteId: "N149", paraphraseTo: ["lie in", "depend on"], rank: "A", type: "熟語⇄熟語" },
  { id: "IM150", expression: "derive from", ja: "～に由来する", noteId: "N150", paraphraseTo: ["come from", "originate from"], rank: "A", type: "熟語⇄熟語" }
];
