// idiom_data_1kyu.js
// 全商英検1級 イディオムクイズ用データ（150件版）
// 今の idiom_quiz.js でそのまま使える形
// expression / ja がクイズ本体で使用される主項目
// それ以外は将来の言い換え問題連携用に保持

(function () {
  const RAW = [
    ["IM001", "take part in", "～に参加する", "N001", ["participate in"], "A", "熟語→1語"],
    ["IM002", "put off", "～を延期する", "N002", ["postpone"], "A", "熟語→1語"],
    ["IM003", "be made up of", "～から成り立っている", "N003", ["consist of"], "A", "構成表現"],
    ["IM004", "deal with", "～に対処する", "N004", ["handle"], "A", "熟語→1語"],
    ["IM005", "be in charge of", "～を担当している", "N005", ["be responsible for"], "A", "句⇄形容詞句"],
    ["IM006", "be absent from", "～を欠席する", "N006", ["miss"], "A", "句→1語"],
    ["IM007", "come across", "偶然出会う", "N007", ["happen to meet", "run into", "meet by chance"], "A", "句動詞→言い換え"],
    ["IM008", "look into", "～を調査する", "N008", ["investigate"], "A", "熟語→1語"],
    ["IM009", "get over", "～を克服する", "N009", ["recover from"], "A", "句動詞→言い換え"],
    ["IM010", "be against", "～に反対している", "N010", ["disagree with"], "A", "句⇄動詞句"],

    ["IM011", "rely on", "～に頼る", "N011", ["depend on"], "A", "熟語⇄熟語"],
    ["IM012", "be independent of", "～に頼らない", "N012", ["not depend on"], "A", "反対構文型言い換え"],
    ["IM013", "lead to", "～を引き起こす", "N013", ["cause"], "A", "因果表現"],
    ["IM014", "due to", "～が原因で", "N014", ["because of"], "A", "原因表現"],
    ["IM015", "call off", "～を中止する", "N015", ["cancel"], "A", "句動詞→1語"],
    ["IM016", "turn down", "～を断る", "N016", ["reject"], "A", "句動詞→1語"],
    ["IM017", "cut down on", "～を減らす", "N017", ["reduce"], "A", "句動詞→1語"],
    ["IM018", "carry out", "～を実行する", "N018", ["implement"], "A", "熟語→1語"],
    ["IM019", "have an effect on", "～に影響を与える", "N019", ["affect"], "A-", "名詞化⇄動詞化"],
    ["IM020", "pass away", "亡くなる", "N020", ["die"], "A", "婉曲表現→1語"],

    ["IM021", "go through", "～を経験する", "N021", ["experience"], "A", "熟語→1語"],
    ["IM022", "have confidence in", "～を信頼している", "N022", ["trust"], "A", "名詞句→1語"],
    ["IM023", "be in favor of", "～に賛成している", "N023", ["support","agree with"], "A", "句→1語"],
    ["IM024", "account for", "～を説明する", "N024", ["explain"], "A", "熟語→1語"],
    ["IM025", "look up to", "～を尊敬する", "N025", ["respect"], "A", "句動詞→1語"],
    ["IM026", "take care of", "～の世話をする", "N026", ["look after"], "A", "熟語⇄熟語"],
    ["IM027", "run out of", "～を使い果たす", "N027", ["use up"], "A", "熟語⇄熟語"],
    ["IM028", "be short of", "～が不足している", "N028", ["lack"], "A", "句→1語"],
    ["IM029", "in spite of", "～にもかかわらず", "N029", ["despite"], "A", "接続・前置詞表現"],
    ["IM030", "no longer", "もはや～ない", "N030", ["not ... anymore"], "A", "否定言い換え"],

    ["IM031", "all of a sudden", "突然", "N031", ["suddenly"], "A", "副詞化"],
    ["IM032", "from time to time", "時々", "N032", ["occasionally"], "A", "副詞化"],
    ["IM033", "by accident", "偶然に", "N033", ["accidentally"], "A", "副詞化"],
    ["IM034", "on purpose", "わざと", "N034", ["intentionally"], "A", "副詞化"],
    ["IM035", "in the end", "結局", "N035", ["finally"], "A", "副詞化"],
    ["IM036", "instead of", "～の代わりに", "N036", ["rather than"], "A", "接続表現"],
    ["IM037", "in addition to", "～に加えて", "N037", ["besides"], "A-", "追加表現"],
    ["IM038", "be likely to", "～しそうだ", "N038", ["probably"], "A-", "構文→副詞"],
    ["IM039", "be supposed to", "～することになっている", "N039", ["should"], "A", "構文→助動詞"],
    ["IM040", "cannot help doing", "～せずにはいられない", "N040", ["cannot avoid doing"], "A", "構文言い換え"],

    ["IM041", "be eager to", "～したがっている", "N041", ["be keen to"], "A", "形容詞句言い換え"],
    ["IM042", "get along with", "～とうまくやる", "N042", ["have a good relationship with"], "A", "熟語→説明型"],
    ["IM043", "keep in touch with", "～と連絡を取り合う", "N043", ["stay in contact with"], "A", "熟語⇄熟語"],
    ["IM044", "take over", "引き継ぐ", "N044", ["assume control of"], "A", "句動詞→説明型"],
    ["IM045", "make sense", "筋が通る", "N045", ["be understandable"], "A", "熟語→形容詞化"],
    ["IM046", "be different from", "～と異なる", "N046", ["differ from"], "A", "句⇄動詞"],
    ["IM047", "there is no use doing", "～しても無駄だ", "N047", ["it is useless to do"], "A", "構文言い換え"],
    ["IM048", "there is no knowing", "～はわからない", "N048", ["it is impossible to know"], "A", "構文言い換え"],
    ["IM049", "be worth doing", "～する価値がある", "N049", ["it is worthwhile to do"], "A", "構文言い換え"],
    ["IM050", "take A for granted", "Aを当然のことと思う", "N050", ["fail to appreciate A"], "A", "熟語→説明型"],

    ["IM051", "put up with", "～を我慢する", "N051", ["tolerate"], "A", "句動詞→1語"],
    ["IM052", "get rid of", "～を取り除く", "N052", ["remove"], "A", "熟語→1語"],
    ["IM053", "get in touch with", "～に連絡を取る", "N053", ["contact"], "A", "熟語→1語"],
    ["IM054", "make up one's mind", "決心する", "N054", ["decide"], "A", "熟語→1語"],
    ["IM055", "break out", "突然起こる", "N055", ["start suddenly"], "A", "句動詞→説明型"],
    ["IM056", "bring about", "～を引き起こす", "N056", ["cause"], "A", "熟語→1語"],
    ["IM057", "result from", "～から生じる", "N057", ["be caused by"], "A", "因果表現"],
    ["IM058", "be concerned about", "～を心配している", "N058", ["worry about"], "A", "形容詞句言い換え"],
    ["IM059", "be satisfied with", "～に満足している", "N059", ["be content with"], "A", "形容詞句言い換え"],
    ["IM060", "make fun of", "～をからかう", "N060", ["laugh at"], "A", "熟語⇄熟語"],

    ["IM061", "keep A from doing", "Aが～するのを妨げる", "N061", ["prevent A from doing"], "A", "構文言い換え"],
    ["IM062", "be known for", "～で知られている", "N062", ["be famous for"], "A", "形容詞句言い換え"],
    ["IM063", "be familiar with", "～をよく知っている", "N063", ["know well"], "A", "形容詞句→説明型"],
    ["IM064", "in search of", "～を探して", "N064", ["looking for"], "A", "前置詞句⇄熟語"],
    ["IM065", "make progress in", "～で進歩する", "N065", ["improve"], "A-", "名詞化⇄動詞化"],
    ["IM066", "stand for", "～を表す", "N066", ["represent"], "A", "熟語→1語"],
    ["IM067", "take after", "～に似ている", "N067", ["resemble"], "A", "句動詞→1語"],
    ["IM068", "be accustomed to", "～に慣れている", "N068", ["be used to"], "A", "形容詞句言い換え"],
    ["IM069", "have difficulty in doing", "～するのが難しい", "N069", ["find it hard to do"], "A", "構文言い換え"],
    ["IM070", "make room for", "～のための場所を空ける", "N070", ["allow space for"], "A", "熟語→説明型"],

    ["IM071", "contribute to", "～の一因となる", "N071", ["help cause"], "A", "熟語→説明型"],
    ["IM072", "get in the way of", "～の妨げになる", "N072", ["obstruct"], "A", "熟語→1語"],
    ["IM073", "in other words", "言い換えれば", "N073", ["that is to say"], "A", "定型表現"],
    ["IM074", "for instance", "例えば", "N074", ["for example"], "A", "定型表現"],
    ["IM075", "on behalf of", "～に代わって", "N075", ["for"], "A-", "前置詞表現"],
    ["IM076", "in return for", "～のお返しに", "N076", ["in exchange for"], "A", "前置詞表現"],
    ["IM077", "with regard to", "～に関して", "N077", ["about"], "A-", "前置詞表現"],
    ["IM078", "be related to", "～に関連している", "N078", ["be connected with"], "A", "形容詞句言い換え"],
    ["IM079", "in terms of", "～の観点で", "N079", ["with respect to"], "A", "前置詞表現"],
    ["IM080", "have a tendency to", "～する傾向がある", "N080", ["tend to"], "A", "構文言い換え"],

    ["IM081", "do away with", "～を廃止する", "N081", ["abolish"], "A", "熟語→1語"],
    ["IM082", "make up for", "～を埋め合わせる", "N082", ["compensate for"], "A", "熟語⇄熟語"],
    ["IM083", "have no choice but to", "～するしかない", "N083", ["be forced to"], "A", "構文言い換え"],
    ["IM084", "be superior to", "～より優れている", "N084", ["be better than"], "A", "比較表現"],
    ["IM085", "be inferior to", "～より劣っている", "N085", ["be worse than"], "A", "比較表現"],
    ["IM086", "take place", "起こる", "N086", ["happen"], "A", "熟語→1語"],
    ["IM087", "set up", "～を設立する", "N087", ["establish"], "A", "句動詞→1語"],
    ["IM088", "look down on", "～を見下す", "N088", ["despise"], "A", "句動詞→1語"],
    ["IM089", "consent to", "～に同意する", "N089", ["agree to"], "A", "熟語⇄熟語"],
    ["IM090", "turn to A for help", "Aに助けを求める", "N090", ["ask A for help"], "A", "熟語→説明型"],

    ["IM091", "be on the point of doing", "まさに～しようとしている", "N091", ["be about to do"], "A", "構文言い換え"],
    ["IM092", "in advance", "前もって", "N092", ["beforehand"], "A", "副詞化"],
    ["IM093", "for the time being", "当分の間", "N093", ["for now"], "A", "定型表現"],
    ["IM094", "at present", "現在は", "N094", ["currently"], "A", "副詞化"],
    ["IM095", "with ease", "容易に", "N095", ["easily"], "A", "副詞化"],
    ["IM096", "in vain", "むだに", "N096", ["without success"], "A", "定型表現"],
    ["IM097", "regardless of", "～に関係なく", "N097", ["despite"], "A", "前置詞表現"],
    ["IM098", "far from", "決して～ない", "N098", ["not at all"], "A-", "否定強調表現"],
    ["IM099", "out of order", "故障している", "N099", ["not working"], "A", "状態表現"],
    ["IM100", "keep up with", "～に遅れずについていく", "N100", ["stay at the same level as"], "A", "熟語→説明型"],

    ["IM101", "come up with", "～を思いつく", "N101", ["think of", "think up"], "A", "句動詞→説明型"],
    ["IM102", "leave out", "～を省く", "N102", ["omit", "skip"], "A", "句動詞→1語"],
    ["IM103", "make sense of", "～を理解する", "N103", ["understand", "figure out"], "A", "熟語→1語"],
    ["IM104", "refrain from", "～を控える", "N104", ["avoid", "keep from"], "A", "熟語→1語"],
    ["IM105", "cope with", "～に対処する", "N105", ["deal with", "handle"], "A", "熟語⇄熟語"],
    ["IM106", "be bound to", "きっと～する", "N106", ["be certain to", "be sure to"], "A", "構文言い換え"],
    ["IM107", "be entitled to", "～する権利がある", "N107", ["have the right to"], "A", "形容詞句→説明型"],
    ["IM108", "on the verge of", "まさに～しそうで", "N108", ["close to", "almost"], "A", "前置詞句言い換え"],
    ["IM109", "in the course of", "～の間に", "N109", ["during"], "A", "前置詞表現"],
    ["IM110", "at the expense of", "～を犠牲にして", "N110", ["by sacrificing", "while sacrificing"], "A", "前置詞句→説明型"],

    ["IM111", "make ends meet", "どうにかやりくりする", "N111", ["earn just enough to live", "have enough money to live"], "A", "熟語→説明型"],
    ["IM112", "keep track of", "～の動向を追う", "N112", ["follow", "stay informed about"], "A-", "熟語→説明型"],
    ["IM113", "speak ill of", "～の悪口を言う", "N113", ["criticize", "say bad things about"], "A", "熟語→1語"],
    ["IM114", "take A into consideration", "Aを考慮に入れる", "N114", ["consider A", "take A into account"], "A", "熟語→1語"],
    ["IM115", "put pressure on", "～に圧力をかける", "N115", ["urge", "force"], "A", "熟語→1語"],
    ["IM116", "be obliged to", "～せざるを得ない", "N116", ["be forced to", "have to"], "A", "構文言い換え"],
    ["IM117", "turn out to be", "～であることがわかる", "N117", ["prove to be", "be found to be"], "A", "構文言い換え"],
    ["IM118", "provide A with B", "AにBを供給する", "N118", ["supply A with B", "give A B"], "A", "構文言い換え"],
    ["IM119", "for lack of", "～が不足しているために", "N119", ["because there is not enough of", "due to not having enough"], "A", "原因表現"],
    ["IM120", "sooner or later", "遅かれ早かれ", "N120", ["eventually", "in time"], "A", "副詞化"],

    ["IM121", "look forward to", "～を楽しみに待つ", "N121", ["await", "expect eagerly"], "A", "熟語→1語"],
    ["IM122", "show up", "現れる", "N122", ["appear", "arrive"], "A", "句動詞→1語"],
    ["IM123", "carry on", "続ける", "N123", ["continue", "go on"], "A", "句動詞→1語"],
    ["IM124", "drop in on", "～をふらっと訪ねる", "N124", ["visit casually", "stop by"], "A", "句動詞→説明型"],
    ["IM125", "make believe", "ふりをする", "N125", ["pretend", "act as if"], "A", "熟語→1語"],
    ["IM126", "bring up", "～を育てる", "N126", ["raise"], "A", "句動詞→1語"],
    ["IM127", "put aside", "～を取っておく", "N127", ["save", "keep for later"], "A", "句動詞→1語"],
    ["IM128", "take advantage of", "～を利用する", "N128", ["make use of", "exploit"], "A", "熟語→1語"],
    ["IM129", "make a point of doing", "必ず～するようにする", "N129", ["be sure to do", "always do intentionally"], "A", "構文言い換え"],
    ["IM130", "do one's best", "最善を尽くす", "N130", ["try as hard as one can", "make every effort"], "A", "熟語→説明型"],

    ["IM131", "attach importance to", "～を重視する", "N131", ["value", "think much of"], "A", "熟語→1語"],
    ["IM132", "put emphasis on", "～を強調する", "N132", ["emphasize", "stress"], "A", "熟語→1語"],
    ["IM133", "be reluctant to", "気が進まない", "N133", ["hesitate to", "be unwilling to"], "A", "形容詞句言い換え"],
    ["IM134", "have yet to do", "まだ～していない", "N134", ["have not done ... yet", "still have to do"], "A", "構文言い換え"],
    ["IM135", "let alone", "まして～ない", "N135", ["much less", "not to mention"], "A", "定型表現"],
    ["IM136", "in no time", "すぐに", "N136", ["very soon", "soon"], "A", "副詞化"],
    ["IM137", "in the meantime", "その間に", "N137", ["meanwhile", "during that time"], "A", "副詞化"],
    ["IM138", "owing to", "～のために", "N138", ["because of", "due to"], "A", "原因表現"],
    ["IM139", "by means of", "～によって", "N139", ["by using", "through"], "A", "前置詞句→説明型"],
    ["IM140", "under no circumstances", "決して～ない", "N140", ["never", "not in any case"], "A", "否定強調表現"],

    ["IM141", "comply with", "～に従う", "N141", ["obey", "follow"], "A", "熟語→1語"],
    ["IM142", "be under the impression that", "～だと思っている", "N142", ["believe that", "think that"], "A", "構文言い換え"],
    ["IM143", "make a living", "生計を立てる", "N143", ["earn money to live", "support oneself"], "A", "熟語→説明型"],
    ["IM144", "be on duty", "勤務中である", "N144", ["be working", "be at work"], "A", "状態表現"],
    ["IM145", "in case of", "～の場合に", "N145", ["if there is", "when there is"], "A-", "前置詞句→説明型"],
    ["IM146", "in honor of", "～に敬意を表して", "N146", ["to show respect for", "to celebrate"], "A", "前置詞句→説明型"],
    ["IM147", "have a good reputation", "評判がよい", "N147", ["be well thought of", "be respected"], "A", "名詞句→説明型"],
    ["IM148", "aside from", "～は別として", "N148", ["except for", "apart from"], "A", "前置詞表現"],
    ["IM149", "consist in", "～にある", "N149", ["lie in", "depend on"], "A", "熟語⇄熟語"],
    ["IM150", "derive from", "～に由来する", "N150", ["come from", "originate from"], "A", "熟語⇄熟語"]
  ];

  window.IDIOM_DATA_1KYU = RAW.map(function (row) {
    return {
      id: row[0],
      expression: row[1],
      ja: row[2],
      noteId: row[3],
      paraphraseTo: row[4],
      rank: row[5],
      type: row[6],
      exampleEn: "",
      exampleJa: "",
      note: row[1] + " = " + row[4].join(" / "),
      tags: [row[5], row[6]],
      variants: []
    };
  });
})();
