// paraphrase_data_1kyu.js
// 全商英検1級 大問11風データ（新141問版）
// noteIdベース連携用

(function () {
  "use strict";

  
  const RAW = [

    
  ["P1_001", 1, "N001", "I’m looking forward to seeing you again.", "I’m ( ) to see you again.", ["eager", "worried", "absent", "ready"], "eager", "私はまたあなたに会えるのを楽しみにしています。", "ぜひ～したい", "look forward to seeing you again の言い換え。eager to see you again で『ぜひまた会いたい』。"],
  ["P1_002", 2, "N002", "She is responsible for managing the sales team.", "She is ( ) managing the sales team.", ["in charge of", "absent from", "eager to", "far from"], "in charge of", "彼女は営業チームを管理する責任を負っている。", "～を担当している", "be responsible for の言い換え。in charge of ～ で『～を担当している』。"],
  ["P1_003", 3, "N003", "The manager turned down my proposal.", "The manager ( ) my proposal.", ["accepted", "refused", "explained", "prepared"], "refused", "部長は私の提案を断った。", "断った", "turn down の言い換え。refuse は『断る、拒否する』。"],
  ["P1_004", 4, "N004", "I have never seen such a beautiful view before.", "This is the most beautiful view I have ( ) seen.", ["ever", "already", "yet", "still"], "ever", "こんなに美しい景色は今まで見たことがない。", "今までに", "現在完了経験用法でよく使う ever。"],
  ["P1_005", 5, "N005", "We should make a decision as soon as possible.", "We should decide ( ).", ["as soon as possible", "by chance", "at first sight", "in charge of"], "as soon as possible", "私たちはできるだけ早く決定すべきだ。", "できるだけ早く", "make a decision as soon as possible を decide as soon as possible に言い換えている。"],
  ["P1_006", 6, "N006", "The train was delayed because of heavy snow.", "Heavy snow ( ) the delay of the train.", ["caused", "received", "protected", "included"], "caused", "列車は大雪のため遅れた。", "引き起こした", "because of heavy snow を主語にして caused を使う言い換え。"],
  ["P1_007", 7, "N007", "He didn’t attend the meeting yesterday.", "He was ( ) from the meeting yesterday.", ["absent", "present", "different", "free"], "absent", "彼は昨日その会議に出席しなかった。", "欠席して", "didn't attend の言い換え。be absent from ～ で『～を欠席している』。"],
  ["P1_008", 8, "N008", "This machine is easy to operate.", "It is easy ( ) this machine.", ["operating", "operated", "to operate", "operation"], "to operate", "この機械は操作するのが簡単だ。", "操作すること", "easy to operate の不定詞の形を問う問題。"],
  ["P1_009", 9, "N009", "The number of foreign tourists has increased.", "The number of foreign tourists has been ( ) recently.", ["on the rise", "on time", "at risk", "in return"], "on the rise", "外国人観光客の数は増えている。", "増加して", "increase の言い換えとして on the rise を使う。"],
  ["P1_010", 10, "N010", "Could you tell me the reason for your decision?", "Could you tell me ( ) you made that decision?", ["how", "why", "when", "where"], "why", "あなたの決定の理由を教えていただけますか。", "なぜ", "the reason for ～ の言い換えとして why を使う。"],
    ["P1_011", 11, "N011", "She was able to finish the work by herself.", "She ( ) in finishing the work by herself.", ["succeeded", "failed", "practiced", "avoided"], "succeeded"],
    ["P1_012", 12, "N012", "We must protect the environment for future generations.", "It is ( ) for us to protect the environment for future generations.", ["necessary", "immediate", "convenient", "intentional"], "necessary"],
    ["P1_013", 13, "N013", "I don’t know how to solve this problem.", "I have no ( ) how to solve this problem.", ["idea", "answer", "reason", "result"], "idea"],
    ["P1_014", 14, "N014", "The new product became popular immediately.", "The new product became popular ( ).", ["at once", "on purpose", "by chance", "in detail"], "at once"],
    ["P1_015", 15, "N015", "His explanation was too difficult for me to understand.", "His explanation was so difficult that I couldn’t ( ) it.", ["understand", "repeat", "describe", "introduce"], "understand"],
    ["P1_016", 16, "N016", "The city is famous for its old temples.", "The city is well ( ) for its old temples.", ["known", "built", "made", "used"], "known"],
    ["P1_017", 17, "N017", "I happened to meet my old friend at the station.", "I met my old friend at the station ( ).", ["by chance", "on purpose", "at once", "in detail"], "by chance"],
    ["P1_018", 18, "N018", "The company will introduce a new system next month.", "The company will ( ) a new system next month.", ["bring in", "take off", "look after", "make up"], "bring in"],
    ["P1_019", 19, "N019", "You should not speak loudly in the library.", "You are not ( ) to speak loudly in the library.", ["allowed", "invited", "ordered", "helped"], "allowed"],
    ["P1_020", 20, "N020", "The problem is too serious to ignore.", "The problem is so serious that we cannot ( ) it.", ["ignore", "solve", "notice", "explain"], "ignore"],
    ["P1_021", 21, "N021", "I prefer tea to coffee.", "I like tea ( ) than coffee.", ["better", "worse", "less", "fewer"], "better"],
    ["P1_022", 22, "N022", "The event was canceled due to the storm.", "The storm ( ) the cancellation of the event.", ["led to", "looked for", "depended on", "took after"], "led to"],
    ["P1_023", 23, "N023", "He apologized to me for being late.", "He said he was ( ) for being late.", ["sorry", "angry", "ready", "famous"], "sorry"],
    ["P1_024", 24, "N024", "This medicine will reduce your pain.", "This medicine will make your pain ( ).", ["less", "more", "worse", "full"], "less"],
    ["P1_025", 25, "N025", "My sister takes care of our dog every morning.", "My sister ( ) our dog every morning.", ["looks after", "turns down", "looks into", "takes after"], "looks after"],
    ["P1_026", 26, "N026", "They finally reached an agreement after long discussions.", "They finally ( ) after long discussions.", ["agreed", "argued", "failed", "remained"], "agreed"],
    ["P1_027", 27, "N027", "It is difficult to predict the result of the election.", "The result of the election is difficult ( ).", ["to predict", "predicting", "predicted", "prediction"], "to predict"],
    ["P1_028", 28, "N028", "The teacher encouraged us to study abroad.", "The teacher ( ) us to study abroad.", ["urged", "prevented", "refused", "avoided"], "urged"],
    ["P1_029", 29, "N029", "I could not remember his name.", "His name did not ( ).", ["come to mind", "take place", "break out", "turn down"], "come to mind"],
    ["P1_030", 30, "N030", "The population of the town is decreasing every year.", "The population of the town is getting ( ) every year.", ["smaller", "larger", "higher", "wider"], "smaller"],
    ["P1_031", 31, "N031", "If you don’t submit the form today, you cannot join the event.", "( ) you submit the form today, you cannot join the event.", ["Unless", "Although", "Because", "Since"], "Unless"],
    ["P1_032", 32, "N032", "Using less plastic can help protect the ocean.", "The ocean can be ( ) by using less plastic.", ["protected", "polluted", "wasted", "avoided"], "protected"],
    ["P1_033", 33, "N033", "Building trust with customers requires careful communication.", "Building trust with customers ( ) careful communication.", ["calls for", "gets over", "turns down", "looks after"], "calls for"],
    ["P1_034", 34, "N034", "Heavy traffic caused the delay of the bus.", "The delay of the bus was ( ) heavy traffic.", ["due to", "different from", "proud of", "full of"], "due to"],
    ["P1_035", 35, "N035", "We should try to stop accidents from happening.", "We should make efforts to prevent the ( ) of accidents.", ["occurrence", "translation", "decoration", "explanation"], "occurrence"],
    ["P1_036", 36, "N036", "As English is used in many countries, it has become an international language.", "Since English is used ( ), it functions as a common language worldwide.", ["globally", "frequently", "simultaneously", "locally"], "globally"],
    ["P1_037", 37, "N037", "The school trip was canceled because there were not enough participants.", "The school trip was canceled due to a ( ) of participants.", ["lack", "group", "pair", "crowd"], "lack"],
    ["P1_038", 38, "N038", "The team achieved its greatest success last year.", "The team was ( ) last year.", ["at its best", "in charge", "by chance", "under way"], "at its best"],
    ["P1_039", 39, "N039", "They tried hard to solve the problem of food waste.", "They worked hard to ( ) the problem of food waste.", ["overcome", "invite", "borrow", "repeat"], "overcome"],
    ["P1_040", 40, "N040", "Snow covered the mountains all night.", "There was snow ( ) the mountains all night.", ["covering", "choosing", "losing", "building"], "covering"],
    ["P1_041", 41, "N041", "He is not close to becoming the best player on the team.", "He is ( ) becoming the best player on the team.", ["far from", "good at", "ready for", "similar to"], "far from"],
    ["P1_042", 42, "N042", "The new highway helped the local economy grow.", "The new highway ( ) the growth of the local economy.", ["promoted", "refused", "destroyed", "corrected"], "promoted"],
    ["P1_043", 43, "N043", "Many citizens asked the city for better public services.", "Many citizens ( ) better public services from the city.", ["requested", "doubted", "avoided", "borrowed"], "requested"],
    ["P1_044", 44, "N044", "Because you have finished your homework, you can watch TV.", "( ) you have finished your homework, you can watch TV.", ["Since", "Unless", "Though", "Before"], "Since"],
    ["P1_045", 45, "N045", "The children could understand the story easily.", "The story ( ) sense to the children.", ["made", "gave", "took", "had"], "made"],
    ["P1_046", 46, "N046", "Your answer seems correct, but you should examine it again.", "Your answer seems correct, but you should ( ) it again.", ["check", "draw", "cancel", "print"], "check"],
    ["P1_047", 47, "N047", "She chose the difficult task on purpose.", "She ( ) chose the difficult task.", ["intentionally", "accidentally", "suddenly", "luckily"], "intentionally"],
    ["P1_048", 48, "N048", "Ken is not likely to forget his promise.", "Ken is the ( ) person to forget his promise.", ["least likely", "most careful", "most likely", "best"], "least likely"],
    ["P1_049", 49, "N049", "Students should use every chance to practice speaking English.", "Students should ( ) every chance to practice speaking English.", ["use", "lose", "miss", "hide"], "use"],
    ["P1_050", 50, "N050", "I felt nervous before giving a speech.", "I was ( ) about giving a speech.", ["anxious", "comfortable", "satisfied", "relaxed"], "anxious"],
    ["P1_051", 51, "N051", "My grandfather goes fishing from time to time.", "My grandfather ( ) goes fishing.", ["sometimes", "never", "always", "hardly ever"], "sometimes"],
    ["P1_052", 52, "N052", "You must explain the reason for your absence.", "You must ( ) for your absence.", ["account", "stand", "take", "go"], "account"],
    ["P1_053", 53, "N053", "The principal does not support the new school rule.", "The principal is ( ) the new school rule.", ["against", "for", "near", "under"], "against"],
    ["P1_054", 54, "N054", "Planting more trees can help make the town cooler in summer.", "Planting more trees can ( ) making the town cooler in summer.", ["contribute to", "take after", "give up", "put off"], "contribute to"],
    ["P1_055", 55, "N055", "Good health requires regular exercise and enough sleep.", "Good health ( ) regular exercise and enough sleep.", ["calls for", "takes off", "breaks out", "turns down"], "calls for"],
    ["P1_056", 56, "N056", "The new factory created many jobs in the town.", "The new factory brought an increase in employment ( ).", ["opportunities", "mistakes", "illnesses", "temperatures"], "opportunities"],
    ["P1_057", 57, "N057", "As soon as Ken saw the new bicycle, he wanted to buy it.", "Ken wanted to buy the new bicycle at ( ).", ["first sight", "the end", "any price", "last"], "first sight"],
    ["P1_058", 58, "N058", "To be honest, I was not satisfied with his answer.", "( ) speaking, I was not satisfied with his answer.", ["Frankly", "Usually", "Suddenly", "Lightly"], "Frankly"],
    ["P1_059", 59, "N059", "The teacher looked into the cause of the trouble.", "The teacher ( ) the cause of the trouble.", ["investigated", "celebrated", "introduced", "translated"], "investigated"],
    ["P1_060", 60, "N060", "There is no solving this problem without teamwork.", "It is ( ) to solve this problem without teamwork.", ["impossible", "careless", "useful", "natural"], "impossible"],
    ["P1_061", 61, "N061", "This new cleaner can get rid of bad smells.", "This new cleaner can ( ) bad smells.", ["remove", "increase", "accept", "borrow"], "remove"],
    ["P1_062", 62, "N062", "She has improved her writing skills this year.", "She has made ( ) her writing skills this year.", ["progress in", "a mistake with", "a promise about", "room for"], "progress in"],
    ["P1_063", 63, "N063", "It was not long before the bus arrived.", "The bus arrived ( ).", ["soon", "lately", "finally", "once"], "soon"],
    ["P1_064", 64, "N064", "The results of the survey will be published next week.", "The results of the survey will be ( ) next week.", ["released", "hidden", "repaired", "refused"], "released"],
    ["P1_065", 65, "N065", "He never accepted my advice.", "He ( ) to accept my advice.", ["refused", "offered", "agreed", "managed"], "refused"],
    ["P1_066", 66, "N066", "She spoke English with a slight Japanese accent.", "She spoke English with a ( ) Japanese accent.", ["mild", "heavy", "strong", "serious"], "mild"],
    ["P1_067", 67, "N067", "Mike does not depend on his family for money.", "Mike is ( ) of his family’s financial help.", ["independent", "fond", "full", "afraid"], "independent"],
    ["P1_068", 68, "N068", "We had to call off the picnic because of the rain.", "The rain forced us to ( ) the picnic.", ["cancel", "extend", "complete", "attend"], "cancel"],
    ["P1_069", 69, "N069", "Your essay is excellent.", "There is ( ) room for improvement in your essay.", ["little", "many", "several", "enough"], "little"],
    ["P1_070", 70, "N070", "The company will employ ten new workers this spring.", "Ten new workers will be ( ) by the company this spring.", ["hired", "fired", "blamed", "trained"], "hired"],
    ["P1_071", 71, "N071", "The students expressed ideas for a better school festival.", "The students made ( ) for a better school festival.", ["suggestions", "mistakes", "excuses", "prices"], "suggestions"],
    ["P1_072", 72, "N072", "She made believe she didn't hear his comment to avoid an argument.", "She ( ) not to hear his comment to avoid an argument.", ["pretended", "happened", "decided", "refused"], "pretended"],
    ["P1_073", 73, "N073", "Parents have to protect their children.", "Parents have the ( ) of protecting their children.", ["responsibility", "difficulty", "possibility", "experience"], "responsibility"],
    ["P1_074", 74, "N074", "My phone is too old, so I should change it for a new one.", "My phone is too old, so I should ( ) it.", ["replace", "reduce", "repair", "respect"], "replace"],
    ["P1_075", 75, "N075", "It is crucial that all students in the school follow this rule.", "This rule is ( ) to every student in the school.", ["important", "mysterious", "foreign", "private"], "important"],
    ["P1_076", 76, "N076", "I came across my former teacher at the station.", "I ( ) to see my former teacher at the station.", ["happened", "decided", "wanted", "promised"], "happened"],
    ["P1_077", 77, "N077", "The team worked hard to win the final game.", "The team made great ( ) to win the final game.", ["efforts", "progress", "money", "damage"], "efforts"],
    ["P1_078", 78, "N078", "The price of rice has become higher recently.", "The price of rice has ( ) recently.", ["risen", "fallen", "dropped", "disappeared"], "risen"],
    ["P1_079", 79, "N079", "I’m sorry about the result of the exam.", "I’m ( ) about the result of the exam.", ["disappointed", "excited", "pleased", "relaxed"], "disappointed"],
    ["P1_080", 80, "N080", "The science question was too difficult for me.", "I couldn’t ( ) the science question.", ["understand", "hear", "believe", "touch"], "understand"],
    ["P1_081", 81, "N081", "I answered the question as clearly as I could.", "To the best of my ( ), I answered the question clearly.", ["ability", "memory", "opinion", "promise"], "ability"],
    ["P1_082", 82, "N082", "I couldn’t understand how to use this machine.", "I couldn’t ( ) out how to use this machine.", ["figure", "carry", "put", "turn"], "figure"],
    ["P1_083", 83, "N083", "Ken is against the new school rule.", "Ken ( ) with the new school rule.", ["disagrees", "agrees", "deals", "compares"], "disagrees"],
    ["P1_084", 84, "N084", "This computer is superior to my old one.", "This computer is ( ) than my old one.", ["better", "worse", "slower", "smaller"], "better"],
    ["P1_085", 85, "N085", "She should be upset about the result.", "It is ( ) for her to be upset about the result.", ["natural", "impossible", "unnecessary", "careless"], "natural"],
    ["P1_086", 86, "N086", "The captain is looked up to by all the players.", "The captain is ( ) by all the players.", ["respected", "suspected", "ignored", "repaired"], "respected"],
    ["P1_087", 87, "N087", "Emi made up her mind to study abroad.", "Emi made a ( ) to study abroad.", ["decision", "mistake", "difference", "rule"], "decision"],
    ["P1_088", 88, "N088", "The train arrived as planned.", "The train arrived ( ).", ["on schedule", "on purpose", "on board", "on sale"], "on schedule"],
    ["P1_089", 89, "N089", "I am happy to answer your questions.", "I am ( ) to answer your questions.", ["willing", "likely", "unable", "supposed"], "willing"],
    ["P1_090", 90, "N090", "You don’t have to pay for dinner today. I invited you.", "Dinner is ( ) today.", ["on me", "by chance", "at once", "on schedule"], "on me"],
    ["P1_091", 91, "N091", "My teacher talked me into entering the speech contest.", "My teacher ( ) me to enter the speech contest.", ["persuaded", "refused", "allowed", "forced"], "persuaded"],
    ["P1_092", 92, "N092", "It goes without saying that health is more important than money.", "( ) to say, health is more important than money.", ["Needless", "Strange", "Lucky", "Careful"], "Needless"],
    ["P1_093", 93, "N093", "Please take off your hat inside the building.", "Please ( ) your hat inside the building.", ["remove", "wear", "brush", "carry"], "remove"],
    ["P1_094", 94, "N094", "If it were not for the sun, plants could not grow.", "( ) the sun, plants could not grow.", ["Without", "Under", "Since", "Through"], "Without"],
    ["P1_095", 95, "N095", "We don’t have any seats available for tonight’s show.", "All the seats are ( ) for tonight’s show.", ["occupied", "empty", "broken", "cleaned"], "occupied"],
    ["P1_096", 96, "N096", "The Olympic Games are held every four years.", "The Olympic Games ( ) every four years.", ["take place", "look into", "get over", "come across"], "take place"],
    ["P1_097", 97, "N097", "There are only ten students in the classroom.", "There are no ( ) than ten students in the classroom.", ["more", "less", "better", "larger"], "more"],
    ["P1_098", 98, "N098", "My father never fails to read the newspaper in the morning.", "My father ( ) reads the newspaper in the morning.", ["always", "sometimes", "seldom", "never"], "always"],
    ["P1_099", 99, "N099", "We have many problems to deal with before the event.", "We have many problems to ( ) before the event.", ["handle", "avoid", "damage", "compare"], "handle"],
    ["P1_100", 100, "N100", "This job calls for careful planning.", "This job ( ) careful planning.", ["requires", "feeds", "serves", "adds"], "requires"],
    ["P1_101", 101, "N101", "My brother has twice as many CDs as I have.", "My brother has twice the ( ) of CDs I have.", ["number", "size", "height", "weight"], "number"],
    ["P1_102", 102, "N102", "You should make use of your free time.", "You should ( ) your free time.", ["take advantage of", "make fun of", "look forward to", "keep in touch with"], "take advantage of"],
    ["P1_103", 103, "N103", "I happened to see my old classmate on the train.", "I saw my old classmate on the train ( ).", ["by chance", "on purpose", "at once", "in detail"], "by chance"],
    ["P1_104", 104, "N104", "I don’t understand what this sentence means.", "This sentence doesn’t ( ) to me.", ["make sense", "take place", "come across", "put off"], "make sense"],
    ["P1_105", 105, "N105", "If it had not been for his advice, I would have failed.", "( ) his advice, I would have failed.", ["Without", "With", "For", "Under"], "Without"],
    ["P1_106", 106, "N106", "Every time I hear this song, I remember my childhood.", "This song always ( ) me of my childhood.", ["reminds", "remembers", "resembles", "removes"], "reminds"],
    ["P1_107", 107, "N107", "Mr. Brown is in charge of the sales department.", "Mr. Brown is ( ) for the sales department.", ["responsible", "suitable", "eager", "late"], "responsible"],
    ["P1_108", 108, "N108", "I couldn’t understand the meaning of the message.", "I couldn’t ( ) out the meaning of the message.", ["figure", "carry", "spread", "get"], "figure"],
    ["P1_109", 109, "N109", "Many children are in trouble because they do not have enough food.", "Many children are ( ) from hunger.", ["suffering", "retiring", "celebrating", "separating"], "suffering"],
    ["P1_110", 110, "N110", "If the weather is not bad, the sports day will be held tomorrow.", "The sports day will be held tomorrow ( ) the weather is bad.", ["unless", "since", "although", "as"], "unless"],
    ["P1_111", 111, "N111", "Who can believe such an unbelievable story?", "( ) can believe such an unbelievable story.", ["Nobody", "Anybody", "Everybody", "Somebody"], "Nobody"],
    ["P1_112", 112, "N112", "I can’t put up with his rude behavior anymore.", "I can’t ( ) his rude behavior anymore.", ["stand", "enjoy", "remember", "expect"], "stand"],
    ["P1_113", 113, "N113", "Ken looks like his grandfather.", "Ken ( ) his grandfather.", ["resembles", "respects", "recommends", "recognizes"], "resembles"],
    ["P1_114", 114, "N114", "My brother often forgets important things.", "My brother has a ( ) of forgetting important things.", ["habit", "handicap", "harmony", "honesty"], "habit"],
    ["P1_115", 115, "N115", "You need to fill in this application form.", "You need to ( ) this application form.", ["complete", "collect", "bring", "offer"], "complete"],
    ["P1_116", 116, "N116", "The car almost hit the old man.", "The car ( ) hit the old man.", ["nearly", "hardly", "completely", "seldom"], "nearly"],
    ["P1_117", 117, "N117", "This article will help you understand Japanese culture.", "This article will help you ( ) Japanese culture.", ["make sense of", "look down on", "get away with", "run out of"], "make sense of"],
    ["P1_118", 118, "N118", "The flight was late because of thick fog.", "The flight was ( ) by thick fog.", ["delayed", "destroyed", "broken", "stuck"], "delayed"],
    ["P1_119", 119, "N119", "Yumi is a good speaker of French.", "Yumi speaks French ( ).", ["fluently", "poorly", "quietly", "loudly"], "fluently"],
    ["P1_120", 120, "N120", "A typhoon is coming toward the island.", "A typhoon is ( ) the island.", ["approaching", "leaving", "breaking", "crossing"], "approaching"],
    ["P1_121", 121, "N121", "He got over the sadness after his dog died.", "He ( ) from the sadness after his dog died.", ["recovered", "suffered", "learned", "heard"], "recovered"],
    ["P1_122", 122, "N122", "The students learned the speech by heart.", "The students ( ) the speech.", ["memorized", "created", "copied", "reviewed"], "memorized"],
    ["P1_123", 123, "N123", "Tom is in charge of planning the school event.", "Tom is ( ) for planning the school event.", ["responsible", "late", "eager", "famous"], "responsible"],
    ["P1_124", 124, "N124", "If her advice had not helped me, I would have made a serious mistake.", "( ) her advice, I could not avoid making a serious mistake.", ["But for", "With", "Against", "Under"], "But for"],
    ["P1_125", 125, "N125", "I couldn't catch the early bus.", "I ( ) the early bus.", ["missed", "lost", "took", "saw"], "missed"],
    ["P1_126", 126, "N126", "Until Emma was six, she was brought up by her aunt.", "Until Emma was six, she was ( ) by her aunt.", ["raised", "praised", "scolded", "spoiled"], "raised"],
    ["P1_127", 127, "N127", "The letters UN stand for “United Nations.”", "The letters UN ( ) the “United Nations.”", ["represent", "offer", "adopt", "suspect"], "represent"],
    ["P1_128", 128, "N128", "There is no denying that she is talented.", "It is ( ) to deny that she is talented.", ["impossible", "natural", "normal", "doubtful"], "impossible"],
    ["P1_129", 129, "N129", "The movie was so touching that many people cried.", "Many people were ( ) by the movie.", ["affected", "disappointed", "frightened", "bothered"], "affected"],
    ["P1_130", 130, "N130", "Significant changes take place during the evolution process.", " Significant changes ( ) during the evolution process.", ["occurred", "remained", "disappeared", "repeated"], "occurred"],
    ["P1_131", 131, "N131", "You will probably not pass the test without studying.", "It is ( ) that you will pass the test without studying.", ["unlikely", "likely", "natural", "clear"], "unlikely"],
    ["P1_132", 132, "N132", "The ceremony began as planned.", "The ceremony began ( ).", ["on schedule", "behind schedule", "at last", "on air"], "on schedule"],
    ["P1_133", 133, "N133", "My sister often leaves the lights on.", "My sister has a ( ) of leaving the lights on.", ["habit", "hobby", "policy", "theory"], "habit"],
    ["P1_134", 134, "N134", "You shouldn’t count on his promise.", "You shouldn’t ( ) his promise.", ["trust", "disturb", "forgive", "visit"], "trust"],
    ["P1_135", 135, "N135", "This article is beyond my understanding.", "I can’t ( ) this article at all.", ["follow", "buy", "guess", "find"], "follow"],
    ["P1_136", 136, "N136", "It is no use trying to finish the work in five minutes.", "It is ( ) to try to finish the work in five minutes.", ["hopeless", "careless", "priceless", "timeless"], "hopeless"],
    ["P1_137", 137, "N137", "She is concerned about her son’s health.", "She is ( ) about her son’s health.", ["anxious", "excited", "pleased", "satisfied"], "anxious"],
    ["P1_138", 138, "N138", "You should know better than to make fun of others.", "You should be ( ) enough not to make fun of others.", ["wise", "brave", "calm", "kind"], "wise"],
    ["P1_139", 139, "N139", "I’ll drop you a line when I arrive in New York.", "I’ll ( ) when I arrive in New York.", ["write to", "take after", "look into", "put off"], "write to"],
    ["P1_140", 140, "N140", "We had to put off the concert because of the storm.", "The storm ( ) us to put off the concert.", ["forced", "wanted", "expected", "ordered"], "forced"],
    ["P1_141", 141, "N141", "Ken can’t play the piano, and he certainly can’t play the violin.", "Ken can’t play the piano, much ( ) the violin.", ["less", "more", "better", "worse"], "less"]
  ];
const EXTRA = {
  "P1_001": { ja: "私はまたあなたに会えるのを楽しみにしています。", answerJa: "熱望して、ぜひ～したい" },
  "P1_002": { ja: "彼女は営業チームの管理を担当している。", answerJa: "～を担当している" },
  "P1_003": { ja: "部長は私の提案を断った。", answerJa: "断った、拒否した" },
  "P1_004": { ja: "こんなに美しい景色は今まで見たことがない。", answerJa: "今までに" },
  "P1_005": { ja: "私たちはできるだけ早く決定すべきだ。", answerJa: "できるだけ早く" },
  "P1_006": { ja: "列車は大雪のため遅れた。", answerJa: "引き起こした" },
  "P1_007": { ja: "彼は昨日その会議に出席しなかった。", answerJa: "欠席して" },
  "P1_008": { ja: "この機械は操作するのが簡単だ。", answerJa: "操作すること" },
  "P1_009": { ja: "外国人観光客の数は最近増えている。", answerJa: "増加して、上昇して" },
  "P1_010": { ja: "その決定をした理由を教えていただけますか。", answerJa: "なぜ" },
  "P1_011": { ja: "彼女は一人でその仕事を終えることができた。", answerJa: "成功した" },
  "P1_012": { ja: "私たちは将来の世代のために環境を守らなければならない。", answerJa: "必要な" },
  "P1_013": { ja: "私はこの問題の解き方がわからない。", answerJa: "考え、見当" },
  "P1_014": { ja: "その新製品はすぐに人気になった。", answerJa: "すぐに" },
  "P1_015": { ja: "彼の説明は難しすぎて私には理解できなかった。", answerJa: "理解する" },
  "P1_016": { ja: "その都市は古い寺で有名だ。", answerJa: "知られている" },
  "P1_017": { ja: "私は駅で昔の友人に偶然会った。", answerJa: "偶然に" },
  "P1_018": { ja: "その会社は来月新しいシステムを導入する予定だ。", answerJa: "導入する、持ち込む" },
  "P1_019": { ja: "図書館では大声で話してはいけない。", answerJa: "許されている" },
  "P1_020": { ja: "その問題は深刻すぎて無視できない。", answerJa: "無視する" },
  "P1_021": { ja: "私はコーヒーより紅茶のほうが好きだ。", answerJa: "よりよく、もっと" },
  "P1_022": { ja: "その行事は嵐のため中止になった。", answerJa: "～につながった、引き起こした" },
  "P1_023": { ja: "彼は遅刻したことを私に謝った。", answerJa: "すまなく思って" },
  "P1_024": { ja: "この薬はあなたの痛みを和らげるだろう。", answerJa: "より少なく、より弱く" },
  "P1_025": { ja: "姉は毎朝私たちの犬の世話をしている。", answerJa: "～の世話をする" },
  "P1_026": { ja: "彼らは長い議論の末、ついに合意に達した。", answerJa: "同意した" },
  "P1_027": { ja: "選挙の結果を予測するのは難しい。", answerJa: "予測すること" },
  "P1_028": { ja: "先生は私たちに留学するよう勧めた。", answerJa: "強く勧めた、促した" },
  "P1_029": { ja: "私は彼の名前を思い出せなかった。", answerJa: "心に浮かぶ" },
  "P1_030": { ja: "その町の人口は毎年減っている。", answerJa: "より小さく" },
  "P1_031": { ja: "今日その用紙を提出しなければ、その行事に参加できない。", answerJa: "もし～でなければ" },
  "P1_032": { ja: "プラスチックの使用を減らすことは海を守るのに役立つ。", answerJa: "守られた" },
  "P1_033": { ja: "顧客との信頼関係を築くには丁寧なコミュニケーションが必要だ。", answerJa: "必要とする" },
  "P1_034": { ja: "激しい交通渋滞がバスの遅れを引き起こした。", answerJa: "～のために" },
  "P1_035": { ja: "私たちは事故が起こるのを防ぐ努力をすべきだ。", answerJa: "発生" },
  "P1_036": { ja: "英語は多くの国で使われているので、国際語になっている。", answerJa: "世界的に" },
  "P1_037": { ja: "参加者が足りなかったため、修学旅行は中止になった。", answerJa: "不足" },
  "P1_038": { ja: "そのチームは昨年最大の成功を収めた。", answerJa: "最高の状態で" },
  "P1_039": { ja: "彼らは食品ロスの問題を解決しようと一生懸命努力した。", answerJa: "克服する" },
  "P1_040": { ja: "雪が一晩中山々を覆っていた。", answerJa: "覆っている" },
  "P1_041": { ja: "彼はチームで最高の選手になるにはほど遠い。", answerJa: "～にはほど遠い" },
  "P1_042": { ja: "その新しい高速道路は地域経済の成長を助けた。", answerJa: "促進した" },
  "P1_043": { ja: "多くの市民が市によりよい公共サービスを求めた。", answerJa: "要求した" },
  "P1_044": { ja: "宿題を終えたので、テレビを見てもよい。", answerJa: "～なので" },
  "P1_045": { ja: "子どもたちはその話を簡単に理解できた。", answerJa: "作った、なした" },
  "P1_046": { ja: "あなたの答えは正しそうだが、もう一度確かめるべきだ。", answerJa: "確認する" },
  "P1_047": { ja: "彼女はわざと難しい課題を選んだ。", answerJa: "意図的に" },
  "P1_048": { ja: "ケンは約束を忘れそうにない。", answerJa: "最も～しそうにない" },
  "P1_049": { ja: "生徒は英語を話す練習のためにあらゆる機会を使うべきだ。", answerJa: "使う" },
  "P1_050": { ja: "私はスピーチをする前に緊張していた。", answerJa: "不安な、心配して" },
  "P1_051": { ja: "祖父は時々釣りに行く。", answerJa: "時々" },
  "P1_052": { ja: "欠席した理由を説明しなければならない。", answerJa: "説明する" },
  "P1_053": { ja: "校長はその新しい校則を支持していない。", answerJa: "反対して" },
  "P1_054": { ja: "もっと木を植えることは、夏に町をより涼しくするのに役立つ。", answerJa: "～に貢献する" },
  "P1_055": { ja: "健康には定期的な運動と十分な睡眠が必要だ。", answerJa: "必要とする" },
  "P1_056": { ja: "その新しい工場は町に多くの仕事を生み出した。", answerJa: "機会" },
  "P1_057": { ja: "ケンはその新しい自転車を一目見て買いたくなった。", answerJa: "一目" },
  "P1_058": { ja: "正直に言うと、私は彼の答えに満足していなかった。", answerJa: "率直に言えば" },
  "P1_059": { ja: "先生はそのトラブルの原因を調べた。", answerJa: "調査した" },
  "P1_060": { ja: "チームワークなしでこの問題を解くのは不可能だ。", answerJa: "不可能な" },
  "P1_061": { ja: "この新しいクリーナーは嫌なにおいを取り除くことができる。", answerJa: "取り除く" },
  "P1_062": { ja: "彼女は今年、作文の力を伸ばした。", answerJa: "～における進歩" },
  "P1_063": { ja: "バスはまもなく到着した。", answerJa: "すぐに" },
  "P1_064": { ja: "その調査結果は来週公表される予定だ。", answerJa: "公開された、発表された" },
  "P1_065": { ja: "彼は決して私の助言を受け入れなかった。", answerJa: "拒否した" },
  "P1_066": { ja: "彼女は少し日本語なまりのある英語を話した。", answerJa: "軽い、わずかな" },
  "P1_067": { ja: "マイクはお金のことで家族に頼っていない。", answerJa: "独立して" },
  "P1_068": { ja: "私たちは雨のためピクニックを中止しなければならなかった。", answerJa: "中止する" },
  "P1_069": { ja: "あなたの作文はすばらしい。", answerJa: "ほとんどない" },
  "P1_070": { ja: "その会社はこの春、新しく10人の労働者を雇う予定だ。", answerJa: "雇われた" },
  "P1_071": { ja: "生徒たちはよりよい文化祭のための案を出した。", answerJa: "提案" },
  "P1_072": { ja: "彼女は口論を避けるため、彼の発言が聞こえなかったふりをした。", answerJa: "～のふりをした" },
  "P1_073": { ja: "親は子どもを守らなければならない。", answerJa: "責任" },
  "P1_074": { ja: "私の携帯は古すぎるので、新しいものに替えるべきだ。", answerJa: "取り替える" },
  "P1_075": { ja: "学校のすべての生徒がこの規則に従うことが重要だ。", answerJa: "重要な" },
  "P1_076": { ja: "私は駅で以前の先生に偶然会った。", answerJa: "たまたま～した" },
  "P1_077": { ja: "そのチームは決勝戦に勝つために一生懸命努力した。", answerJa: "努力" },
  "P1_078": { ja: "米の値段は最近高くなっている。", answerJa: "上がった" },
  "P1_079": { ja: "私は試験の結果を残念に思っている。", answerJa: "失望した" },
  "P1_080": { ja: "その理科の問題は私には難しすぎた。", answerJa: "理解する" },
  "P1_081": { ja: "私はできるだけはっきりその問いに答えた。", answerJa: "能力" },
  "P1_082": { ja: "私はこの機械の使い方が理解できなかった。", answerJa: "理解する" },
  "P1_083": { ja: "ケンはその新しい校則に反対している。", answerJa: "反対する" },
  "P1_084": { ja: "このコンピュータは私の古いものより優れている。", answerJa: "よりよい" },
  "P1_085": { ja: "彼女がその結果に腹を立てるのは当然だ。", answerJa: "当然の" },
  "P1_086": { ja: "その主将はすべての選手に尊敬されている。", answerJa: "尊敬されて" },
  "P1_087": { ja: "エミは留学する決心をした。", answerJa: "決定" },
  "P1_088": { ja: "列車は予定通り到着した。", answerJa: "予定通りに" },
  "P1_089": { ja: "私は喜んであなたの質問に答えます。", answerJa: "進んで～する" },
  "P1_090": { ja: "今日は夕食代を払わなくてよい。私が招待したのだから。", answerJa: "私のおごり" },
  "P1_091": { ja: "先生は私を説得してスピーチコンテストに出場させた。", answerJa: "説得した" },
  "P1_092": { ja: "健康がお金より大切なのは言うまでもない。", answerJa: "言うまでもなく" },
  "P1_093": { ja: "建物の中では帽子を取ってください。", answerJa: "取り外す、脱ぐ" },
  "P1_094": { ja: "太陽がなければ、植物は育たないだろう。", answerJa: "～がなければ" },
  "P1_095": { ja: "今夜のショーには空いている席がない。", answerJa: "使用中で、ふさがって" },
  "P1_096": { ja: "オリンピックは4年ごとに行われる。", answerJa: "行われる、起こる" },
  "P1_097": { ja: "教室にはたった10人の生徒しかいない。", answerJa: "より多く" },
  "P1_098": { ja: "父は朝、必ず新聞を読む。", answerJa: "いつも" },
  "P1_099": { ja: "私たちは行事の前に対処すべき問題を多く抱えている。", answerJa: "対処する" },
  "P1_100": { ja: "この仕事には慎重な計画が必要だ。", answerJa: "必要とする" },
  "P1_101": { ja: "兄は私の2倍のCDを持っている。", answerJa: "数" },
  "P1_102": { ja: "自由時間を活用すべきだ。", answerJa: "利用する" },
  "P1_103": { ja: "私は電車の中で昔のクラスメートを偶然見かけた。", answerJa: "偶然に" },
  "P1_104": { ja: "この文の意味がわからない。", answerJa: "意味をなす" },
  "P1_105": { ja: "彼の助言がなかったら、私は失敗していただろう。", answerJa: "～がなければ" },
  "P1_106": { ja: "この歌を聞くたびに、私は子どものころを思い出す。", answerJa: "思い出させる" },
  "P1_107": { ja: "ブラウン氏は営業部を担当している。", answerJa: "責任がある、担当している" },
  "P1_108": { ja: "私はそのメッセージの意味を理解できなかった。", answerJa: "理解する" },
  "P1_109": { ja: "多くの子どもたちは十分な食べ物がなく困っている。", answerJa: "苦しんで" },
  "P1_110": { ja: "天気が悪くなければ、運動会は明日行われる。", answerJa: "もし～でなければ" },
  "P1_111": { ja: "そんな信じられない話をいったい誰が信じられるだろうか。", answerJa: "誰も～ない" },
  "P1_112": { ja: "私はもう彼の失礼なふるまいには我慢できない。", answerJa: "我慢する" },
  "P1_113": { ja: "ケンは祖父に似ている。", answerJa: "似ている" },
  "P1_114": { ja: "兄はよく大事なことを忘れる。", answerJa: "習慣、癖" },
  "P1_115": { ja: "この申込書に記入する必要がある。", answerJa: "完成させる、記入する" },
  "P1_116": { ja: "その車は危うくその老人にぶつかるところだった。", answerJa: "ほとんど、危うく" },
  "P1_117": { ja: "この記事は日本文化を理解するのに役立つだろう。", answerJa: "理解する" },
  "P1_118": { ja: "その便は濃い霧のため遅れた。", answerJa: "遅らされた" },
  "P1_119": { ja: "ユミはフランス語を上手に話す。", answerJa: "流ちょうに" },
  "P1_120": { ja: "台風がその島に向かって来ている。", answerJa: "近づいている" },
  "P1_121": { ja: "彼は犬が死んだ後、その悲しみを乗り越えた。", answerJa: "回復した" },
  "P1_122": { ja: "生徒たちはそのスピーチを暗記した。", answerJa: "暗記した" },
  "P1_123": { ja: "トムは学校行事の計画を担当している。", answerJa: "責任がある、担当している" },
  "P1_124": { ja: "彼女の助言がなかったなら、私は大きな間違いをしていただろう。", answerJa: "～がなければ" },
  "P1_125": { ja: "私は早いバスに間に合わなかった。", answerJa: "乗り遅れた" },
  "P1_126": { ja: "エマは6歳まで叔母に育てられた。", answerJa: "育てられた" },
  "P1_127": { ja: "UN という文字は『国際連合』を表す。", answerJa: "表す" },
  "P1_128": { ja: "彼女に才能があることは否定できない。", answerJa: "不可能な" },
  "P1_129": { ja: "その映画はとても感動的で、多くの人が泣いた。", answerJa: "影響を受けた、心を動かされた" },
  "P1_130": { ja: "進化の過程で、重要な変化が起こる", answerJa: "起こった" },
  "P1_131": { ja: "勉強しなければ、その試験に受からないだろう。", answerJa: "ありそうにない" },
  "P1_132": { ja: "その式典は予定通り始まった。", answerJa: "予定通りに" },
  "P1_133": { ja: "妹はよく電気をつけっぱなしにする。", answerJa: "習慣、癖" },
  "P1_134": { ja: "彼の約束を当てにしてはいけない。", answerJa: "信頼する、当てにする" },
  "P1_135": { ja: "この記事は私には理解を超えている。", answerJa: "理解する、ついていく" },
  "P1_136": { ja: "5分でその仕事を終えようとしても無駄だ。", answerJa: "望みがない、無駄な" },
  "P1_137": { ja: "彼女は息子の健康を心配している。", answerJa: "不安な、心配して" },
  "P1_138": { ja: "人をからかうほど愚かではないはずだ。", answerJa: "賢い" },
  "P1_139": { ja: "ニューヨークに着いたら手紙を書くよ。", answerJa: "～に手紙を書く、連絡する" },
  "P1_140": { ja: "私たちは嵐のためコンサートを延期しなければならなかった。", answerJa: "強いて～させた" },
  "P1_141": { ja: "ケンはピアノが弾けないし、ましてバイオリンなど弾けない。", answerJa: "まして～ない" }
};

  window.PARAPHRASE_DATA_1KYU = RAW.map(function (row) {
  const noteId = String(row[2] || "").trim().toUpperCase();
  const extra = EXTRA[row[0]] || {};

  return {
    id: row[0],
    displayNo: row[1],
    noteId: noteId,
    noteIds: noteId ? [noteId] : [],
    a: row[3],
    b: row[4],
    choices: row[5],
    answer: row[6],
    ja: extra.ja || "",
    answerJa: extra.answerJa || "",
    note: "",
    tags: ["大問11", "言い換え"]
  };
});

})();
