window.PARAPHRASE_DATA_1KYU = [
     {
    id: "P1_001",
    sourceId: "IM001",
    a: "Many students took part in the volunteer program last summer.",
    b: "Many students ( ) the volunteer program last summer.",
    choices: ["participated in", "complained about", "applied for", "looked into"],
    answer: "participated in",
    ja: "多くの生徒が昨年の夏、そのボランティア活動に参加した。",
    note: "take part in = participate in（〜に参加する）\n選択肢:\nparticipated in = 〜に参加した\ncomplained about = 〜について不満を言った\napplied for = 〜に応募した\nlooked into = 〜を調べた",
    tags: ["熟語→言い換え", "動詞句"]
  },
  {
    id: "P1_002",
    sourceId: "IM002",
    a: "The city decided to put off the festival because of the storm.",
    b: "The city decided to ( ) the festival because of the storm.",
    choices: ["postpone", "hold", "advertise", "discuss"],
    answer: "postpone",
    ja: "市は嵐のため、その祭りを延期することにした。",
    note: "put off = postpone（〜を延期する）\n選択肢:\npostpone = 延期する\nhold = 開催する\nadvertise = 宣伝する\ndiscuss = 話し合う",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_003",
    sourceId: "IM003",
    a: "The committee is made up of five teachers and two students.",
    b: "The committee ( ) five teachers and two students.",
    choices: ["consists of", "depends on", "agrees with", "suffers from"],
    answer: "consists of",
    ja: "その委員会は5人の教師と2人の生徒で構成されている。",
    note: "be made up of = consist of（〜で構成される）\n選択肢:\nconsists of = 〜で成り立っている\ndepends on = 〜に依存する\nagrees with = 〜に賛成する / 〜と一致する\nsuffers from = 〜に苦しむ",
    tags: ["構成表現", "動詞句"]
  },
  {
    id: "P1_004",
    sourceId: "IM008",
    a: "The police will look into the cause of the fire.",
    b: "The police will ( ) the cause of the fire.",
    choices: ["investigate", "celebrate", "compare", "imagine"],
    answer: "investigate",
    ja: "警察はその火事の原因を調査するつもりだ。",
    note: "look into = investigate（〜を調査する）\n選択肢:\ninvestigate = 調査する\ncelebrate = 祝う\ncompare = 比較する\nimagine = 想像する",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_005",
    sourceId: "IM009",
    a: "He got over the illness in a few days.",
    b: "He ( ) the illness in a few days.",
    choices: ["recovered from", "depended on", "stared at", "ran into"],
    answer: "recovered from",
    ja: "彼は数日でその病気を克服した。",
    note: "get over = recover from（〜から回復する）\n選択肢:\nrecovered from = 〜から回復した\ndepended on = 〜に頼った\nstared at = 〜をじっと見つめた\nran into = 〜に偶然出会った",
    tags: ["句動詞→言い換え", "動詞句"]
  },
  {
    id: "P1_006",
    sourceId: "IM010",
    a: "I am against the new plan.",
    b: "I ( ) the new plan.",
    choices: ["disagree with", "agree with", "deal with", "compare with"],
    answer: "disagree with",
    ja: "私はその新しい計画に反対している。",
    note: "be against = disagree with（〜に反対する）\n選択肢:\ndisagree with = 〜に反対する\nagree with = 〜に賛成する\ndeal with = 〜に対処する\ncompare with = 〜を比較する",
    tags: ["形容詞句→動詞句", "意見"]
  },
  {
    id: "P1_007",
    sourceId: "IM013",
    a: "A lack of sleep can lead to poor concentration.",
    b: "A lack of sleep can ( ) poor concentration.",
    choices: ["cause", "reduce", "prevent", "express"],
    answer: "cause",
    ja: "睡眠不足は集中力の低下を引き起こすことがある。",
    note: "lead to = cause（〜を引き起こす）\n選択肢:\ncause = 引き起こす\nreduce = 減らす\nprevent = 防ぐ\nexpress = 表現する",
    tags: ["因果表現", "動詞"]
  },
  {
    id: "P1_008",
    sourceId: "IM024",
    a: "How do you account for the sudden change in her attitude?",
    b: "How do you ( ) the sudden change in her attitude?",
    choices: ["explain", "ignore", "mention", "discover"],
    answer: "explain",
    ja: "彼女の態度の急な変化をどう説明しますか。",
    note: "account for = explain（〜を説明する）\n選択肢:\nexplain = 説明する\nignore = 無視する\nmention = 言及する\ndiscover = 発見する",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_009",
    sourceId: "IM025",
    a: "Many children look up to their coach.",
    b: "Many children ( ) their coach.",
    choices: ["respect", "encourage", "replace", "blame"],
    answer: "respect",
    ja: "多くの子どもたちがそのコーチを尊敬している。",
    note: "look up to = respect（〜を尊敬する）\n選択肢:\nrespect = 尊敬する\nencourage = 励ます\nreplace = 取り替える\nblame = 非難する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_010",
    sourceId: "IM030",
    a: "My grandfather no longer drives at night.",
    b: "My grandfather does not drive at night ( ).",
    choices: ["anymore", "regularly", "abroad", "instead"],
    answer: "anymore",
    ja: "祖父はもう夜に運転しない。",
    note: "no longer = not ... anymore（もはや〜ない）\n選択肢:\nanymore = もうこれ以上\nregularly = 規則的に / いつも\nabroad = 海外で\ninstead = その代わりに",
    tags: ["否定言い換え", "副詞"]
  },
  {
    id: "P1_011",
    sourceId: "IM031",
    a: "All of a sudden, the lights went out.",
    b: "The lights went out ( ).",
    choices: ["suddenly", "gradually", "privately", "carefully"],
    answer: "suddenly",
    ja: "突然、明かりが消えた。",
    note: "all of a sudden = suddenly（突然に）\n選択肢:\nsuddenly = 突然\ngradually = 徐々に\nprivately = ひそかに\ncarefully = 注意深く",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_012",
    sourceId: "IM029",
    a: "In spite of the heavy rain, the game continued.",
    b: "( ) the heavy rain, the game continued.",
    choices: ["Despite", "During", "Beyond", "Around"],
    answer: "Despite",
    ja: "激しい雨にもかかわらず、その試合は続けられた。",
    note: "in spite of = despite（〜にもかかわらず）\n選択肢:\nDespite = 〜にもかかわらず\nDuring = 〜の間に\nBeyond = 〜を越えて\nAround = 〜の周りに / およそ",
    tags: ["前置詞表現", "逆接"]
  },
  {
    id: "P1_013",
    sourceId: "IM039",
    a: "You are supposed to wear a helmet here.",
    b: "You ( ) wear a helmet here.",
    choices: ["should", "can", "may", "will"],
    answer: "should",
    ja: "ここではヘルメットを着用すべきです。",
    note: "be supposed to = should（〜することになっている / 〜すべきだ）\n選択肢:\nshould = 〜すべきだ\ncan = 〜できる\nmay = 〜してもよい / 〜かもしれない\nwill = 〜するだろう",
    tags: ["構文言い換え", "助動詞"]
  },
  {
    id: "P1_014",
    sourceId: "IM018",
    a: "The school carried out a new safety policy this year.",
    b: "The school ( ) a new safety policy this year.",
    choices: ["implemented", "announced", "repeated", "questioned"],
    answer: "implemented",
    ja: "その学校は今年、新しい安全方針を実施した。",
    note: "carry out = implement（〜を実施する）\n選択肢:\nimplemented = 実施した\nannounced = 発表した\nrepeated = 繰り返した\nquestioned = 疑問視した / 質問した",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_015",
    sourceId: "IM052",
    a: "We need to get rid of these old files.",
    b: "We need to ( ) these old files.",
    choices: ["remove", "review", "arrange", "borrow"],
    answer: "remove",
    ja: "私たちはこれらの古いファイルを処分する必要がある。",
    note: "get rid of = remove（〜を取り除く / 処分する）\n選択肢:\nremove = 取り除く\nreview = 見直す\narrange = 整える / 手配する\nborrow = 借りる",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_016",
    sourceId: "IM054",
    a: "She finally made up her mind to study abroad.",
    b: "She finally ( ) to study abroad.",
    choices: ["decided", "pretended", "refused", "managed"],
    answer: "decided",
    ja: "彼女はついに留学する決心をした。",
    note: "make up one's mind = decide（決心する）\n選択肢:\ndecided = 決めた\npretended = ふりをした\nrefused = 断った\nmanaged = なんとかやり遂げた",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_017",
    sourceId: "IM051",
    a: "I can't put up with this noise any longer.",
    b: "I can't ( ) this noise any longer.",
    choices: ["tolerate", "ignore", "organize", "deserve"],
    answer: "tolerate",
    ja: "私はもうこの騒音に我慢できない。",
    note: "put up with = tolerate（〜を我慢する）\n選択肢:\ntolerate = 我慢する\nignore = 無視する\norganize = 整理する / 組織する\ndeserve = 〜に値する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_018",
    sourceId: "IM086",
    a: "The meeting will take place next Monday.",
    b: "The meeting will ( ) next Monday.",
    choices: ["happen", "continue", "recover", "settle"],
    answer: "happen",
    ja: "その会議は次の月曜日に行われる。",
    note: "take place = happen（起こる / 行われる）\n選択肢:\nhappen = 起こる\ncontinue = 続く\nrecover = 回復する\nsettle = 落ち着く / 解決する",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_019",
    sourceId: "IM087",
    a: "The company set up a branch office in Osaka.",
    b: "The company ( ) a branch office in Osaka.",
    choices: ["established", "borrowed", "expanded", "examined"],
    answer: "established",
    ja: "その会社は大阪に支店を設立した。",
    note: "set up = establish（〜を設立する）\n選択肢:\nestablished = 設立した\nborrowed = 借りた\nexpanded = 拡大した\nexamined = 調べた",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_020",
    sourceId: "IM093",
    a: "We will use this room for the time being.",
    b: "We will use this room ( ).",
    choices: ["for now", "at once", "by accident", "at least"],
    answer: "for now",
    ja: "私たちは当分の間この部屋を使う。",
    note: "for the time being = for now（当分の間）\n選択肢:\nfor now = 今のところ / 当分の間\nat once = すぐに\nby accident = 偶然に\nat least = 少なくとも",
    tags: ["定型表現", "副詞句"]
  },

      {
    id: "P1_021",
    sourceId: "IM014",
    a: "The game was canceled due to heavy snow.",
    b: "The game was canceled ( ) heavy snow.",
    choices: ["because of", "instead of", "in spite of", "along with"],
    answer: "because of",
    ja: "大雪のため、その試合は中止になった。",
    note: "due to = because of（〜が理由で / 〜のために）\n選択肢:\nbecause of = 〜のために\ninstead of = 〜の代わりに\nin spite of = 〜にもかかわらず\nalong with = 〜と一緒に",
    tags: ["原因表現", "前置詞句"]
  },
  {
    id: "P1_022",
    sourceId: "IM016",
    a: "She turned down the offer from the company.",
    b: "She ( ) the offer from the company.",
    choices: ["rejected", "accepted", "reviewed", "repeated"],
    answer: "rejected",
    ja: "彼女はその会社からの申し出を断った。",
    note: "turn down = reject（〜を断る）\n選択肢:\nrejected = 断った\naccepted = 受け入れた\nreviewed = 見直した / 再検討した\nrepeated = 繰り返した",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_023",
    sourceId: "IM017",
    a: "You should cut down on sugar.",
    b: "You should ( ) the amount of sugar you eat.",
    choices: ["reduce", "increase", "measure", "imagine"],
    answer: "reduce",
    ja: "砂糖を減らしたほうがよい。",
    note: "cut down on = reduce（〜を減らす）\n選択肢:\nreduce = 減らす\nincrease = 増やす\nmeasure = 測る\nimagine = 想像する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_024",
    sourceId: "IM021",
    a: "She went through many difficulties in her childhood.",
    b: "She ( ) many difficulties in her childhood.",
    choices: ["experienced", "avoided", "prevented", "collected"],
    answer: "experienced",
    ja: "彼女は子ども時代に多くの困難を経験した。",
    note: "go through = experience（〜を経験する）\n選択肢:\nexperienced = 経験した\navoided = 避けた\nprevented = 防いだ\ncollected = 集めた",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_025",
    sourceId: "IM022",
    a: "I have confidence in his ability.",
    b: "I ( ) his ability.",
    choices: ["trust", "doubt", "replace", "observe"],
    answer: "trust",
    ja: "私は彼の能力を信頼している。",
    note: "have confidence in = trust（〜を信頼する）\n選択肢:\ntrust = 信頼する\ndoubt = 疑う\nreplace = 取り替える\nobserve = 観察する",
    tags: ["名詞句→1語", "動詞"]
  },
  {
    id: "P1_026",
    sourceId: "IM023",
    a: "Most citizens are in favor of the new rule.",
    b: "Most citizens ( ) the new rule.",
    choices: ["support", "oppose", "ignore", "measure"],
    answer: "support",
    ja: "たいていの市民はその新しい規則に賛成している。",
    note: "be in favor of = support（〜に賛成する）\n選択肢:\nsupport = 支持する / 賛成する\noppose = 反対する\nignore = 無視する\nmeasure = 測る",
    tags: ["句→1語", "動詞"]
  },
  {
    id: "P1_027",
    sourceId: "IM026",
    a: "Who will take care of the children tonight?",
    b: "Who will ( ) the children tonight?",
    choices: ["look after", "look into", "look for", "look over"],
    answer: "look after",
    ja: "今夜は誰が子どもたちの世話をしますか。",
    note: "take care of = look after（〜の世話をする）\n選択肢:\nlook after = 〜の世話をする\nlook into = 〜を調べる\nlook for = 〜を探す\nlook over = 〜にざっと目を通す",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_028",
    sourceId: "IM027",
    a: "We ran out of milk this morning.",
    b: "We ( ) milk this morning.",
    choices: ["used up", "kept off", "took over", "brought back"],
    answer: "used up",
    ja: "今朝、牛乳を使い切ってしまった。",
    note: "run out of = use up（〜を使い切る）\n選択肢:\nused up = 使い切った\nkept off = 〜を近づけなかった / 避けた\ntook over = 引き継いだ\nbrought back = 持ち帰った / 思い出させた",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_029",
    sourceId: "IM028",
    a: "The hospital is short of nurses.",
    b: "The hospital ( ) nurses.",
    choices: ["lacks", "employs", "invites", "trains"],
    answer: "lacks",
    ja: "その病院は看護師が不足している。",
    note: "be short of = lack（〜が不足している）\n選択肢:\nlacks = 不足している\nemploys = 雇っている\ninvites = 招待する\ntrains = 訓練する",
    tags: ["句→1語", "動詞"]
  },
  {
    id: "P1_030",
    sourceId: "IM032",
    a: "We visit our grandparents from time to time.",
    b: "We ( ) visit our grandparents.",
    choices: ["occasionally", "regularly", "carefully", "rarely"],
    answer: "occasionally",
    ja: "私たちは時々祖父母を訪ねる。",
    note: "from time to time = occasionally（時々）\n選択肢:\noccasionally = 時々\nregularly = 定期的に / いつも\ncarefully = 注意深く\nrarely = めったに〜ない",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_031",
    sourceId: "IM033",
    a: "I broke the cup by accident.",
    b: "I broke the cup ( ).",
    choices: ["accidentally", "purposely", "politely", "carelessly"],
    answer: "accidentally",
    ja: "私はうっかりそのカップを割ってしまった。",
    note: "by accident = accidentally（偶然に / うっかり）\n選択肢:\naccidentally = 偶然に / うっかり\npurposely = わざと\npolitely = 礼儀正しく\ncarelessly = 不注意に",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_032",
    sourceId: "IM034",
    a: "He left the room on purpose.",
    b: "He ( ) left the room.",
    choices: ["intentionally", "quietly", "smoothly", "immediately"],
    answer: "intentionally",
    ja: "彼はわざと部屋を出た。",
    note: "on purpose = intentionally（故意に / わざと）\n選択肢:\nintentionally = わざと\nquietly = 静かに\nsmoothly = 円滑に\nimmediately = すぐに",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_033",
    sourceId: "IM035",
    a: "In the end, they accepted our idea.",
    b: "( ), they accepted our idea.",
    choices: ["Finally", "Usually", "Instead", "Besides"],
    answer: "Finally",
    ja: "結局、彼らは私たちの考えを受け入れた。",
    note: "in the end = finally（結局 / 最後には）\n選択肢:\nFinally = 結局 / 最後に\nUsually = たいてい\nInstead = その代わりに\nBesides = そのうえ / 〜に加えて",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_034",
    sourceId: "IM036",
    a: "He chose tea instead of coffee.",
    b: "He chose tea ( ) coffee.",
    choices: ["rather than", "because of", "according to", "in case of"],
    answer: "rather than",
    ja: "彼はコーヒーではなく紅茶を選んだ。",
    note: "instead of = rather than（〜ではなく）\n選択肢:\nrather than = 〜ではなく\nbecause of = 〜のために\naccording to = 〜によれば\nin case of = 〜の場合には",
    tags: ["接続表現", "比較"]
  },
  {
    id: "P1_035",
    sourceId: "IM041",
    a: "She is eager to learn new skills.",
    b: "She is ( ) to learn new skills.",
    choices: ["keen", "ready", "afraid", "unable"],
    answer: "keen",
    ja: "彼女は新しい技能を学びたがっている。",
    note: "be eager to = be keen to（〜したがっている）\n選択肢:\nkeen = 熱心な / 〜したがっている\nready = 準備ができている\nafraid = 怖がって / 心配して\nunable = できない",
    tags: ["形容詞句言い換え", "形容詞"]
  },
  {
    id: "P1_036",
    sourceId: "IM043",
    a: "I still keep in touch with my host family.",
    b: "I still ( ) with my host family.",
    choices: ["stay in contact", "get in trouble", "come to terms", "fall in line"],
    answer: "stay in contact",
    ja: "私は今でもホストファミリーと連絡を取り合っている。",
    note: "keep in touch with = stay in contact with（〜と連絡を取り続ける）\n選択肢:\nstay in contact = 連絡を取り続ける\nget in trouble = 困ったことになる\ncome to terms = 折り合いをつける\nfall in line = 従う / 列に並ぶ",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_037",
    sourceId: "IM045",
    a: "His explanation makes sense.",
    b: "His explanation is ( ).",
    choices: ["understandable", "reasonable", "available", "avoidable"],
    answer: "understandable",
    ja: "彼の説明は筋が通っている。",
    note: "make sense = be understandable（理解できる / 筋が通っている）\n選択肢:\nunderstandable = 理解できる\nreasonable = 妥当な\navailable = 利用できる\navoidable = 避けられる",
    tags: ["熟語→形容詞化", "形容詞"]
  },
  {
    id: "P1_038",
    sourceId: "IM046",
    a: "My opinion is different from yours.",
    b: "My opinion ( ) yours.",
    choices: ["differs from", "agrees with", "results from", "belongs to"],
    answer: "differs from",
    ja: "私の意見はあなたの意見と異なる。",
    note: "be different from = differ from（〜と異なる）\n選択肢:\ndiffers from = 〜と異なる\nagrees with = 〜と一致する / 〜に賛成する\nresults from = 〜から生じる\nbelongs to = 〜に属する",
    tags: ["句⇄動詞", "動詞句"]
  },
  {
    id: "P1_039",
    sourceId: "IM049",
    a: "This book is worth reading.",
    b: "It is ( ) to read this book.",
    choices: ["worthwhile", "reasonable", "ordinary", "careless"],
    answer: "worthwhile",
    ja: "この本は読む価値がある。",
    note: "be worth doing = it is worthwhile to do（〜する価値がある）\n選択肢:\nworthwhile = 価値がある\nreasonable = 合理的な\nordinary = 普通の\ncareless = 不注意な",
    tags: ["構文言い換え", "形容詞"]
  },
  {
    id: "P1_040",
    sourceId: "IM053",
    a: "I will get in touch with you next week.",
    b: "I will ( ) you next week.",
    choices: ["contact", "ignore", "compare", "collect"],
    answer: "contact",
    ja: "来週あなたに連絡します。",
    note: "get in touch with = contact（〜に連絡する）\n選択肢:\ncontact = 連絡する\nignore = 無視する\ncompare = 比較する\ncollect = 集める",
    tags: ["熟語→1語", "動詞"]
  },

      {
    id: "P1_041",
    sourceId: "IM058",
    a: "Many parents are concerned about their children's safety.",
    b: "Many parents ( ) their children's safety.",
    choices: ["worry about", "laugh at", "wait for", "depend on"],
    answer: "worry about",
    ja: "多くの親は子どもの安全を心配している。",
    note: "be concerned about = worry about（〜を心配する）\n選択肢:\nworry about = 〜を心配する\nlaugh at = 〜を笑う / からかう\nwait for = 〜を待つ\ndepend on = 〜に頼る",
    tags: ["形容詞句言い換え", "動詞句"]
  },
  {
    id: "P1_042",
    sourceId: "IM059",
    a: "She is satisfied with the result of the experiment.",
    b: "She is ( ) the result of the experiment.",
    choices: ["content with", "different from", "famous for", "ready for"],
    answer: "content with",
    ja: "彼女はその実験結果に満足している。",
    note: "be satisfied with = be content with（〜に満足している）\n選択肢:\ncontent with = 〜に満足している\ndifferent from = 〜と異なる\nfamous for = 〜で有名である\nready for = 〜の準備ができている",
    tags: ["形容詞句言い換え", "形容詞句"]
  },
  {
    id: "P1_043",
    sourceId: "IM060",
    a: "It is wrong to make fun of others.",
    b: "It is wrong to ( ) others.",
    choices: ["laugh at", "depend on", "suffer from", "prepare for"],
    answer: "laugh at",
    ja: "他人をからかうのはよくない。",
    note: "make fun of = laugh at（〜をからかう）\n選択肢:\nlaugh at = 〜を笑う / からかう\ndepend on = 〜に頼る\nsuffer from = 〜に苦しむ\nprepare for = 〜に備える",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_044",
    sourceId: "IM062",
    a: "Kyoto is known for its beautiful temples.",
    b: "Kyoto is ( ) its beautiful temples.",
    choices: ["famous for", "busy with", "short of", "close to"],
    answer: "famous for",
    ja: "京都は美しい寺院で知られている。",
    note: "be known for = be famous for（〜で知られている）\n選択肢:\nfamous for = 〜で有名である\nbusy with = 〜で忙しい\nshort of = 〜が不足している\nclose to = 〜に近い",
    tags: ["形容詞句言い換え", "形容詞句"]
  },
  {
    id: "P1_045",
    sourceId: "IM063",
    a: "I am familiar with this software.",
    b: "I ( ) this software well.",
    choices: ["know", "build", "notice", "change"],
    answer: "know",
    ja: "私はこのソフトをよく知っている。",
    note: "be familiar with = know well（〜をよく知っている）\n選択肢:\nknow = 知っている\nbuild = 作る\nnotice = 気づく\nchange = 変える",
    tags: ["形容詞句→説明型", "動詞"]
  },
  {
    id: "P1_046",
    sourceId: "IM066",
    a: "What does this sign stand for?",
    b: "What does this sign ( )?",
    choices: ["represent", "prevent", "invent", "protect"],
    answer: "represent",
    ja: "この標識は何を表していますか。",
    note: "stand for = represent（〜を表す）\n選択肢:\nrepresent = 表す\nprevent = 防ぐ\ninvent = 発明する\nprotect = 守る",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_047",
    sourceId: "IM067",
    a: "Emily takes after her mother.",
    b: "Emily ( ) her mother.",
    choices: ["resembles", "supports", "greets", "follows"],
    answer: "resembles",
    ja: "エミリーは母親に似ている。",
    note: "take after = resemble（〜に似ている）\n選択肢:\nresembles = 〜に似ている\nsupports = 支える / 支持する\ngreets = あいさつする\nfollows = 後について行く / 従う",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_048",
    sourceId: "IM068",
    a: "He is accustomed to getting up early.",
    b: "He is ( ) getting up early.",
    choices: ["used to", "known for", "opposed to", "interested in"],
    answer: "used to",
    ja: "彼は早起きすることに慣れている。",
    note: "be accustomed to = be used to（〜に慣れている）\n選択肢:\nused to = 〜に慣れている\nknown for = 〜で知られている\nopposed to = 〜に反対している\ninterested in = 〜に興味がある",
    tags: ["形容詞句言い換え", "形容詞句"]
  },
  {
    id: "P1_049",
    sourceId: "IM069",
    a: "Some students have difficulty in speaking in public.",
    b: "Some students ( ) speak in public.",
    choices: ["find it hard to", "plan to", "hope to", "agree to"],
    answer: "find it hard to",
    ja: "人前で話すのが苦手な生徒もいる。",
    note: "have difficulty in doing = find it hard to do（〜するのが難しい）\n選択肢:\nfind it hard to = 〜するのが難しい\nplan to = 〜するつもりである\nhope to = 〜したいと思う\nagree to = 〜することに同意する",
    tags: ["構文言い換え", "不定詞"]
  },
  {
    id: "P1_050",
    sourceId: "IM071",
    a: "Poor eating habits can contribute to health problems.",
    b: "Poor eating habits can ( ) health problems.",
    choices: ["help cause", "set aside", "keep off", "look over"],
    answer: "help cause",
    ja: "悪い食習慣は健康問題の一因になりうる。",
    note: "contribute to = help cause（〜の一因となる）\n選択肢:\nhelp cause = 引き起こす一因となる\nset aside = 取っておく / 脇に置く\nkeep off = 近づかない / 避ける\nlook over = ざっと目を通す",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_051",
    sourceId: "IM072",
    a: "Lack of money got in the way of the project.",
    b: "Lack of money ( ) the project.",
    choices: ["obstructed", "encouraged", "celebrated", "explained"],
    answer: "obstructed",
    ja: "資金不足がその計画の妨げになった。",
    note: "get in the way of = obstruct（〜の妨げになる）\n選択肢:\nobstructed = 妨げた\nencouraged = 励ました / 促した\ncelebrated = 祝った\nexplained = 説明した",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_052",
    sourceId: "IM073",
    a: "In other words, we need more time.",
    b: "( ), we need more time.",
    choices: ["That is to say", "At first", "By accident", "For now"],
    answer: "That is to say",
    ja: "言い換えれば、私たちにはもっと時間が必要だ。",
    note: "in other words = that is to say（言い換えれば）\n選択肢:\nThat is to say = 言い換えれば\nAt first = 最初は\nBy accident = 偶然に\nFor now = 今のところ",
    tags: ["定型表現", "言い換え"]
  },
  {
    id: "P1_053",
    sourceId: "IM074",
    a: "For instance, you can start with this easy task.",
    b: "( ), you can start with this easy task.",
    choices: ["For example", "At last", "In contrast", "As usual"],
    answer: "For example",
    ja: "例えば、この簡単な作業から始められます。",
    note: "for instance = for example（例えば）\n選択肢:\nFor example = 例えば\nAt last = ついに\nIn contrast = それとは対照的に\nAs usual = いつものように",
    tags: ["定型表現", "副詞句"]
  },
  {
    id: "P1_054",
    sourceId: "IM076",
    a: "She gave me a gift in return for my help.",
    b: "She gave me a gift ( ) my help.",
    choices: ["in exchange for", "in place of", "because of", "in front of"],
    answer: "in exchange for",
    ja: "彼女は私の手伝いのお返しに贈り物をくれた。",
    note: "in return for = in exchange for（〜のお返しに）\n選択肢:\nin exchange for = 〜と引き換えに / お返しに\nin place of = 〜の代わりに\nbecause of = 〜のために\nin front of = 〜の前で",
    tags: ["前置詞表現", "句"]
  },
  {
    id: "P1_055",
    sourceId: "IM078",
    a: "His research is closely related to climate change.",
    b: "His research is closely ( ) climate change.",
    choices: ["connected with", "divided by", "hidden from", "crowded with"],
    answer: "connected with",
    ja: "彼の研究は気候変動と密接に関連している。",
    note: "be related to = be connected with（〜に関連している）\n選択肢:\nconnected with = 〜と関連している\ndivided by = 〜で分けられている\nhidden from = 〜から隠されている\ncrowded with = 〜で混み合っている",
    tags: ["形容詞句言い換え", "形容詞句"]
  },
  {
    id: "P1_056",
    sourceId: "IM080",
    a: "Young children have a tendency to ask many questions.",
    b: "Young children ( ) ask many questions.",
    choices: ["tend to", "refuse to", "agree to", "pretend to"],
    answer: "tend to",
    ja: "幼い子どもは多くの質問をする傾向がある。",
    note: "have a tendency to = tend to（〜する傾向がある）\n選択肢:\ntend to = 〜する傾向がある\nrefuse to = 〜するのを拒む\nagree to = 〜することに同意する\npretend to = 〜するふりをする",
    tags: ["構文言い換え", "動詞句"]
  },
  {
    id: "P1_057",
    sourceId: "IM081",
    a: "The school decided to do away with the old rule.",
    b: "The school decided to ( ) the old rule.",
    choices: ["abolish", "correct", "revise", "examine"],
    answer: "abolish",
    ja: "その学校は古い規則を廃止することにした。",
    note: "do away with = abolish（〜を廃止する）\n選択肢:\nabolish = 廃止する\ncorrect = 訂正する\nrevise = 修正する / 改訂する\nexamine = 調べる",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_058",
    sourceId: "IM082",
    a: "I will make up for the lost time.",
    b: "I will ( ) the lost time.",
    choices: ["compensate for", "look after", "get over", "call off"],
    answer: "compensate for",
    ja: "私は失った時間を埋め合わせるつもりだ。",
    note: "make up for = compensate for（〜を埋め合わせる）\n選択肢:\ncompensate for = 〜を埋め合わせる\nlook after = 〜の世話をする\nget over = 〜を乗り越える / 回復する\ncall off = 〜を中止する",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_059",
    sourceId: "IM083",
    a: "We had no choice but to stay home.",
    b: "We were ( ) stay home.",
    choices: ["forced to", "ready to", "pleased to", "proud to"],
    answer: "forced to",
    ja: "私たちは家にいるしかなかった。",
    note: "have no choice but to = be forced to（〜するしかない）\n選択肢:\nforced to = 〜せざるを得ない\nready to = 〜する準備ができている\npleased to = 〜してうれしい\nproud to = 〜して誇りに思う",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_060",
    sourceId: "IM088",
    a: "You should not look down on others.",
    b: "You should not ( ) others.",
    choices: ["despise", "forgive", "support", "contact"],
    answer: "despise",
    ja: "他人を見下してはいけない。",
    note: "look down on = despise（〜を見下す）\n選択肢:\ndespise = 見下す / 軽蔑する\nforgive = 許す\nsupport = 支える / 支持する\ncontact = 連絡する",
    tags: ["句動詞→1語", "動詞"]
  },
    {
    id: "P1_061",
    sourceId: "IM089",
    a: "They finally consented to our proposal.",
    b: "They finally ( ) our proposal.",
    choices: ["agreed to", "looked into", "suffered from", "waited for"],
    answer: "agreed to",
    ja: "彼らはついに私たちの提案に同意した。",
    note: "consent to = agree to（〜に同意する）\n選択肢:\nagreed to = 〜に同意した\nlooked into = 〜を調べた\nsuffered from = 〜に苦しんだ\nwaited for = 〜を待った",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_062",
    sourceId: "IM091",
    a: "The train is on the point of leaving.",
    b: "The train is ( ) leave.",
    choices: ["about to", "likely to", "willing to", "afraid to"],
    answer: "about to",
    ja: "その電車は今にも出発しようとしている。",
    note: "be on the point of doing = be about to do（まさに〜しようとしている）\n選択肢:\nabout to = まさに〜しようとして\nlikely to = 〜しそうで\nwilling to = 〜する気があって\nafraid to = 〜するのをこわがって",
    tags: ["構文言い換え", "不定詞"]
  },
  {
    id: "P1_063",
    sourceId: "IM092",
    a: "Please let me know in advance if you cannot come.",
    b: "Please let me know ( ) if you cannot come.",
    choices: ["beforehand", "directly", "everywhere", "upstairs"],
    answer: "beforehand",
    ja: "来られない場合は前もって知らせてください。",
    note: "in advance = beforehand（前もって）\n選択肢:\nbeforehand = 前もって\ndirectly = 直接 / すぐに\neverywhere = どこでも\nupstairs = 階上で / 2階へ",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_064",
    sourceId: "IM094",
    a: "At present, the library is closed.",
    b: "( ), the library is closed.",
    choices: ["Currently", "Recently", "Rarely", "Personally"],
    answer: "Currently",
    ja: "現在、その図書館は閉まっている。",
    note: "at present = currently（現在は）\n選択肢:\nCurrently = 現在は\nRecently = 最近\nRarely = めったに〜ない\nPersonally = 個人的には",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_065",
    sourceId: "IM095",
    a: "She solved the puzzle with ease.",
    b: "She solved the puzzle ( ).",
    choices: ["easily", "closely", "gently", "widely"],
    answer: "easily",
    ja: "彼女はそのパズルを簡単に解いた。",
    note: "with ease = easily（容易に）\n選択肢:\neasily = 簡単に\nclosely = 綿密に / 近くで\ngently = やさしく\nwidely = 広く",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_066",
    sourceId: "IM096",
    a: "They searched for the missing dog in vain.",
    b: "They searched for the missing dog ( ).",
    choices: ["without success", "with pleasure", "for practice", "at night"],
    answer: "without success",
    ja: "彼らはその行方不明の犬を探したがむだだった。",
    note: "in vain = without success（むだに / 成果なく）\n選択肢:\nwithout success = 成功せずに\nwith pleasure = 喜んで\nfor practice = 練習のために\nat night = 夜に",
    tags: ["定型表現", "句"]
  },
  {
    id: "P1_067",
    sourceId: "IM097",
    a: "Regardless of age, anyone can join the class.",
    b: "( ) age, anyone can join the class.",
    choices: ["Despite", "Beyond", "Among", "Inside"],
    answer: "Despite",
    ja: "年齢に関係なく、誰でもその講座に参加できる。",
    note: "regardless of = despite（〜に関係なく / 〜にもかかわらず）\n選択肢:\nDespite = 〜にもかかわらず / 〜に関係なく\nBeyond = 〜を越えて\nAmong = 〜の間で\nInside = 〜の中に",
    tags: ["前置詞表現", "前置詞"]
  },
  {
    id: "P1_068",
    sourceId: "IM099",
    a: "This vending machine is out of order.",
    b: "This vending machine is ( ).",
    choices: ["not working", "well known", "far away", "fully open"],
    answer: "not working",
    ja: "この自動販売機は故障している。",
    note: "out of order = not working（故障している）\n選択肢:\nnot working = 動いていない / 故障している\nwell known = よく知られている\nfar away = 遠くにある\nfully open = 全開で / 完全に開いている",
    tags: ["状態表現", "説明型"]
  },
  {
    id: "P1_069",
    sourceId: "IM100",
    a: "It is hard to keep up with rapid changes in technology.",
    b: "It is hard to ( ) rapid changes in technology.",
    choices: ["stay at the same level as", "take place in", "look down on", "run out of"],
    answer: "stay at the same level as",
    ja: "技術の急速な変化についていくのは難しい。",
    note: "keep up with = stay at the same level as（〜に遅れずについていく）\n選択肢:\nstay at the same level as = 〜に遅れずついていく\ntake place in = 〜で起こる\nlook down on = 〜を見下す\nrun out of = 〜を使い果たす",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_070",
    sourceId: "IM101",
    a: "She came up with a great idea for the project.",
    b: "She ( ) a great idea for the project.",
    choices: ["thought of", "gave up", "turned off", "brought back"],
    answer: "thought of",
    ja: "彼女はその計画のためのすばらしい案を思いついた。",
    note: "come up with = think of（〜を思いつく）\n選択肢:\nthought of = 思いついた\ngave up = あきらめた\nturned off = 消した / 興味を失わせた\nbrought back = 持ち帰った / 思い出させた",
    tags: ["句動詞→説明型", "動詞句"]
  },
  {
    id: "P1_071",
    sourceId: "IM102",
    a: "You can leave out the last question.",
    b: "You can ( ) the last question.",
    choices: ["omit", "notice", "invite", "attach"],
    answer: "omit",
    ja: "最後の質問は省いてよい。",
    note: "leave out = omit（〜を省く）\n選択肢:\nomit = 省く\nnotice = 気づく\ninvite = 招待する\nattach = 付ける",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_072",
    sourceId: "IM103",
    a: "I couldn't make sense of his explanation.",
    b: "I couldn't ( ) his explanation.",
    choices: ["understand", "decorate", "predict", "replace"],
    answer: "understand",
    ja: "私は彼の説明を理解できなかった。",
    note: "make sense of = understand（〜を理解する）\n選択肢:\nunderstand = 理解する\ndecorate = 飾る\npredict = 予測する\nreplace = 取り替える",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_073",
    sourceId: "IM104",
    a: "You should refrain from using your phone during class.",
    b: "You should ( ) using your phone during class.",
    choices: ["avoid", "consider", "finish", "admit"],
    answer: "avoid",
    ja: "授業中に携帯電話を使うのは控えるべきだ。",
    note: "refrain from = avoid（〜を控える / 避ける）\n選択肢:\navoid = 避ける\nconsider = 検討する\nfinish = 終える\nadmit = 認める",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_074",
    sourceId: "IM105",
    a: "How do you cope with stress at work?",
    b: "How do you ( ) stress at work?",
    choices: ["deal with", "break into", "run across", "turn over"],
    answer: "deal with",
    ja: "仕事上のストレスにどう対処していますか。",
    note: "cope with = deal with（〜に対処する）\n選択肢:\ndeal with = 〜に対処する\nbreak into = 〜に侵入する\nrun across = 〜に偶然出会う\nturn over = ひっくり返す / 引き渡す",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_075",
    sourceId: "IM106",
    a: "She is bound to succeed.",
    b: "She is ( ) succeed.",
    choices: ["certain to", "late to", "afraid to", "unable to"],
    answer: "certain to",
    ja: "彼女はきっと成功する。",
    note: "be bound to = be certain to（きっと〜する）\n選択肢:\ncertain to = きっと〜する\nlate to = 〜するには遅れて\nafraid to = 〜するのをこわがって\nunable to = 〜できなくて",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_076",
    sourceId: "IM107",
    a: "Every citizen is entitled to vote.",
    b: "Every citizen ( ) vote.",
    choices: ["has the right to", "is willing to", "is likely to", "has to"],
    answer: "has the right to",
    ja: "すべての市民には投票する権利がある。",
    note: "be entitled to = have the right to（〜する権利がある）\n選択肢:\nhas the right to = 〜する権利がある\nis willing to = 〜する気がある\nis likely to = 〜しそうだ\nhas to = 〜しなければならない",
    tags: ["形容詞句→説明型", "権利"]
  },
  {
    id: "P1_077",
    sourceId: "IM111",
    a: "It is not easy for them to make ends meet.",
    b: "It is not easy for them to ( ).",
    choices: ["have enough money to live", "look for new jobs", "share their opinions", "improve their grades"],
    answer: "have enough money to live",
    ja: "彼らがどうにか生活していくのは簡単ではない。",
    note: "make ends meet = have enough money to live（どうにかやりくりする）\n選択肢:\nhave enough money to live = 生活できるだけのお金がある\nlook for new jobs = 新しい仕事を探す\nshare their opinions = 意見を共有する\nimprove their grades = 成績を上げる",
    tags: ["熟語→説明型", "生活"]
  },
  {
    id: "P1_078",
    sourceId: "IM113",
    a: "It is rude to speak ill of others.",
    b: "It is rude to ( ) others.",
    choices: ["criticize", "forgive", "support", "observe"],
    answer: "criticize",
    ja: "他人の悪口を言うのは失礼だ。",
    note: "speak ill of = criticize（〜の悪口を言う / 批判する）\n選択肢:\ncriticize = 批判する\nforgive = 許す\nsupport = 支持する / 支える\nobserve = 観察する",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_079",
    sourceId: "IM114",
    a: "You should take cost into consideration.",
    b: "You should ( ) cost.",
    choices: ["consider", "ignore", "demand", "increase"],
    answer: "consider",
    ja: "費用を考慮に入れるべきだ。",
    note: "take A into consideration = consider A（Aを考慮に入れる）\n選択肢:\nconsider = 考慮する\nignore = 無視する\ndemand = 要求する\nincrease = 増やす",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_080",
    sourceId: "IM120",
    a: "Sooner or later, people will notice the problem.",
    b: "( ), people will notice the problem.",
    choices: ["Eventually", "Actually", "Recently", "Silently"],
    answer: "Eventually",
    ja: "遅かれ早かれ、人々はその問題に気づくだろう。",
    note: "sooner or later = eventually（遅かれ早かれ / 結局）\n選択肢:\nEventually = 結局 / やがて\nActually = 実際には\nRecently = 最近\nSilently = 黙って / 静かに",
    tags: ["副詞化", "副詞"]
  },

      {
    id: "P1_081",
    sourceId: "IM121",
    a: "We are looking forward to your reply.",
    b: "We are eagerly ( ) your reply.",
    choices: ["awaiting", "avoiding", "ignoring", "sharing"],
    answer: "awaiting",
    ja: "私たちはあなたの返事を楽しみに待っています。",
    note: "look forward to = await（〜を楽しみに待つ）\n選択肢:\nawaiting = 待っている\navoiding = 避けている\nignoring = 無視している\nsharing = 共有している",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_082",
    sourceId: "IM122",
    a: "He did not show up for class today.",
    b: "He did not ( ) for class today.",
    choices: ["appear", "prepare", "return", "volunteer"],
    answer: "appear",
    ja: "彼は今日授業に現れなかった。",
    note: "show up = appear（現れる）\n選択肢:\nappear = 現れる\nprepare = 準備する\nreturn = 戻る\nvolunteer = 志願する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_083",
    sourceId: "IM123",
    a: "Please carry on with your work.",
    b: "Please ( ) with your work.",
    choices: ["continue", "compete", "agree", "struggle"],
    answer: "continue",
    ja: "どうぞ仕事を続けてください。",
    note: "carry on = continue（続ける）\n選択肢:\ncontinue = 続ける\ncompete = 競う\nagree = 同意する\nstruggle = もがく / 苦闘する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_084",
    sourceId: "IM125",
    a: "He made believe that he knew the answer.",
    b: "He ( ) to know the answer.",
    choices: ["pretended", "refused", "managed", "promised"],
    answer: "pretended",
    ja: "彼はその答えを知っているふりをした。",
    note: "make believe = pretend（ふりをする）\n選択肢:\npretended = ふりをした\nrefused = 断った\nmanaged = なんとかやり遂げた\npromised = 約束した",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_085",
    sourceId: "IM126",
    a: "Her grandparents brought her up in the countryside.",
    b: "Her grandparents ( ) her in the countryside.",
    choices: ["raised", "invited", "warned", "followed"],
    answer: "raised",
    ja: "祖父母が彼女を田舎で育てた。",
    note: "bring up = raise（〜を育てる）\n選択肢:\nraised = 育てた\ninvited = 招待した\nwarned = 警告した\nfollowed = 後について行った / 従った",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_086",
    sourceId: "IM127",
    a: "You should put aside some money each month.",
    b: "You should ( ) some money each month.",
    choices: ["save", "waste", "borrow", "spend"],
    answer: "save",
    ja: "毎月いくらかお金を取っておくべきだ。",
    note: "put aside = save（取っておく / 貯める）\n選択肢:\nsave = 貯める / 取っておく\nwaste = むだにする\nborrow = 借りる\nspend = 使う",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_087",
    sourceId: "IM128",
    a: "We should take advantage of this opportunity.",
    b: "We should ( ) this opportunity.",
    choices: ["make use of", "get away from", "put up with", "come up with"],
    answer: "make use of",
    ja: "私たちはこの機会を利用すべきだ。",
    note: "take advantage of = make use of（〜を利用する）\n選択肢:\nmake use of = 利用する\nget away from = 〜から離れる\nput up with = 〜を我慢する\ncome up with = 〜を思いつく",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_088",
    sourceId: "IM129",
    a: "She makes a point of checking her email every morning.",
    b: "She is ( ) check her email every morning.",
    choices: ["sure to", "afraid to", "unable to", "ready to"],
    answer: "sure to",
    ja: "彼女は毎朝必ずメールを確認するようにしている。",
    note: "make a point of doing = be sure to do（必ず〜するようにする）\n選択肢:\nsure to = 必ず〜する\nafraid to = 〜するのをこわがって\nunable to = 〜できなくて\nready to = 〜する準備ができて",
    tags: ["構文言い換え", "不定詞"]
  },
  {
    id: "P1_089",
    sourceId: "IM130",
    a: "He did his best to help the team.",
    b: "He ( ) to help the team.",
    choices: ["made every effort", "lost his temper", "kept his distance", "changed his mind"],
    answer: "made every effort",
    ja: "彼はチームを助けるために最善を尽くした。",
    note: "do one's best = make every effort（最善を尽くす）\n選択肢:\nmade every effort = あらゆる努力をした\nlost his temper = かっとなった\nkept his distance = 距離を置いた\nchanged his mind = 気が変わった",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_090",
    sourceId: "IM131",
    a: "Many companies attach importance to teamwork.",
    b: "Many companies ( ) teamwork.",
    choices: ["value", "delay", "forgive", "predict"],
    answer: "value",
    ja: "多くの会社はチームワークを重視している。",
    note: "attach importance to = value（〜を重視する）\n選択肢:\nvalue = 重視する / 価値を認める\ndelay = 遅らせる\nforgive = 許す\npredict = 予測する",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_091",
    sourceId: "IM132",
    a: "Our teacher put emphasis on clear pronunciation.",
    b: "Our teacher ( ) clear pronunciation.",
    choices: ["stressed", "replied to", "waited for", "commented on"],
    answer: "stressed",
    ja: "私たちの先生は明瞭な発音を強調した。",
    note: "put emphasis on = stress（〜を強調する）\n選択肢:\nstressed = 強調した\nreplied to = 〜に返答した\nwaited for = 〜を待った\ncommented on = 〜についてコメントした",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_092",
    sourceId: "IM133",
    a: "She was reluctant to speak in public.",
    b: "She ( ) speak in public.",
    choices: ["hesitated to", "preferred to", "promised to", "attempted to"],
    answer: "hesitated to",
    ja: "彼女は人前で話すのをためらった。",
    note: "be reluctant to = hesitate to（気が進まない / ためらう）\n選択肢:\nhesitated to = ためらった\npreferred to = むしろ〜したかった\npromised to = 〜すると約束した\nattempted to = 〜しようと試みた",
    tags: ["形容詞句言い換え", "不定詞"]
  },
  {
    id: "P1_093",
    sourceId: "IM134",
    a: "I have yet to finish the report.",
    b: "I have not finished the report ( ).",
    choices: ["yet", "already", "again", "instead"],
    answer: "yet",
    ja: "私はまだその報告書を仕上げていない。",
    note: "have yet to do = have not done ... yet（まだ〜していない）\n選択肢:\nyet = まだ\nalready = すでに\nagain = 再び\ninstead = その代わりに",
    tags: ["構文言い換え", "副詞"]
  },
  {
    id: "P1_094",
    sourceId: "IM135",
    a: "He cannot swim, let alone dive.",
    b: "He cannot swim, much ( ) dive.",
    choices: ["less", "more", "better", "rather"],
    answer: "less",
    ja: "彼は泳げないし、まして潜ることなどできない。",
    note: "let alone = much less（まして〜ない）\n選択肢:\nless = さらに少なく / まして〜ない\nmore = さらに多く\nbetter = よりよく\nrather = むしろ",
    tags: ["定型表現", "比較"]
  },
  {
    id: "P1_095",
    sourceId: "IM136",
    a: "The children fell asleep in no time.",
    b: "The children fell asleep very ( ).",
    choices: ["soon", "late", "hard", "close"],
    answer: "soon",
    ja: "子どもたちはすぐに眠ってしまった。",
    note: "in no time = very soon（すぐに）\n選択肢:\nsoon = すぐに\nlate = 遅く\nhard = 激しく / 一生懸命に\nclose = 近くに",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_096",
    sourceId: "IM137",
    a: "I will wash the dishes. In the meantime, please clean the table.",
    b: "I will wash the dishes. ( ), please clean the table.",
    choices: ["Meanwhile", "Therefore", "Instead", "Anyway"],
    answer: "Meanwhile",
    ja: "私が皿を洗う。その間に、テーブルをきれいにしてください。",
    note: "in the meantime = meanwhile（その間に）\n選択肢:\nMeanwhile = その間に\nTherefore = したがって\nInstead = その代わりに\nAnyway = とにかく",
    tags: ["副詞化", "副詞"]
  },
  {
    id: "P1_097",
    sourceId: "IM138",
    a: "The game was canceled owing to the weather.",
    b: "The game was canceled ( ) the weather.",
    choices: ["because of", "instead of", "according to", "along with"],
    answer: "because of",
    ja: "その試合は天候のため中止になった。",
    note: "owing to = because of（〜のために）\n選択肢:\nbecause of = 〜のために\ninstead of = 〜の代わりに\naccording to = 〜によれば\nalong with = 〜と一緒に",
    tags: ["原因表現", "前置詞句"]
  },
  {
    id: "P1_098",
    sourceId: "IM139",
    a: "They sent the message by means of satellite communication.",
    b: "They sent the message ( ) satellite communication.",
    choices: ["by using", "because of", "in spite of", "as for"],
    answer: "by using",
    ja: "彼らは衛星通信によってそのメッセージを送った。",
    note: "by means of = by using（〜によって）\n選択肢:\nby using = 〜を使って\nbecause of = 〜のために\nin spite of = 〜にもかかわらず\nas for = 〜については",
    tags: ["前置詞句→説明型", "手段"]
  },
  {
    id: "P1_099",
    sourceId: "IM140",
    a: "Under no circumstances should you open this box.",
    b: "You should ( ) open this box.",
    choices: ["never", "always", "probably", "still"],
    answer: "never",
    ja: "決してこの箱を開けてはいけない。",
    note: "under no circumstances = never（決して〜ない）\n選択肢:\nnever = 決して〜ない\nalways = いつも\nprobably = おそらく\nstill = まだ / それでも",
    tags: ["否定強調表現", "副詞"]
  },
  {
    id: "P1_100",
    sourceId: "IM141",
    a: "All students must comply with the school rules.",
    b: "All students must ( ) the school rules.",
    choices: ["obey", "ignore", "exchange", "judge"],
    answer: "obey",
    ja: "すべての生徒は校則に従わなければならない。",
    note: "comply with = obey（〜に従う）\n選択肢:\nobey = 従う\nignore = 無視する\nexchange = 交換する\njudge = 判断する",
    tags: ["熟語→1語", "動詞"]
  },

      {
    id: "P1_101",
    sourceId: "IM090",
    a: "When I have a problem, I turn to my teacher for help.",
    b: "When I have a problem, I ( ) my teacher.",
    choices: ["ask for help from", "make fun of", "keep away from", "run out of"],
    answer: "ask for help from",
    ja: "問題があるとき、私は先生に助けを求める。",
    note: "turn to A for help = ask A for help（Aに助けを求める）\n選択肢:\nask for help from = 〜に助けを求める\nmake fun of = 〜をからかう\nkeep away from = 〜から離れる\nrun out of = 〜を使い果たす",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_102",
    sourceId: "IM098",
    a: "The movie was far from interesting.",
    b: "The movie was not interesting at ( ).",
    choices: ["all", "first", "times", "home"],
    answer: "all",
    ja: "その映画は決して面白くなかった。",
    note: "far from = not ... at all（決して〜ない / まったく〜ない）\n選択肢:\nall = まったく（not ... at all で）\nfirst = 最初に\ntimes = 回数 / 時代\nhome = 家 / 故郷",
    tags: ["否定強調表現", "副詞句"]
  },
  {
    id: "P1_103",
    sourceId: "IM108",
    a: "She was on the verge of tears.",
    b: "She was ( ) crying.",
    choices: ["close to", "tired of", "free from", "proud of"],
    answer: "close to",
    ja: "彼女は今にも泣きそうだった。",
    note: "on the verge of = close to（今にも〜しそうで）\n選択肢:\nclose to = 〜しそうで / 〜に近くて\ntired of = 〜にうんざりして\nfree from = 〜から自由で\nproud of = 〜を誇りに思って",
    tags: ["前置詞句言い換え", "句"]
  },
  {
    id: "P1_104",
    sourceId: "IM109",
    a: "He learned many things in the course of the trip.",
    b: "He learned many things ( ) the trip.",
    choices: ["during", "beyond", "against", "inside"],
    answer: "during",
    ja: "彼はその旅行の間に多くのことを学んだ。",
    note: "in the course of = during（〜の間に）\n選択肢:\nduring = 〜の間に\nbeyond = 〜を越えて\nagainst = 〜に反して / 〜に向かって\ninside = 〜の中に",
    tags: ["前置詞表現", "前置詞"]
  },
  {
    id: "P1_105",
    sourceId: "IM110",
    a: "They built the new road at the expense of the forest.",
    b: "They built the new road ( ) the forest.",
    choices: ["by sacrificing", "in front of", "in place of", "along with"],
    answer: "by sacrificing",
    ja: "彼らは森を犠牲にして新しい道路を建設した。",
    note: "at the expense of = by sacrificing（〜を犠牲にして）\n選択肢:\nby sacrificing = 〜を犠牲にして\nin front of = 〜の前に\nin place of = 〜の代わりに\nalong with = 〜と一緒に",
    tags: ["前置詞句→説明型", "説明型"]
  },
  {
    id: "P1_106",
    sourceId: "IM112",
    a: "It is hard to keep track of all the changes.",
    b: "It is hard to ( ) all the changes.",
    choices: ["stay informed about", "take care of", "make use of", "keep away from"],
    answer: "stay informed about",
    ja: "すべての変化を追い続けるのは難しい。",
    note: "keep track of = stay informed about（〜の動向を追う / 把握し続ける）\n選択肢:\nstay informed about = 〜について把握し続ける\ntake care of = 〜の世話をする\nmake use of = 〜を利用する\nkeep away from = 〜から離れる",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_107",
    sourceId: "IM115",
    a: "The manager put pressure on us to finish early.",
    b: "The manager tried to ( ) us to finish early.",
    choices: ["urge", "thank", "follow", "protect"],
    answer: "urge",
    ja: "部長は私たちに早く終えるよう圧力をかけた。",
    note: "put pressure on = urge（〜に強く促す / 圧力をかける）\n選択肢:\nurge = 強く促す\nthank = 感謝する\nfollow = 従う / 後について行く\nprotect = 守る",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_108",
    sourceId: "IM116",
    a: "I was obliged to cancel the meeting.",
    b: "I was ( ) cancel the meeting.",
    choices: ["forced to", "glad to", "ready to", "free to"],
    answer: "forced to",
    ja: "私は会議を中止せざるを得なかった。",
    note: "be obliged to = be forced to（〜せざるを得ない）\n選択肢:\nforced to = 〜せざるを得なくて\nglad to = 〜してうれしくて\nready to = 〜する準備ができて\nfree to = 自由に〜できて",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_109",
    sourceId: "IM117",
    a: "The rumor turned out to be false.",
    b: "The rumor ( ) false.",
    choices: ["proved to be", "belonged to", "looked after", "turned over"],
    answer: "proved to be",
    ja: "そのうわさは誤りだとわかった。",
    note: "turn out to be = prove to be（〜であることがわかる）\n選択肢:\nproved to be = 〜であるとわかった\nbelonged to = 〜に属していた\nlooked after = 〜の世話をした\nturned over = ひっくり返した / 引き渡した",
    tags: ["構文言い換え", "動詞句"]
  },
  {
    id: "P1_110",
    sourceId: "IM118",
    a: "The hotel provides guests with free Wi-Fi.",
    b: "The hotel ( ) free Wi-Fi.",
    choices: ["gives guests", "charges guests for", "compares guests with", "warns guests about"],
    answer: "gives guests",
    ja: "そのホテルは宿泊客に無料Wi-Fiを提供している。",
    note: "provide A with B = give A B（AにBを与える / 提供する）\n選択肢:\ngives guests = 宿泊客に与える\ncharges guests for = 宿泊客に料金を請求する\ncompares guests with = 宿泊客を〜と比較する\nwarns guests about = 宿泊客に〜について警告する",
    tags: ["構文言い換え", "動詞句"]
  },
  {
    id: "P1_111",
    sourceId: "IM119",
    a: "The match was canceled for lack of players.",
    b: "The match was canceled because there were not ( ) players.",
    choices: ["enough", "available", "talented", "careful"],
    answer: "enough",
    ja: "選手不足のため、その試合は中止になった。",
    note: "for lack of = because there is not enough of（〜が不足しているため）\n選択肢:\nenough = 十分な\navailable = 利用できる / 手が空いている\ntalented = 才能のある\ncareful = 注意深い",
    tags: ["原因表現", "説明型"]
  },
  {
    id: "P1_112",
    sourceId: "IM142",
    a: "I was under the impression that she was a doctor.",
    b: "I ( ) she was a doctor.",
    choices: ["believed", "noticed", "promised", "admitted"],
    answer: "believed",
    ja: "私は彼女が医者だと思っていた。",
    note: "be under the impression that = believe that（〜だと思っている）\n選択肢:\nbelieved = 〜だと思った\nnoticed = 気づいた\npromised = 約束した\nadmitted = 認めた",
    tags: ["構文言い換え", "動詞"]
  },
  {
    id: "P1_113",
    sourceId: "IM143",
    a: "He makes a living by writing articles.",
    b: "He ( ) by writing articles.",
    choices: ["earns money to live", "changes his schedule", "finds useful advice", "improves his writing"],
    answer: "earns money to live",
    ja: "彼は記事を書いて生計を立てている。",
    note: "make a living = earn money to live（生計を立てる）\n選択肢:\nearns money to live = 生活のためのお金を稼ぐ\nchanges his schedule = 予定を変える\nfinds useful advice = 役立つ助言を見つける\nimproves his writing = 文章力を高める",
    tags: ["熟語→説明型", "生活"]
  },
  {
    id: "P1_114",
    sourceId: "IM144",
    a: "The nurse is on duty tonight.",
    b: "The nurse is ( ) tonight.",
    choices: ["working", "traveling", "resting", "studying"],
    answer: "working",
    ja: "その看護師は今夜勤務中だ。",
    note: "be on duty = be working（勤務中である）\n選択肢:\nworking = 働いている\ntraveling = 旅行している\nresting = 休んでいる\nstudying = 勉強している",
    tags: ["状態表現", "動詞"]
  },
  {
    id: "P1_115",
    sourceId: "IM145",
    a: "In case of fire, use these stairs.",
    b: "( ) there is a fire, use these stairs.",
    choices: ["If", "Though", "Before", "Since"],
    answer: "If",
    ja: "火事の場合には、この階段を使ってください。",
    note: "in case of = if there is（〜の場合には）\n選択肢:\nIf = もし〜なら\nThough = 〜だけれども\nBefore = 〜の前に\nSince = 〜なので / 〜以来",
    tags: ["前置詞句→説明型", "条件"]
  },
  {
    id: "P1_116",
    sourceId: "IM146",
    a: "They held a concert in honor of the famous singer.",
    b: "They held a concert to show ( ) the famous singer.",
    choices: ["respect for", "interest in", "fear of", "distance from"],
    answer: "respect for",
    ja: "彼らはその有名な歌手に敬意を表してコンサートを開いた。",
    note: "in honor of = to show respect for（〜に敬意を表して）\n選択肢:\nrespect for = 〜への敬意\ninterest in = 〜への興味\nfear of = 〜への恐れ\ndistance from = 〜からの距離",
    tags: ["前置詞句→説明型", "説明型"]
  },
  {
    id: "P1_117",
    sourceId: "IM147",
    a: "That restaurant has a good reputation.",
    b: "That restaurant is ( ).",
    choices: ["well thought of", "out of order", "short of staff", "under construction"],
    answer: "well thought of",
    ja: "そのレストランは評判がよい。",
    note: "have a good reputation = be well thought of（評判がよい）\n選択肢:\nwell thought of = 評判がよい\nout of order = 故障している\nshort of staff = 人手不足で\nunder construction = 建設中で",
    tags: ["名詞句→説明型", "状態"]
  },
  {
    id: "P1_118",
    sourceId: "IM148",
    a: "Aside from this one mistake, your essay is excellent.",
    b: "( ) this one mistake, your essay is excellent.",
    choices: ["Except for", "Along with", "Because of", "Instead of"],
    answer: "Except for",
    ja: "この一つのミスを除けば、あなたの作文はすばらしい。",
    note: "aside from = except for（〜を除けば）\n選択肢:\nExcept for = 〜を除けば\nAlong with = 〜と一緒に\nBecause of = 〜のために\nInstead of = 〜の代わりに",
    tags: ["前置詞表現", "除外"]
  },
  {
    id: "P1_119",
    sourceId: "IM149",
    a: "True happiness consists in being satisfied with what you have.",
    b: "True happiness ( ) being satisfied with what you have.",
    choices: ["lies in", "results from", "belongs to", "deals with"],
    answer: "lies in",
    ja: "本当の幸福は、自分の持っているものに満足することにある。",
    note: "consist in = lie in（〜にある）\n選択肢:\nlies in = 〜にある\nresults from = 〜から生じる\nbelongs to = 〜に属する\ndeals with = 〜を扱う",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_120",
    sourceId: "IM150",
    a: "Many English words derive from Latin.",
    b: "Many English words ( ) Latin.",
    choices: ["come from", "take after", "look into", "get over"],
    answer: "come from",
    ja: "多くの英単語はラテン語に由来する。",
    note: "derive from = come from（〜に由来する）\n選択肢:\ncome from = 〜に由来する / 〜から来る\ntake after = 〜に似る\nlook into = 〜を調べる\nget over = 〜を乗り越える / 回復する",
    tags: ["熟語⇄熟語", "動詞句"]
  },

      {
    id: "P1_121",
    sourceId: "IM005",
    a: "Ms. Brown is in charge of this project.",
    b: "Ms. Brown is ( ) this project.",
    choices: ["responsible for", "interested in", "familiar with", "different from"],
    answer: "responsible for",
    ja: "ブラウン先生がこの計画を担当している。",
    note: "be in charge of = be responsible for（〜を担当している）\n選択肢:\nresponsible for = 〜を担当している\ninterested in = 〜に興味がある\nfamiliar with = 〜によく通じている\ndifferent from = 〜と異なる",
    tags: ["句⇄形容詞句", "担当"]
  },
  {
    id: "P1_122",
    sourceId: "IM006",
    a: "Ken was absent from school yesterday.",
    b: "Ken ( ) school yesterday.",
    choices: ["missed", "attended", "visited", "finished"],
    answer: "missed",
    ja: "ケンは昨日学校を欠席した。",
    note: "be absent from = miss（〜を欠席する）\n選択肢:\nmissed = 欠席した / 逃した\nattended = 出席した\nvisited = 訪れた\nfinished = 終えた",
    tags: ["句→1語", "動詞"]
  },
  {
    id: "P1_123",
    sourceId: "IM011",
    a: "Small children rely on their parents.",
    b: "Small children ( ) their parents.",
    choices: ["depend on", "agree with", "look after", "compare with"],
    answer: "depend on",
    ja: "幼い子どもは親に頼っている。",
    note: "rely on = depend on（〜に頼る）\n選択肢:\ndepend on = 〜に頼る\nagree with = 〜に賛成する / 〜と一致する\nlook after = 〜の世話をする\ncompare with = 〜と比べる",
    tags: ["熟語⇄熟語", "動詞句"]
  },
  {
    id: "P1_124",
    sourceId: "IM012",
    a: "Our country is independent of foreign oil.",
    b: "Our country does not ( ) foreign oil.",
    choices: ["depend on", "believe in", "search for", "look after"],
    answer: "depend on",
    ja: "私たちの国は外国産の石油に頼っていない。",
    note: "be independent of = not depend on（〜に頼らない）\n選択肢:\ndepend on = 〜に頼る\nbelieve in = 〜を信じる\nsearch for = 〜を探す\nlook after = 〜の世話をする",
    tags: ["反対構文型言い換え", "動詞句"]
  },
  {
    id: "P1_125",
    sourceId: "IM019",
    a: "This decision will have an effect on our future.",
    b: "This decision will ( ) our future.",
    choices: ["affect", "respect", "decorate", "collect"],
    answer: "affect",
    ja: "この決定は私たちの将来に影響を与えるだろう。",
    note: "have an effect on = affect（〜に影響を与える）\n選択肢:\naffect = 影響を与える\nrespect = 尊敬する\ndecorate = 飾る\ncollect = 集める",
    tags: ["名詞化⇄動詞化", "動詞"]
  },
  {
    id: "P1_126",
    sourceId: "IM037",
    a: "In addition to English, she can speak French.",
    b: "She can speak French ( ) English.",
    choices: ["besides", "instead of", "because of", "without"],
    answer: "besides",
    ja: "彼女は英語に加えてフランス語も話せる。",
    note: "in addition to = besides（〜に加えて）\n選択肢:\nbesides = 〜に加えて\ninstead of = 〜の代わりに\nbecause of = 〜のために\nwithout = 〜なしで",
    tags: ["追加表現", "前置詞"]
  },
  {
    id: "P1_127",
    sourceId: "IM038",
    a: "He is likely to arrive late.",
    b: "He will ( ) arrive late.",
    choices: ["probably", "rarely", "suddenly", "nearly"],
    answer: "probably",
    ja: "彼はたぶん遅れて到着するだろう。",
    note: "be likely to = probably（たぶん〜する）\n選択肢:\nprobably = たぶん\nrarely = めったに〜ない\nsuddenly = 突然\nnearly = ほとんど / もう少しで",
    tags: ["構文→副詞", "副詞"]
  },
  {
    id: "P1_128",
    sourceId: "IM040",
    a: "I cannot help laughing when I hear that story.",
    b: "I cannot ( ) laughing when I hear that story.",
    choices: ["avoid", "finish", "suggest", "delay"],
    answer: "avoid",
    ja: "その話を聞くと笑わずにはいられない。",
    note: "cannot help doing = cannot avoid doing（〜せずにはいられない）\n選択肢:\navoid = 避ける\nfinish = 終える\nsuggest = 提案する\ndelay = 遅らせる",
    tags: ["構文言い換え", "動詞"]
  },
  {
    id: "P1_129",
    sourceId: "IM042",
    a: "She gets along with everyone in the class.",
    b: "She has a good ( ) with everyone in the class.",
    choices: ["relationship", "conversation", "competition", "appointment"],
    answer: "relationship",
    ja: "彼女はクラスの誰とでもうまくやっている。",
    note: "get along with = have a good relationship with（〜とうまくやる）\n選択肢:\nrelationship = 関係\nconversation = 会話\ncompetition = 競争\nappointment = 約束 /  नियुक्त",
    tags: ["熟語→説明型", "名詞"]
  },
  {
    id: "P1_130",
    sourceId: "IM044",
    a: "His son will take over the family business.",
    b: "His son will ( ) the family business.",
    choices: ["assume control of", "take part in", "make fun of", "run out of"],
    answer: "assume control of",
    ja: "彼の息子が家業を引き継ぐだろう。",
    note: "take over = assume control of（〜を引き継ぐ）\n選択肢:\nassume control of = 支配 / 管理を引き継ぐ\ntake part in = 〜に参加する\nmake fun of = 〜をからかう\nrun out of = 〜を使い果たす",
    tags: ["句動詞→説明型", "動詞句"]
  },
  {
    id: "P1_131",
    sourceId: "IM047",
    a: "There is no use arguing with him.",
    b: "It is ( ) argue with him.",
    choices: ["useless to", "safe to", "easy to", "fun to"],
    answer: "useless to",
    ja: "彼と口論してもむだだ。",
    note: "there is no use doing = it is useless to do（〜しても無駄だ）\n選択肢:\nuseless to = 〜しても無駄で\nsafe to = 〜しても安全で\neasy to = 〜しやすく\nfun to = 〜して楽しく",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_132",
    sourceId: "IM048",
    a: "There is no knowing what will happen next.",
    b: "It is ( ) what will happen next.",
    choices: ["impossible to know", "important to know", "easy to decide", "necessary to say"],
    answer: "impossible to know",
    ja: "次に何が起こるかはわからない。",
    note: "there is no knowing = it is impossible to know（〜はわからない）\n選択肢:\nimpossible to know = 知るのは不可能で\nimportant to know = 知ることが重要で\neasy to decide = 決めるのが簡単で\nnecessary to say = 言う必要があって",
    tags: ["構文言い換え", "説明型"]
  },
  {
    id: "P1_133",
    sourceId: "IM050",
    a: "Many people take clean water for granted.",
    b: "Many people fail to ( ) clean water.",
    choices: ["appreciate", "notice", "protect", "improve"],
    answer: "appreciate",
    ja: "多くの人はきれいな水を当然のものと思っている。",
    note: "take A for granted = fail to appreciate A（Aを当然のことと思う）\n選択肢:\nappreciate = ありがたみを理解する / 正当に評価する\nnotice = 気づく\nprotect = 守る\nimprove = 改善する",
    tags: ["熟語→説明型", "動詞"]
  },
  {
    id: "P1_134",
    sourceId: "IM057",
    a: "The damage resulted from the heavy rain.",
    b: "The damage ( ) the heavy rain.",
    choices: ["was caused by", "was proud of", "was ready for", "was similar to"],
    answer: "was caused by",
    ja: "その被害は大雨から生じた。",
    note: "result from = be caused by（〜が原因で起こる）\n選択肢:\nwas caused by = 〜によって引き起こされた\nwas proud of = 〜を誇りに思った\nwas ready for = 〜の準備ができていた\nwas similar to = 〜に似ていた",
    tags: ["因果表現", "受け身"]
  },
  {
    id: "P1_135",
    sourceId: "IM061",
    a: "The bad weather kept us from going out.",
    b: "The bad weather ( ) going out.",
    choices: ["prevented us from", "reminded us of", "compared us with", "invited us to"],
    answer: "prevented us from",
    ja: "悪天候のため私たちは外出できなかった。",
    note: "keep A from doing = prevent A from doing（Aが〜するのを妨げる）\n選択肢:\nprevented us from = 私たちが〜するのを妨げた\nreminded us of = 私たちに〜を思い出させた\ncompared us with = 私たちを〜と比較した\ninvited us to = 私たちを〜に招いた",
    tags: ["構文言い換え", "動詞句"]
  },
  {
    id: "P1_136",
    sourceId: "IM064",
    a: "They set off in search of a better life.",
    b: "They set off ( ) a better life.",
    choices: ["looking for", "thinking of", "making up", "calling off"],
    answer: "looking for",
    ja: "彼らはよりよい暮らしを求めて旅立った。",
    note: "in search of = looking for（〜を求めて / 探して）\n選択肢:\nlooking for = 探して / 求めて\nthinking of = 〜を考えて\nmaking up = 作り上げて / 仲直りして\ncalling off = 中止して",
    tags: ["前置詞句⇄熟語", "動詞句"]
  },
  {
    id: "P1_137",
    sourceId: "IM065",
    a: "She has made progress in math this year.",
    b: "She has ( ) in math this year.",
    choices: ["improved", "hesitated", "suffered", "participated"],
    answer: "improved",
    ja: "彼女は今年数学で進歩した。",
    note: "make progress in = improve（進歩する）\n選択肢:\nimproved = 進歩した / 改善した\nhesitated = ためらった\nsuffered = 苦しんだ\nparticipated = 参加した",
    tags: ["名詞化⇄動詞化", "動詞"]
  },
  {
    id: "P1_138",
    sourceId: "IM070",
    a: "We need to make room for new ideas.",
    b: "We need to ( ) new ideas.",
    choices: ["allow space for", "be short of", "put pressure on", "keep up with"],
    answer: "allow space for",
    ja: "私たちは新しい考えのための余地を作る必要がある。",
    note: "make room for = allow space for（〜のための余地を作る）\n選択肢:\nallow space for = 〜のための余地を作る\nbe short of = 〜が不足している\nput pressure on = 〜に圧力をかける\nkeep up with = 〜についていく",
    tags: ["熟語→説明型", "動詞句"]
  },
  {
    id: "P1_139",
    sourceId: "IM075",
    a: "She spoke on behalf of the whole team.",
    b: "She spoke ( ) the whole team.",
    choices: ["for", "against", "beyond", "inside"],
    answer: "for",
    ja: "彼女はチーム全体を代表して話した。",
    note: "on behalf of = for（〜を代表して ）\n選択肢:\nfor = 〜のために / 〜を代表して\nagainst = 〜に反対して\nbeyond = 〜を越えて\ninside = 〜の中に",
    tags: ["前置詞表現", "前置詞"]
  },
  {
    id: "P1_140",
    sourceId: "IM077",
    a: "With regard to this issue, we need more data.",
    b: "( ) this issue, we need more data.",
    choices: ["About", "Despite", "Beyond", "Around"],
    answer: "About",
    ja: "この問題に関しては、もっとデータが必要だ。",
    note: "with regard to = about（〜に関して）\n選択肢:\nAbout = 〜に関して\nDespite = 〜にもかかわらず\nBeyond = 〜を越えて\nAround = 〜の周りに / およそ",
    tags: ["前置詞表現", "前置詞"]
  },

      {
    id: "P1_141",
    sourceId: "IM004",
    a: "Teachers must deal with many different situations every day.",
    b: "Teachers must ( ) many different situations every day.",
    choices: ["handle", "invent", "ignore", "collect"],
    answer: "handle",
    ja: "教師は毎日多くの異なる状況に対処しなければならない。",
    note: "deal with = handle（〜に対処する）\n選択肢:\nhandle = 対処する\ninvent = 発明する\nignore = 無視する\ncollect = 集める",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_142",
    sourceId: "IM007",
    a: "I came across an old photo in the drawer.",
    b: "I ( ) an old photo in the drawer.",
    choices: ["happened to find", "decided to keep", "wanted to show", "managed to hide"],
    answer: "happened to find",
    ja: "私は引き出しの中で古い写真を偶然見つけた。",
    note: "come across = happen to find（偶然見つける）\n選択肢:\nhappened to = 偶然~する\ndecided to keep = 取っておくことにした\nwanted to show = 見せたかった\nmanaged to hide = なんとか隠した",
    tags: ["句動詞→説明型", "動詞句"]
  },
  {
    id: "P1_143",
    sourceId: "IM015",
    a: "They had to call off the baseball game.",
    b: "They had to ( ) the baseball game.",
    choices: ["cancel", "watch", "record", "win"],
    answer: "cancel",
    ja: "彼らはその野球の試合を中止しなければならなかった。",
    note: "call off = cancel（〜を中止する）\n選択肢:\ncancel = 中止する\nwatch = 見る\nrecord = 記録する\nwin = 勝つ",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_144",
    sourceId: "IM020",
    a: "Her grandfather passed away last winter.",
    b: "Her grandfather ( ) last winter.",
    choices: ["died", "retired", "traveled", "recovered"],
    answer: "died",
    ja: "彼女の祖父は昨年の冬に亡くなった。",
    note: "pass away = die（亡くなる）\n選択肢:\ndied = 亡くなった\nretired = 退職した\ntraveled = 旅行した\nrecovered = 回復した",
    tags: ["婉曲表現→1語", "動詞"]
  },
  {
    id: "P1_145",
    sourceId: "IM055",
    a: "A fire broke out in the old building.",
    b: "A fire ( ) in the old building.",
    choices: ["started suddenly", "was prevented", "was reported", "came to an end"],
    answer: "started suddenly",
    ja: "その古い建物で火事が突然起こった。",
    note: "break out = start suddenly（突然起こる）\n選択肢:\nstarted suddenly = 突然始まった\nwas prevented = 防がれた\nwas reported = 報告された\ncame to an end = 終わった",
    tags: ["句動詞→説明型", "動詞句"]
  },
  {
    id: "P1_146",
    sourceId: "IM056",
    a: "The new policy may bring about major changes.",
    b: "The new policy may ( ) major changes.",
    choices: ["cause", "measure", "hide", "delay"],
    answer: "cause",
    ja: "その新しい方針は大きな変化を引き起こすかもしれない。",
    note: "bring about = cause（〜を引き起こす）\n選択肢:\ncause = 引き起こす\nmeasure = 測る\nhide = 隠す\ndelay = 遅らせる",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_147",
    sourceId: "IM079",
    a: "In terms of safety, this car is excellent.",
    b: "( ) safety, this car is excellent.",
    choices: ["With respect to", "In place of", "Because of", "In spite of"],
    answer: "With respect to",
    ja: "安全性の観点では、この車はすばらしい。",
    note: "in terms of = with respect to（〜の観点では / 〜に関して）\n選択肢:\nWith respect to = 〜に関して\nIn place of = 〜の代わりに\nBecause of = 〜のために\nIn spite of = 〜にもかかわらず",
    tags: ["前置詞表現", "句"]
  },
  {
    id: "P1_148",
    sourceId: "IM084",
    a: "This method is superior to the old one.",
    b: "This method is ( ) the old one.",
    choices: ["better than", "similar to", "equal to", "close to"],
    answer: "better than",
    ja: "この方法は古い方法より優れている。",
    note: "be superior to = be better than（〜より優れている）\n選択肢:\nbetter than = 〜より優れている\nsimilar to = 〜に似ている\nequal to = 〜と等しい\nclose to = 〜に近い",
    tags: ["比較表現", "形容詞句"]
  },
  {
    id: "P1_149",
    sourceId: "IM085",
    a: "The second plan is inferior to the first one.",
    b: "The second plan is ( ) the first one.",
    choices: ["worse than", "equal to", "newer than", "closer to"],
    answer: "worse than",
    ja: "2つ目の案は1つ目の案より劣っている。",
    note: "be inferior to = be worse than（〜より劣っている）\n選択肢:\nworse than = 〜より悪い / 劣っている\nequal to = 〜と等しい\nnewer than = 〜より新しい\ncloser to = 〜により近い",
    tags: ["比較表現", "形容詞句"]
  },
  {
    id: "P1_150",
    sourceId: "IM124",
    a: "I dropped in on my aunt after school.",
    b: "I ( ) my aunt after school.",
    choices: ["stopped by", "looked after", "ran away from", "put up with"],
    answer: "stopped by",
    ja: "私は放課後、おばの家にふらっと立ち寄った。",
    note: "drop in on = stop by（〜にふらっと立ち寄る）\n選択肢:\nstopped by = 立ち寄った\nlooked after = 世話をした\nran away from = 〜から逃げた\nput up with = 〜を我慢した",
    tags: ["句動詞→説明型", "動詞句"]
  },
  {
    id: "P1_151",
    sourceId: "IM014",
    a: "The train was delayed due to dense fog.",
    b: "The train was delayed ( ) dense fog.",
    choices: ["because of", "instead of", "regardless of", "such as"],
    answer: "because of",
    ja: "濃い霧のため、その電車は遅れた。",
    note: "due to = because of（〜のために）\n選択肢:\nbecause of = 〜のために\ninstead of = 〜の代わりに\nregardless of = 〜に関係なく\nsuch as = 例えば〜のような",
    tags: ["原因表現", "前置詞句"]
  },
  {
    id: "P1_152",
    sourceId: "IM025",
    a: "Everyone in the town looks up to her.",
    b: "Everyone in the town ( ) her.",
    choices: ["respects", "supports", "notices", "blames"],
    answer: "respects",
    ja: "町の誰もが彼女を尊敬している。",
    note: "look up to = respect（〜を尊敬する）\n選択肢:\nrespects = 尊敬する\nsupports = 支える / 支持する\nnotices = 気づく\nblames = 非難する",
    tags: ["句動詞→1語", "動詞"]
  },
  {
    id: "P1_153",
    sourceId: "IM052",
    a: "We must get rid of this broken chair.",
    b: "We must ( ) this broken chair.",
    choices: ["remove", "repair", "borrow", "follow"],
    answer: "remove",
    ja: "この壊れた椅子を取り除かなければならない。",
    note: "get rid of = remove（〜を取り除く）\n選択肢:\nremove = 取り除く\nrepair = 修理する\nborrow = 借りる\nfollow = 従う / 後について行く",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_154",
    sourceId: "IM062",
    a: "This village is known for its hot springs.",
    b: "This village is ( ) its hot springs.",
    choices: ["famous for", "free from", "late for", "afraid of"],
    answer: "famous for",
    ja: "この村は温泉で知られている。",
    note: "be known for = be famous for（〜で知られている）\n選択肢:\nfamous for = 〜で有名である\nfree from = 〜から自由である\nlate for = 〜に遅れている\nafraid of = 〜を恐れている",
    tags: ["形容詞句言い換え", "形容詞句"]
  },
  {
    id: "P1_155",
    sourceId: "IM083",
    a: "We had no choice but to leave early.",
    b: "We were ( ) leave early.",
    choices: ["forced to", "free to", "glad to", "likely to"],
    answer: "forced to",
    ja: "私たちは早く出発するしかなかった。",
    note: "have no choice but to = be forced to（〜するしかない）\n選択肢:\nforced to = 〜せざるを得なくて\nfree to = 自由に〜できて\nglad to = 〜してうれしくて\nlikely to = 〜しそうで",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_156",
    sourceId: "IM121",
    a: "They are looking forward to the school trip.",
    b: "They are ( ) the school trip.",
    choices: ["awaiting", "avoiding", "canceling", "reporting"],
    answer: "awaiting",
    ja: "彼らは修学旅行を楽しみに待っている。",
    note: "look forward to = await（〜を楽しみに待つ）\n選択肢:\nawaiting = 待っている\navoiding = 避けている\ncanceling = 中止している\nreporting = 報告している",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_157",
    sourceId: "IM132",
    a: "The speaker put emphasis on the final point.",
    b: "The speaker ( ) the final point.",
    choices: ["emphasized", "repaired", "observed", "divided"],
    answer: "emphasized",
    ja: "その話し手は最後の点を強調した。",
    note: "put emphasis on = emphasize（〜を強調する）\n選択肢:\nemphasized = 強調した\nrepaired = 修理した\nobserved = 観察した\ndivided = 分けた",
    tags: ["熟語→1語", "動詞"]
  },
  {
    id: "P1_158",
    sourceId: "IM111",
    a: "It is hard for some families to make ends meet.",
    b: "It is hard for some families to ( ).",
    choices: ["have enough money to live", "win every contest", "travel around the world", "avoid all mistakes"],
    answer: "have enough money to live",
    ja: "家庭によっては、生活していくだけのお金を得るのが難しい。",
    note: "make ends meet = have enough money to live（どうにかやりくりする）\n選択肢:\nhave enough money to live = 生活できるだけのお金がある\nwin every contest = すべての大会で勝つ\ntravel around the world = 世界中を旅行する\navoid all mistakes = すべての間違いを避ける",
    tags: ["熟語→説明型", "生活"]
  },
  {
    id: "P1_159",
    sourceId: "IM106",
    a: "This plan is bound to fail.",
    b: "This plan is ( ) fail.",
    choices: ["sure to", "ready to", "glad to", "able to"],
    answer: "sure to",
    ja: "この計画はきっと失敗する。",
    note: "be bound to = be sure to / be certain to（きっと〜する）\n選択肢:\nsure to = きっと〜する\nready to = 〜する準備ができて\nglad to = 〜してうれしくて\nable to = 〜できて",
    tags: ["構文言い換え", "形容詞句"]
  },
  {
    id: "P1_160",
    sourceId: "IM143",
    a: "After graduating, she had to make a living by herself.",
    b: "After graduating, she needed to ( ) by herself.",
    choices: ["support herself", "introduce herself", "enjoy herself", "hide herself"],
    answer: "support herself",
    ja: "卒業後、彼女は自分で生計を立てなければならなかった。",
    note: "make a living = support oneself / earn money to live（生計を立てる）\n選択肢:\nsupport herself = 自活する / 自分を養う\nintroduce herself = 自己紹介する\nenjoy herself = 楽しむ\nhide herself = 身を隠す",
    tags: ["熟語→説明型", "生活"]
  }

];
