const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
const source=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
function storage(){const data=new Map();return {get length(){return data.size},key:i=>[...data.keys()][i]??null,getItem:k=>data.get(k)??null,setItem(k,v){data.set(k,String(v))},removeItem:k=>data.delete(k)}}
function page(native,locks={request:(name,opts,fn)=>fn({})}){const c={localStorage:native,TextEncoder,Event,crypto:crypto.webcrypto,navigator:{locks},addEventListener(){},dispatchEvent(){},alert(){}};c.window=c;vm.createContext(c);for(const f of ['cloud_schema.js','cloud_storage.js'])vm.runInContext(source(f),c);return c;}
const key='q7SetHistory_v1';
test('Guest data unchanged; accounts and old tabs remain isolated',()=>{const n=storage(),g=page(n);g.GOIMONStorage.setItem(key,'{"guest":1}');g.GOIMONProfiles.activate('A');const a=page(n);assert.equal(a.GOIMONStorage.getItem(key),null);a.GOIMONStorage.setItem(key,'{"a":1}');a.GOIMONProfiles.activate('B');const b=page(n);assert.equal(b.GOIMONStorage.getItem(key),null);b.GOIMONStorage.setItem(key,'{"b":1}');a.GOIMONStorage.setItem(key,'{"a":2}');assert.equal(b.GOIMONStorage.getItem(key),'{"b":1}');b.GOIMONProfiles.logout();assert.equal(page(n).GOIMONStorage.getItem(key),'{"guest":1}');});
test('Same-key stale tab write is preserved separately, never overwrites newer data',()=>{const n=storage();page(n).GOIMONProfiles.activate('A');const a=page(n),b=page(n);a.GOIMONStorage.getItem(key);b.GOIMONStorage.getItem(key);a.GOIMONStorage.setItem(key,'{"a":1}');assert.throws(()=>b.GOIMONStorage.setItem(key,'{"b":1}'));assert.equal(a.GOIMONStorage.getItem(key),'{"a":1}');assert([...Array(n.length)].map((_,i)=>n.key(i)).some(k=>k.includes('recovery:')));});
test('Quota failure cannot partially replace account profile or original data',()=>{const n=storage(),g=page(n);n.setItem(key,'{}');g.GOIMONProfiles.activate('A');const a=page(n);const original=n.setItem;n.setItem=()=>{throw Error('QuotaExceededError')};assert.throws(()=>a.GOIMONStorage.setItem(key,'{}'));n.setItem=original;assert.equal(a.GOIMONProfiles.read('A').data[key],undefined);assert.equal(a.GOIMONPendingRecovery.profile.data[key],'{}');assert.equal(n.getItem(key),'{}');});
test('Three-way merge preserves independent changes, deletions; blocks divergent updates',()=>{const {merge}=page(storage()).GOIMONCloudSchema;let m=merge({a:'1',b:'1'},{a:'2',b:'1'},{a:'1',b:'2'});assert.equal(m.data.a,'2');assert.equal(m.data.b,'2');assert.equal(m.conflicts.length,0);m=merge({a:'1'},{a:'2'},{a:'3'});assert.equal(m.conflicts[0],'a');m=merge({a:'1'},{},{a:'1'});assert.equal(m.data.a,undefined);});
test('Allowlist includes previous omissions; rejects settings, credentials and prototype injection',()=>{const s=page(storage()).GOIMONCloudSchema;for(const k of ['zensho_goimon_learning_achievements_v1_lv1','zensho_block_stats_enja_v1_lv1','goimon_dialogue_history_v2'])assert(s.allowed(k));for(const k of ['token','q7Sessions_v1','zensho_quiz_settings_enja_v1_lv1'])assert(!s.allowed(k));assert.throws(()=>s.validate({schemaVersion:1,data:{[key]:'{"__proto__":{}}'}}));assert.throws(()=>s.validate({schemaVersion:1,data:{[key]:'null'}}));});
test('Every app HTML loads storage adapter before app scripts; original storage access removed',()=>{for(const f of fs.readdirSync(require('node:path').join(__dirname,'..'))){if(f.endsWith('.html')&&f!=='google1d6eafb09b9c3b78.html'){const t=source(f);assert(t.includes('src="cloud_storage.js"'),f);assert(t.indexOf('cloud_storage.js')<t.indexOf('</head>'),f);}if(f.endsWith('.js')&&!f.startsWith('cloud_')&&f!=='goimon_save_foundation.js')assert(!/\blocalStorage\b/.test(source(f)),f);}});

test('Startup writes wait for the account lock; denied tabs preserve pending work only',async()=>{const n=storage();page(n).GOIMONProfiles.activate('A');let acquire;const a=page(n,{request:(name,opts,fn)=>{acquire=fn}});a.GOIMONStorage.setItem(key,'{"first":1}');assert.equal(a.GOIMONProfiles.read('A').data[key],undefined);acquire({});assert.equal(a.GOIMONProfiles.read('A').data[key],'{"first":1}');const b=page(n,{request:(name,opts,fn)=>fn(null)});assert.throws(()=>b.GOIMONStorage.setItem(key,'{"blocked":1}'));assert.equal(a.GOIMONProfiles.read('A').data[key],'{"first":1}');assert.equal(b.GOIMONPendingRecovery.profile.data[key],'{"blocked":1}');});
