const {chromium}=require('playwright'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
(async()=>{const root=path.join(__dirname,'..'),server=spawn(process.execPath,['preview-server.cjs'],{cwd:root,env:{...process.env,GOIMON_PREVIEW_PORT:'8891'}});let browser;try{await new Promise(r=>server.stdout.once('data',r));browser=await chromium.launch({headless:true,...(process.env.GOIMON_CHROMIUM_PATH?{executablePath:process.env.GOIMON_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu']}:{})});const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://localhost:8891/index.html');
const toggle=p.locator('#goimon-menu-toggle'),dialog=p.locator('#goimon-navigation');await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');assert.equal(await dialog.evaluate(d=>d.open),true);assert.equal(await p.evaluate(()=>document.body.style.overflow),'hidden');
for(let i=0;i<24;i++){await p.keyboard.press('Tab');assert.equal(await dialog.evaluate(d=>d.contains(document.activeElement)),true);}
await p.keyboard.press('Escape');assert.equal(await dialog.evaluate(d=>d.open),false);assert.equal(await p.evaluate(()=>document.activeElement.id),'goimon-menu-toggle');assert.equal(await p.evaluate(()=>document.body.style.overflow),'');
await toggle.click();await dialog.locator('summary').click();for(const href of await dialog.locator('a').evaluateAll(a=>a.map(x=>x.getAttribute('href')).filter(x=>!x.startsWith('mailto:')))){assert(fs.existsSync(path.join(root,href.split('?')[0])),href);}
await dialog.locator('[data-panel="goimon"]').click();await p.waitForFunction(()=>document.querySelector('#goimonSheet').classList.contains('show'));await p.locator('#closeGoimonSheet').click();await toggle.click();await dialog.locator('[data-panel="dex"]').click();await p.waitForFunction(()=>document.querySelector('#goimonDexModal').classList.contains('show'));await p.locator('#closeGoimonDexBtn').click();
await p.goto('http://localhost:8891/quiz.html');await toggle.click();await dialog.locator('[data-panel="dex"]').click();await p.waitForFunction(()=>document.querySelector('#goimonDexModal')?.classList.contains('show'));assert.equal(new URL(p.url()).search,'');await p.locator('#closeGoimonDexBtn').click();
await toggle.click();await dialog.locator('a[href="progress.html"]').click();await p.waitForURL('**/progress.html');await toggle.click();await dialog.locator('a[href="cloud.html"]').click();await p.waitForURL('**/cloud.html');
await p.goto('http://localhost:8891/index.html');const cta=p.locator('#goimonAdviceActionBtn');await cta.waitFor({state:'visible'});assert.equal(await cta.evaluate(e=>getComputedStyle(e).borderRadius),'12px');await cta.click();await p.waitForURL(url=>!url.pathname.endsWith('/index.html'));
console.log('PASS: mobile drawer, keyboard focus/Escape, existing GOIMON/dex dialogs, cross-page deep link, progress/profile navigation and CTA destination');
await p.goto('http://localhost:8891/index.html');
if(process.env.GOIMON_TEST_FONT_DIR){const dir=process.env.GOIMON_TEST_FONT_DIR;let css=fs.readFileSync(path.join(dir,'400.css'),'utf8');css=css.replace(/url\(([^)]+)\)/g,(_,u)=>'url(data:font/woff2;base64,'+fs.readFileSync(path.join(dir,u.replace(/['"]/g,''))).toString('base64')+')');await p.addStyleTag({content:css+'body,button,a,#goimon-account-bar,#goimon-navigation{font-family:"Noto Sans JP",sans-serif!important}'});await p.evaluate(()=>document.fonts.ready);}
await toggle.click();assert.equal(await dialog.evaluate(d=>d.scrollWidth<=d.clientWidth),true);await p.screenshot({path:process.env.GOIMON_MENU_SCREENSHOT||'/tmp/goimon-menu.png'});await p.locator('.gn-close').click();await cta.scrollIntoViewIfNeeded();await cta.locator('xpath=ancestor::*[contains(@class,"goimonHomeSpeech")]').last().screenshot({path:process.env.GOIMON_CTA_SCREENSHOT||'/tmp/goimon-cta.png'});
await p.setViewportSize({width:1280,height:900});await toggle.click();assert.equal(await dialog.evaluate(d=>d.getBoundingClientRect().width),360);await p.mouse.click(1000,200);assert.equal(await dialog.evaluate(d=>d.open),false);assert.deepEqual(errors,[]);console.log('PASS: mobile/desktop layout and backdrop close; no JavaScript errors');
}finally{await browser?.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
